# src/wxui/wxui_code.cmake --- these are the files generated by wxUiEditor

set( file_list

    src/wxUiEditor.rc           # Only processed when compiling for Windows, ignored otherwise

    src/mainapp.cpp             # Main application class
    src/mainframe.cpp           # Main window frame
    src/mainframe_events.cpp    # Main window frame event handlers
    src/mainframe_updates.cpp   # Main window frame event handlers
    src/assertion_dlg.cpp       # Assertion Dialog

    src/bitmaps.cpp             # Map of bitmaps accessed by name
    src/clipboard.cpp           # Handles reading and writing OS clipboard data
    src/cstm_event.cpp          # Custom Event handling
    src/frame_status_bar.cpp    # MainFrame status bar functions
    src/gen_enums.cpp           # Enumerations for generators
    src/id_lists.cpp            # wxID_ strings
    src/preferences.cpp         # Prefs/UserPrefs -- Set/Get wxUiEditor preferences
    src/previews.cpp            # Top level Preview functions
    src/undo_cmds.cpp           # Undoable command classes derived from UndoStackCmd
    src/undo_stack.cpp          # Maintain an undo and redo stack
    src/wakatime.cpp            # Updates WakaTime metrics

    src/ui/startup_dlg.cpp      # Dialog to display if wxUiEditor is launched with no arguments

    src/wxue_namespace/wxue.cpp
    src/wxue_namespace/wxue_string.cpp          # wxue::wxue::string class
    src/wxue_namespace/wxue_string_view.cpp     # wxue::string_view class
    src/wxue_namespace/wxue_string_vector.cpp   # wxue::string_vector class
    src/wxue_namespace/wxue_view_vector.cpp     # wxue::view_vector class

    # Custom property handling for Property Grid panel
    src/customprops/code_single_prop.cpp      # EditCodeSingleProperty -- Derived wxStringProperty class for single line code
    src/customprops/code_string_prop.cpp      # EditCodeProperty --Derived wxStringProperty class for code
    src/customprops/custom_colour_prop.cpp    # EditColourProperty -- Property editor for colour
    src/customprops/custom_param_prop.cpp     # EditParamProperty -- Derived wxStringProperty class for custom control parameters
    src/customprops/directory_prop.cpp        # DirectoryProperty -- Derived wxStringProperty class for choosing a directory
    src/customprops/edit_custom_mockup.cpp    # Custom Property editor for pop_custom_mockup
    src/customprops/evt_string_prop.cpp       # EventStringProperty -- Derived wxStringProperty class for event function
    src/customprops/font_string_prop.cpp      # FontStringProperty -- Derived wxStringProperty class for font property
    src/customprops/html_string_prop.cpp      # EditHtmlProperty - Derived wxStringProperty class for HTML
    src/customprops/id_prop.cpp               # ID_Property -- Uses IDEditorDlg to edit a custom ID
    src/customprops/img_string_prop.cpp       # ImageDialogAdapter -- used by ImageStringProperty (img_string_prop.h)
    src/customprops/include_files_prop.cpp    # IncludeFilesProperty -- Derived wxStringProperty class for Include Files
    src/customprops/rearrange_prop.cpp        # RearrangeProperty -- wxRearangeList contents editor
    src/customprops/sb_fields_prop.cpp        # SBarFieldsProperty -- Property editor for status bar fields
    src/customprops/sizer_grow_columns.cpp    # GrowColumnsProperty -- Property editor for Growable Sizer Columns
    src/customprops/sizer_grow_rows.cpp       # GrowRowsProperty -- Property editor for Growable Sizer Rows
    src/customprops/txt_string_prop.cpp       # EditStringProperty -- Derived wxStringProperty class for single-line text

    src/customprops/eventhandler_dlg.cpp      # EventHandlerDlg -- Dialog for editing event handlers
    src/customprops/font_prop_dlg.cpp         # FontPropDlg -- Dialog for editing Font Property
    src/customprops/img_props.cpp             # ImageProperties -- Handles property grid image properties

    src/customprops/tt_file_property.cpp      # ttFileProperty -- Version of wxFileProperty specific to wxUiEditor

    src/customprops/pg_image.cpp         # PropertyGrid_Image -- Custom property grid class for images
    src/customprops/pg_animation.cpp     # PropertyGrid_Animation -- Custom property grid class for animations
    src/customprops/pg_point.cpp         # CustomPointProperty -- Custom wxPGProperty for wxPoint

    # (generated) customprops/art_prop_dlg.cpp        # Art Property Dialog for image property
    # (generated) customprops/include_files_dlg.cpp
    # (generated) customprops/id_editor_dlg.cpp
    src/custom_ctrls/colour_rect_ctrl.cpp # ColourRectCtrl -- Control that displays a solid color
    src/custom_ctrls/kw_color_picker.cpp # kwColourPickerCtrl -- Modified version of wxColourPickerCtrl

    # Code generation modules
    src/generate/writers/code.cpp              # Code -- Helper class for generating code
    src/generate/writers/code_add.cpp          # Code::Add...() functions
    src/generate/writers/code_bundle.cpp       # Code::Bundle() functions
    src/generate/writers/code_gen.cpp          # Code::Gen...() functions
    src/generate/writers/code_pos_style.cpp    # Code::Pose...()/Style() functions
    src/generate/writers/code_size_pos.cpp     # Code::Pose...()/Style() functions
    src/generate/writers/code_string.cpp       # Code::Pose...()/Style() functions
    src/generate/writers/language_traits.cpp   # LanguageTraits -- Language characteristics for code generation
    src/generate/writers/strategy_cpp.cpp      # CppStrategy -- C++ language strategy
    src/generate/writers/strategy_cwrapper.cpp  # CWrapperStrategy/WxBindingStrategy -- Shared non-C++ base
    src/generate/writers/strategy_ffi.cpp      # FFIStrategy -- Shared FFI language strategy base
    src/generate/writers/strategy_fortran.cpp  # FortranStrategy -- Fortran language strategy
    src/generate/writers/strategy_go.cpp       # GoStrategy -- Go language strategy
    src/generate/writers/strategy_julia.cpp    # JuliaStrategy -- Julia language strategy
    src/generate/writers/strategy_luajit.cpp   # LuaJITStrategy -- LuaJIT language strategy
    src/generate/writers/strategy_python.cpp   # PythonStrategy -- Python language strategy
    src/generate/writers/strategy_ruby.cpp     # RubyStrategy -- Ruby language strategy
    src/generate/writers/strategy_typescript.cpp  # TypeScriptStrategy -- TypeScript language strategy
    src/generate/writers/comment_blocks.cpp    # Shared generated comment blocks
    src/generate/writers/common_strings.cpp    # Common strings used by code generators

    src/generate/writers/file_codewriter.cpp   # FileCodeWriter -- Class to write code to disk
    src/generate/writers/gen_base.cpp          # BaseCodeGenerator -- Generate Src and Hdr files for Base and Derived Class
    src/generate/writers/gen_codefiles.cpp     # Generate code functions
    src/generate/writers/gen_construction.cpp  # Top level Object construction code
    src/generate/writers/gen_cmake.cpp         # Auto-generate a .cmake file
    src/generate/writers/gen_events.cpp        # Generate events for all languages
    src/generate/writers/write_code.cpp        # Write code to Scintilla or file
    src/generate/writers/image_gen.cpp         # Functions for generating embedded images

    src/generate/base_generator.cpp    # BaseGenerator -- Base widget generator class
    src/generate/gen_initialize.cpp    # Initialize all widget generate classes
    src/generate/gen_common.cpp        # Common widget generation functions
    src/generate/gen_results.cpp       # GenResults -- Code generation results class

    src/generate/gen_xrc_utils.cpp     # Common XRC generating functions
    src/generate/gen_book_utils.cpp    # Common Book utilities
    src/generate/utils_prop_grid.cpp   # PropertyGrid utilities

    # ############################ begin generators ##############################

    # Code generation output languages
    src/generate/writers/gen_cpp.cpp           # Generate C++ code
    src/generate/writers/gen_cpp_header.cpp    # Generate C++ code header content
    src/generate/writers/gen_cpp_variables.cpp # C++ code generation variable and validator functions
    src/generate/writers/gen_derived.cpp       # Generate C++ Derived code

    src/generate/writers/gen_python.cpp        # Generate wxPython code
    src/generate/writers/gen_ruby.cpp          # Generate wxRuby3 code

    src/generate/writers/gen_fortran.cpp       # Generate Fortran code via kwxFFI
    src/generate/writers/gen_go.cpp            # Generate Go code via kwxFFI
    src/generate/writers/gen_julia.cpp         # Generate Julia code via kwxFFI
    src/generate/writers/gen_luajit.cpp        # Generate LuaJIT code via kwxFFI
    src/generate/writers/gen_typescript.cpp     # Generate TypeScript code via kwxFFI

    src/generate/writers/gen_script_common.cpp # Common functions for generating Script Languages
    src/generate/writers/gen_xrc.cpp           # Generate XRC
    src/generate/writers/verify_codegen.cpp    # Verify that code generation did not change

    # Generators are responsible for displaying the widget in the Mockup window,
    # and generating both C++, Python, Ruby and XRC code. If the generated object
    # can be used in a Dialog or Frame, then the generator must also be able to
    # create a preview of the object for the Preview display.
    src/generate/gen_images_list.cpp    # Images List Embedded images generator
    src/generate/gen_data_list.cpp      # Data List generator
    src/generate/gen_project.cpp        # Project generator

    # Misc widgets
    src/generate/dataview_widgets.cpp      # wxDataView generation classes
    src/generate/gen_activity.cpp          # wxActivityIndicator generator
    src/generate/gen_animation.cpp         # wxAnimationCtrl generator
    src/generate/gen_banner_window.cpp     # wxBannerWindow generator
    src/generate/gen_bitmap_combo.cpp      # wxBitmapComboBox generator
    src/generate/gen_button.cpp            # wxButton generator
    src/generate/gen_calendar_ctrl.cpp     # wxCalendarCtrl generator
    src/generate/gen_check_listbox.cpp     # wxCheckListBox generator
    src/generate/gen_checkbox.cpp          # wxCheckBox generator
    src/generate/gen_choice.cpp            # wxChoice generator
    src/generate/gen_close_btn.cpp         # wxBitmapButton::CreateCloseButton generator
    src/generate/gen_cmd_link_btn.cpp      # wxCommandLinkButton generator
    src/generate/gen_combobox.cpp          # wxComboBox generator
    src/generate/gen_ctx_help_btn.cpp      # wxContextHelpButton generator
    src/generate/gen_custom_ctrl.cpp       # Custom Control generator
    src/generate/gen_edit_listbox.cpp      # wxEditableListBox generator
    src/generate/gen_file_ctrl.cpp         # wxFileCtrl generator
    src/generate/gen_gauge.cpp             # wxGauge generator
    src/generate/gen_grid.cpp              # wxGrid generator
    src/generate/gen_html_listbox.cpp      # wxSimpleHtmlListBox generator
    src/generate/gen_html_window.cpp       # wxHtmlWindow generator
    src/generate/gen_hyperlink.cpp         # wxHyperlinkCtrl generator
    src/generate/gen_infobar.cpp           # wxInfoBar generator
    src/generate/gen_listbox.cpp           # wxListBox generator
    src/generate/gen_listview.cpp          # wxListView generator
    src/generate/gen_radio_box.cpp         # wxRadioBox generator
    src/generate/gen_radio_btn.cpp         # wxRadioButton generator
    src/generate/gen_rearrange.cpp         # wxRearrangeCtrl generator
    src/generate/gen_rich_text.cpp         # wxRichTextCtrl generator
    src/generate/gen_scrollbar.cpp         # wxScrollBar generator
    src/generate/gen_search_ctrl.cpp       # wxSearchCtrl generator
    src/generate/gen_slider.cpp            # wxSlider generator
    src/generate/gen_spin_btn.cpp          # wxSpinButton generator
    src/generate/gen_spin_ctrl.cpp         # wxSpinCtrl generator
    src/generate/gen_static_bmp.cpp        # wxStaticBitmap generator
    src/generate/gen_static_box.cpp        # wxStaticBox generator
    src/generate/gen_static_line.cpp       # wxStaticLine generator
    src/generate/gen_static_text.cpp       # wxStaticText generator
    src/generate/gen_status_bar.cpp        # wxStatusBar generator
    src/generate/gen_styled_text.cpp       # wxStyledText (scintilla) generate
    src/generate/gen_text_ctrl.cpp         # wxTextCtrl generator
    src/generate/gen_timer.cpp             # wxTimer generator
    src/generate/gen_toggle_btn.cpp        # wxToggleButton generator
    src/generate/gen_tree_ctrl.cpp         # wxTreeCtrl generator
    src/generate/gen_tree_list.cpp         # wxTreeListCtrl generator
    src/generate/gen_web_view.cpp          # wxWebView generator

    # Non-python widgets
    src/generate/gen_dir_ctrl.cpp          # wxGenericDirCtrl generator

    # Books
    src/generate/gen_aui_notebook.cpp     # wxAuiNotebook generator
    src/generate/gen_book_page.cpp        # Book page generator
    src/generate/gen_choicebook.cpp       # wxChoicebook generator
    src/generate/gen_listbook.cpp         # wxListbook generator
    src/generate/gen_notebook.cpp         # wxNotebook generator
    src/generate/gen_page_ctrl.cpp        # Page control generator
    src/generate/gen_simplebook.cpp       # wxSimplebook generator
    src/generate/gen_toolbook.cpp         # wxToolbook generator
    src/generate/gen_treebook.cpp         # wxTreebook generator

    # Containers
    src/generate/gen_collapsible.cpp      # wxCollapsiblePane generator
    src/generate/gen_panel.cpp            # wxPanel generator
    src/generate/gen_split_win.cpp        # wxSplitterWindow generator
    src/generate/window_widgets.cpp       # ScrolledCanvasGenerator and ScrolledWindowGenerator

    # Document Management (MDI)
    src/newdialogs/new_mdi.cpp                   # Dialog for creating a new MDI application

    src/generate/mdi/gen_doc_view_app.cpp        # Generates base class for wxDocument/wxView applications

    src/generate/mdi/gen_doc_image.cpp           # wxImage document class
    src/generate/mdi/gen_doc_richtext.cpp        # wxRichTextCtrl document class
    src/generate/mdi/gen_doc_splitter.cpp        # wxSplitterWindow document class
    src/generate/mdi/gen_doc_scintilla.cpp       # Scintilla document class
    src/generate/mdi/gen_doc_textctrl.cpp        # wxTextCtrl document class

    src/generate/mdi/gen_view_image.cpp          # wxImage view class
    src/generate/mdi/gen_view_richtext.cpp       # wxRichTextCtrl view class
    src/generate/mdi/gen_view_splitter.cpp       # wxSplitterWindow view class
    src/generate/mdi/gen_view_scintilla.cpp      # wxStyledTextCtrl view class
    src/generate/mdi/gen_view_textctrl.cpp       # wxTextCtrl view class

    src/generate/mdi/gen_doc_parent_frame.cpp    # wxDocParentFrame generator
    src/generate/mdi/gen_doc_mdi_frame.cpp       # wxDocMdiParentFrame generator
    src/generate/mdi/gen_aui_mdi_frame.cpp       # wxAuiMDIParentFrame generator

    src/generate/mdi/gen_mdi_menu.cpp            # Menu bar classes for an MDI frame

    # Forms
    src/generate/gen_dialog.cpp              # wxDialog generator
    src/generate/gen_frame.cpp               # wxFrame generator
    src/generate/gen_panel_form.cpp          # wxPanel Form generator
    src/generate/gen_popup_win.cpp           # wxPopupTransientWindow generator
    src/generate/gen_propsheet_dlg.cpp       # wxPropertySheetDialog generator
    src/generate/gen_wizard.cpp              # wxWizard generator

    src/generate/gen_frame_common.cpp        # wxDocParent common generator functions

    # Menus
    src/generate/menu_widgets.cpp            # MenuBar, MenuBarForm, PopupMenu, Separator
    src/generate/gen_ctx_menu.cpp            # CtxMenuGenerator -- generates function and includes
    src/generate/gen_menu.cpp                # Menu Generator
    src/generate/gen_menuitem.cpp            # Menu Item Generator
    src/generate/gen_submenu.cpp             # SubMenu Generator

    # Pickers
    src/generate/gen_clr_picker.cpp          # wxColourPickerCtrl generator
    src/generate/gen_date_picker.cpp         # wxDatePickerCtrl generator
    src/generate/gen_dir_picker.cpp          # wxDirPickerCtrl generator
    src/generate/gen_file_picker.cpp         # wxFilePickerCtrl generator
    src/generate/gen_font_picker.cpp         # wxFontPickerCtrl generator
    src/generate/gen_time_picker.cpp         # wxTimePickerCtrl generator

    # PropertyGrid
    src/generate/gen_prop_category.cpp       # PropertyGridCategory (propGridItem) generator
    src/generate/gen_prop_grid.cpp           # wxPropertyGrid generator
    src/generate/gen_prop_grid_mgr.cpp       # wxPropertyGridManager and wxPropertyGridPage generators
    src/generate/gen_prop_item.cpp           # PropertyGridItem (propGridItem) generator

    # Sizers
    src/generate/gen_box_sizer.cpp           # wxBoxSizer generator
    src/generate/gen_flexgrid_sizer.cpp      # wxFlexGridSizer generator
    src/generate/gen_grid_sizer.cpp          # wxGridSizer generator
    src/generate/gen_gridbag_sizer.cpp       # wxGridBagSizer generator
    src/generate/gen_spacer_sizer.cpp        # Add space to sizer generator
    src/generate/gen_statchkbox_sizer.cpp    # wxStaticBoxSizer with wxCheckBox generator
    src/generate/gen_staticbox_sizer.cpp     # wxStaticBoxSizer generator
    src/generate/gen_statradiobox_sizer.cpp  # wxStaticBoxSizer with wxRadioButton generator
    src/generate/gen_std_dlgbtn_sizer.cpp    # wxStdDialogButtonSizer generator
    src/generate/gen_text_sizer.cpp          # wxTextSizerWrapper generator
    src/generate/gen_wrap_sizer.cpp          # wxWrapSizer generator

    # Toolbars
    src/generate/gen_aui_toolbar.cpp         # wxAuiToolBar generator
    src/generate/gen_ribbon_bar.cpp          # wxRibbonButtonBar generator
    src/generate/gen_ribbon_button.cpp       # wxRibbonBar -- form and regular
    src/generate/gen_ribbon_gallery.cpp      # wxRibbonGallery generator
    src/generate/gen_ribbon_page.cpp         # wxRibbonPage and wxRibbonPanel generators
    src/generate/gen_ribbon_tool.cpp         # wxRibbonToolBar generator
    src/generate/gen_toolbar.cpp             # wxToolBar generator
    src/generate/gen_tools.cpp               # Generate tools for wxToolBar

    # ############################ Importers ##############################

    # Importers (also see Windows Resource importer below)
    src/import/import_dialogblocks.cpp    # Import a DialogBlocks project
    src/import/import_formblder.cpp       # Import a wxFormBuilder project
    src/import/import_wxcrafter.cpp       # Import a wxCrafter project
    src/import/import_wxglade.cpp         # Import a wxGlade file
    src/import/import_wxsmith.cpp         # Process XRC files
    src/import/import_xml.cpp             # Base class for XML importing

    # (generated) import/import_winres_dlg.cpp

    # ############################ Mockup Panel ##############################
    src/mockup/mockup_content.cpp      # Mockup of a form's contents
    src/mockup/mockup_parent.cpp       # Top-level MockUp Parent window
    src/mockup/mockup_preview.cpp      # Preview Mockup
    src/mockup/mockup_wizard.cpp       # Emulate a wxWizard

    # ############################ New Form Dialogs ##############################
    # Dialogs for creating new forms
    src/newdialogs/new_common.cpp                # Contains code common between all new_ dialogs

    # (generated) newdialogs/new_dialog.cpp     # Dialog for creating a new project dialog
    # (generated) newdialogs/new_frame.cpp      # Dialog for creating a new project wxFrame
    # (generated) newdialogs/new_panel.cpp      # Dialog for creating a new form panel
    # (generated) newdialogs/new_propsheet.cpp  # Dialog for creating a new wxPropertySheetDialog
    # (generated) newdialogs/new_ribbon.cpp     # Dialog for creating a new wxRibbonBar
    # (generated) newdialogs/new_wizard.cpp     # Dialog for creating a new wxWizard
    # (generated) newdialogs/new_dialog.cpp     # Dialog for creating a new project dialog

    # ############################ Nodes ##############################
    src/nodes/node.cpp                   # Contains user-modifiable node
    src/nodes/node_constants.cpp         # Maps wxWidgets constants to their numerical value
    src/nodes/node_creator.cpp           # Class used to create nodes
    src/nodes/node_decl.cpp              # Contains the declarations for a node (properties, events, etc.)
    src/nodes/node_gridbag.cpp           # Create and modify a node containing a wxGridBagSizer
    src/nodes/node_init.cpp              # Initialize NodeCreator class
    src/nodes/node_prop.cpp              # NodeProperty class
    src/nodes/tool_creator.cpp           # Functions for creating new nodes from Ribbon Panel

    # ############################ Panels ##############################
    src/panels/base_panel.cpp         # Code generation panel
    src/panels/code_display.cpp       # Display code in scintilla control

    # internal/import_panel.cpp  # Internal-only panel to display original Import file
    src/panels/nav_panel.cpp           # Navigation panel
    src/panels/navpopupmenu.cpp        # Context-menu for Navigation panel
    src/panels/propgrid_create.cpp     # PropGridPanel Create functions
    src/panels/propgrid_events.cpp     # PropGridPanel event handlers
    src/panels/propgrid_modify.cpp     # PropGridPanel modification functions
    src/panels/propgrid_panel.cpp      # Property panel
    src/panels/cstm_propgrid.cpp       # Derived wxPropertyGrid class
    src/panels/ribbon_tools.cpp        # Displays node creation tools in a wxRibbonBar

    # (generated) panels/doc_view.cpp         # Panel for displaying docs in wxWebView
    # (generated) panels/nav_toolbar.cpp

    # Project classes
    src/project/data_handler.cpp           # DataHandler class
    src/project/embed_image.cpp            # class to manage images stored in the generated code
    src/project/image_handler.cpp          # ProjectImage class
    src/project/loadproject.cpp            # Load wxUiEditor project
    src/project/project_handler.cpp        # ProjectHandler class
    src/project/saveproject.cpp            # Save a wxUiEditor project file

    src/utils/dlg_msgs.cpp                 # wxMessageDialog dialogs
    src/utils/font_prop.cpp                # FontProperty class
    src/utils/set_stc_colors.cpp           # Contains function for initializing wxStyledTextCtrl colors
    src/utils/utils.cpp                    # Utility functions that work with properties

    # Testing
    src/internal/node_info.cpp             # Node memory usage dialog
    src/internal/msgframe.cpp              # Stores messages
    src/internal/msg_logging.cpp           # Message logging class
    src/internal/import_panel.cpp          # Panel to display original imported file
    src/tests/test_xrc_import.cpp          # XRC Import tests

    src/internal/xrcpreview.cpp            # Generated XrcPreview Dialog code
    src/internal/xrcpreview_handlers.cpp   # Handlers for XrcPreview Dialog class
    src/internal/xrc_list_dlg.cpp

    # Tools

    src/tools/compare/code_compare.cpp  # Code Generation Comparison
    src/tools/compare/diff.cpp          # Simple diff algorithm for comparing text files
    src/tools/compare/diff_viewer.cpp   # Dialog for displaying file differences
    src/tools/generate_dlg.cpp         # Dialog for choosing and generating specific language file(s)

    # tools/generate_dlg.cpp        # Dialog for choosing and generating specific language file(s)
    # tools/preview_settings.cpp    # Dialog for setting preview options
    # (generated) tools/global_ids_dlg.cpp  # Dialog to Globally edit Custom IDs

    # UI

    # (generated) ui/code_preference_dlg.cpp
    # (generated) ui/startup_dlg.cpp
    # (generated) ui/generate_xrc_dlg.cpp  # Dialog for generating XRC file(s)

    # Windows resource importer
    src/winres/ctrl_utils.cpp           # resCtrl class utility functions
    src/winres/form_utils.cpp           # resForm utility functions code
    src/winres/import_winres.cpp        # Import a Windows resource file
    src/winres/winres_ctrl.cpp          # Process Windows Resource control data
    src/winres/winres_dlg.cpp           # Process a Windows Resource DIALOG or DIALOGEX
    src/winres/winres_menu.cpp          # Process a Windows Resource MENU
    src/winres/winres_images.cpp        # resCtrl class image/icon functions
    src/winres/winres_layout.cpp        # resForm layout code
    src/winres/winres_styles.cpp        # resCtrl class style processing functions

    src/pugixml/pugixml.cpp             # XML parser

    src/ui/generate_xrc_dlg.cpp         # Dialog for generating XRC file(s)
    src/ui/gridbag_item.cpp             # Dialog for inserting an item into a wxGridBagSizer node
    src/ui/import_dlg.cpp               # Dialog to import one or more projects
    src/ui/xrccompare.cpp               # C++/XRC UI Comparison dialog
    src/ui/viewdetails_dlg.cpp          # Dialog to display details about a node in the Mockup

    src/helptext/archive_handler.cpp                # Handles doc archive: open, search, display
    src/helptext/find_in_page.cpp    # Find-in-page utilities for DocViewPane
    src/helptext/doc_view_panel.cpp                 # Reusable doc viewer panel (wxHtmlWindow + index tabs)
    src/helptext/doc_view_frame.cpp  # wxFrame host for DocViewPane (menu bar, status bar)

    # (generated) ui/preferences_dlg.cpp  # Preferences dialog
    $<$<CONFIG:Debug>:src/internal/convert_img.cpp> # Convert image
    $<$<CONFIG:Debug>:src/tests/test_xrc_import.cpp> # XRC Import tests
)
set(parser_sources
    src/doc_viweer/zip_reader.cpp
)

set( debug_files

    # These are just here to make it easier to open with a VSCode extension
    src/internal/convert_img.cpp

    src/internal/convert_img_base.cpp
    src/internal/debugsettings.cpp
    src/internal/msgframe_base.cpp
    src/internal/node_search_dlg.cpp
    src/internal/undo_info.cpp
    src/internal/unused_gen_dlg.cpp

    src/tools/generate_dlg.cpp
    src/tools/preview_settings.cpp

    src/wxui/optionsdlg.cpp
    src/wxui/code_preference_dlg.cpp
    src/wxui/dlg_gen_results.cpp
)

# ============================================================================
# build_resources files
# ============================================================================

set (bldres_files
    tools/build_resources/CMakeLists.txt
    tools/build_resources/main.cpp
)

# ============================================================================
# Other files (not necessarily built into wxUiEditor
# ============================================================================

set( xml_list

    # interface declarations
    src/xml/interfaces.xml

    # generator declarations
    src/xml/bars.xml
    src/xml/boxes.xml
    src/xml/buttons.xml
    src/xml/containers.xml
    src/xml/data_ctrls.xml
    src/xml/forms.xml
    src/xml/mdi.xml
    src/xml/pickers.xml
    src/xml/project.xml
    src/xml/sizers.xml
    src/xml/text_ctrls.xml
    src/xml/widgets.xml
)

set( workflow_list
    .github/workflows/build-ubuntu-setup.yml
    .github/workflows/build-win-setup.yml
    .github/workflows/check_build.yml
    .github/workflows/cleanup-workflows.yml
    .github/workflows/codeql-analysis.yml
    .github/workflows/daily_build.yml
    .github/workflows/test_clang_format.yml
)

# ============================================================================
# Documentation Files Reference
# ============================================================================
# All paths are relative to src/ (location of this file_list.cmake)
#
# Project Root Documentation:
#   CHANGELOG.md                           - Version history and release notes
#   README.md                              - Project overview and quick start
#   LICENSE                                - Software license
#   pull_request_template.md              - GitHub PR template
#   .github/copilot-instructions.md       - AI coding guidelines and project standards
#
# Code Generator Support:
#   src/generate/SUPPORTED.md                     - Language support matrix for all widget classes
#
# User Documentation (../docs/):
#   docs/README.md                         - Documentation index
#   docs/users/README.md                   - User guide index
#   docs/users/images.md                   - Image and bitmap handling guide
#   docs/users/import_crafter.md           - wxCrafter import instructions
#   docs/users/import_dialogblocks.md      - DialogBlocks import instructions
#   docs/users/import_formbuilder.md       - wxFormBuilder import instructions
#   docs/users/import_winres.md            - Windows resource (.rc) import guide
#   docs/users/wxui_file_format.md         - .wxui XML format specification
#   docs/users/XRC.md                      - XRC export and usage guide
#
# Contributor Documentation (../docs/contributors/):
#   docs/contributors/README.md            - Contributor guide index
#   docs/contributors/ai-context-template.md - Template for AI context documentation
#   docs/contributors/architecture.md      - High-level architecture documentation
#   docs/contributors/build_notes.md       - Build system and compilation guide
#   docs/contributors/contributor_notes.md - Development workflow and contribution guidelines
#   docs/contributors/generators.md        - Code generator architecture and implementation
#   docs/contributors/internal_testing.md  - Internal testing tools and debug features
#   docs/contributors/node_classes.md      - Node class system documentation
#   docs/contributors/release_prep.md      - Release preparation checklist
#   docs/contributors/test_coverage.md     - Test coverage and testing strategy
#   docs/contributors/windows_res.md       - Windows resource importer implementation
#   docs/contributors/xml_definitions.md   - XML generator definition system guide
#   docs/contributors/xml_interface.md     - XML interface and property system
# ============================================================================
