///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/button.h>
#include <wx/choice.h>
#include <wx/dialog.h>
#include <wx/gdicmn.h>
#include <wx/stattext.h>

class DlgIssue_956 : public wxDialog
{
public:
    DlgIssue_956() {}
    DlgIssue_956(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "colspan codegen issue",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "colspan codegen issue",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE, const wxString &name = wxDialogNameStr);

protected:

    // Class member variables

    wxButton* m_btn;
    wxButton* m_btn_2;
    wxButton* m_btn_3;
    wxButton* m_btn_4;
    wxChoice* m_choice;
    wxChoice* m_choice_2;
    wxStaticText* m_staticText_4;
    wxStaticText* m_staticText_5;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
