///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/bannerwindow.h>
#include <wx/bitmap.h>
#include <wx/button.h>
#include <wx/checklst.h>
#include <wx/colour.h>
#include <wx/commandlinkbutton.h>
#include <wx/dialog.h>
#include <wx/editlbox.h>
#include <wx/event.h>
#include <wx/gdicmn.h>
#include <wx/icon.h>
#include <wx/image.h>
#include <wx/listbase.h>
#include <wx/listctrl.h>
#include <wx/notebook.h>
#include <wx/rearrangectrl.h>
#include <wx/settings.h>
#include <wx/stattext.h>
#include <wx/tglbtn.h>

class DlgMultiTest : public wxDialog
{
public:
    DlgMultiTest() {}
    DlgMultiTest(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Widgets Testing",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Widgets Testing",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr);

protected:

    // Event handlers

    void OnInit(wxInitDialogEvent& event);

    // Class member variables

    wxBannerWindow* m_banner;
    wxBannerWindow* m_banner_left;
    wxBannerWindow* m_banner_right;
    wxBannerWindow* m_banner_top;
    wxButton* m_btn;
    wxButton* m_btn_2;
    wxButton* m_btn_4;
    wxButton* m_btn_bitmaps;
    wxCheckListBox* m_checkList;
    wxCommandLinkButton* m_btn_5;
    wxEditableListBox* m_edit_listbox;
    wxListView* m_listview;
    wxNotebook* m_notebook;
    wxRearrangeCtrl* m_rearrange;
    wxStaticText* m_staticText;
    wxStaticText* m_staticText_2;
    wxStaticText* m_staticText_3;
    wxStaticText* m_staticText_5;
    wxToggleButton* m_toggleBtn;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
