///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/filepicker.h>
#include <wx/gdicmn.h>
#include <wx/listbox.h>
#include <wx/radiobut.h>
#include <wx/sizer.h>
#include <wx/statbox.h>

class GenerateXrcDlg : public wxDialog
{
public:
    GenerateXrcDlg() {}
    GenerateXrcDlg(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Generate XRC File(s)",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Generate XRC File(s)",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr);

protected:

    // Event handlers

    void OnCombinedFile(wxCommandEvent& event);
    void OnCombinedFilenameChanged(wxFileDirPickerEvent& event);
    void OnInit(wxInitDialogEvent& event);
    void OnSave(wxCommandEvent& event);
    void OnSeparateFiles(wxCommandEvent& event);

private:

    // Validator variables

    bool m_create_combined { true };

    // Class member variables

    wxFilePickerCtrl* m_filePicker;
    wxListBox* m_listbox;
    wxRadioButton* m_radio_combined;
    wxStaticBoxSizer* m_combined_box;
    wxRadioButton* m_radio_separate;
    wxStaticBoxSizer* m_separate_box;

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************

public:

    tt_string GetCombinedFilename() { return m_filename.utf8_string(); }
    bool CombineFiles() { return m_create_combined; }

private:
    wxString m_filename;
};
