////////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////////

#include "pch.h"

#include <wx/sizer.h>

#include "importwinres_base.h"

ImportWinResBase::ImportWinResBase(wxWindow* parent, wxWindowID id, const wxString& title,
		const wxPoint& pos, const wxSize& size, long style) :
	wxDialog(parent, id, title, pos, size, style)
{
    auto parent_sizer = new wxBoxSizer(wxVERTICAL);

    auto box_sizer4 = new wxBoxSizer(wxVERTICAL);
    parent_sizer->Add(box_sizer4, wxSizerFlags(1).Expand().Border(wxALL));

    m_staticResFile = new wxStaticText(this, wxID_ANY, wxString::FromUTF8("&Resource File:"));
    box_sizer4->Add(m_staticResFile, wxSizerFlags().Border(wxLEFT|wxRIGHT|wxTOP, wxSizerFlags::GetDefaultBorder()));

    m_fileResource = new wxFilePickerCtrl(this, wxID_ANY, wxEmptyString, wxFileSelectorPromptStr, 
    wxString::FromUTF8("Resource Files|*.rc;*.dlg||"), wxDefaultPosition, wxDefaultSize,
    wxFLP_FILE_MUST_EXIST|wxFLP_OPEN|wxFLP_USE_TEXTCTRL);
    m_fileResource->SetMinSize(wxSize(240, -1));
    box_sizer4->Add(m_fileResource, wxSizerFlags().Expand().Border(wxALL));

    auto box_sizer5 = new wxBoxSizer(wxVERTICAL);
    parent_sizer->Add(box_sizer5, wxSizerFlags().Expand().Border(wxALL));

    m_staticText = new wxStaticText(this, wxID_ANY, wxString::FromUTF8("&Dialogs to Import"));
    box_sizer5->Add(m_staticText, wxSizerFlags().Border(wxLEFT|wxRIGHT|wxTOP, wxSizerFlags::GetDefaultBorder()));

    m_checkListResUI = new wxCheckListBox(this, wxID_ANY);
    m_checkListResUI->SetMinSize(wxSize(-1, 160));
    m_checkListResUI->SetToolTip(wxString::FromUTF8("Uncheck any resources you don't want converted."));
    box_sizer5->Add(m_checkListResUI, wxSizerFlags().Expand().Border(wxALL));

    auto box_sizer = new wxBoxSizer(wxHORIZONTAL);
    box_sizer5->Add(box_sizer, wxSizerFlags().Expand().Border(wxALL));

    m_btnSelectAll = new wxButton(this, wxID_ANY, wxString::FromUTF8("Select &All"));
    box_sizer->Add(m_btnSelectAll, wxSizerFlags().Border(wxALL));

    m_btnClearAll = new wxButton(this, wxID_ANY, wxString::FromUTF8("&Clear All"));
    box_sizer->Add(m_btnClearAll, wxSizerFlags().Border(wxALL));

    auto stdBtn = CreateStdDialogButtonSizer(wxOK|wxCANCEL);
    parent_sizer->Add(CreateSeparatedSizer(stdBtn), wxSizerFlags().Expand().Border(wxALL));

    SetSizerAndFit(parent_sizer);

    Centre(wxBOTH);

    // Event handlers
    Bind(wxEVT_INIT_DIALOG, &ImportWinResBase::OnInit, this);
    m_fileResource->Bind(wxEVT_FILEPICKER_CHANGED, &ImportWinResBase::OnResourceFile, this);
    m_btnSelectAll->Bind(wxEVT_BUTTON, &ImportWinResBase::OnSelectAll, this);
    m_btnClearAll->Bind(wxEVT_BUTTON, &ImportWinResBase::OnClearAll, this);
    Bind(wxEVT_BUTTON, &ImportWinResBase::OnOk, this, wxID_OK);
}
