////////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////////

#include "pch.h"

#include <wx/stattext.h>

#include "insertdialog_base.h"

bool InsertDialogBase::Create(wxWindow *parent, wxWindowID id, const wxString &title,
        const wxPoint&pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;

    auto box_sizer = new wxBoxSizer(wxVERTICAL);
    box_sizer->SetMinSize(300, 400);

    auto box_sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    box_sizer->Add(box_sizer_2, wxSizerFlags().Expand().Border(wxALL));

    auto staticText = new wxStaticText(this, wxID_ANY, wxString::FromUTF8("&Name:"));
    box_sizer_2->Add(staticText, wxSizerFlags().Center().Border(wxALL));

    m_text_name = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    box_sizer_2->Add(m_text_name, wxSizerFlags(1).Border(wxALL));

    auto box_sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    box_sizer->Add(box_sizer_3, wxSizerFlags(1).Expand().Border(wxALL));

    m_listBox = new wxListBox(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 300), 0, nullptr, wxLB_SINGLE|wxLB_SORT);
    box_sizer_3->Add(m_listBox, wxSizerFlags(1).Expand().Border(wxALL));

    m_stdBtn = CreateStdDialogButtonSizer(wxOK|wxCANCEL);
    box_sizer->Add(CreateSeparatedSizer(m_stdBtn), wxSizerFlags().Expand().Border(wxALL));

    SetSizerAndFit(box_sizer);
    Centre(wxBOTH);

    // Event handlers
    Bind(wxEVT_INIT_DIALOG, &InsertDialogBase::OnInit, this);
    m_text_name->Bind(wxEVT_TEXT, &InsertDialogBase::OnNameText, this);
    m_listBox->Bind(wxEVT_LISTBOX,
        [this](wxCommandEvent&) { m_stdBtn->GetAffirmativeButton()->Enable(); }
        );
    m_listBox->Bind(wxEVT_LISTBOX_DCLICK, &InsertDialogBase::OnListBoxDblClick, this);
    Bind(wxEVT_BUTTON, &InsertDialogBase::OnOK, this, wxID_OK);

    return true;
}
