///////////////////////////////////////////////////////////////////////////////
// <auto-generated>
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT ANYTHING IN THIS FILE UNTIL AFTER THE </auto-generated> MARKER
// All changes before that marker will be lost if the code is re-generated.
///////////////////////////////////////////////////////////////////////////////

// clang-format off
// NOLINTBEGIN
// cppcheck-suppress-begin *

#include <wx/bitmap.h>
#include <wx/button.h>
#include <wx/icon.h>
#include <wx/image.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/valgen.h>
#include <wx/valtext.h>

#include "../wxui/ui_images.h"

#include "preferences_dlg.h"

#include <wx/bmpbndl.h>  // wxBitmapBundle class
#include <wx/mstream.h>  // memory stream classes
#include <wx/zstream.h>  // zlib stream classes

#include <memory>  // for std::make_unique

// Convert compressed SVG string into a wxBitmapBundle
#ifdef __cpp_inline_variables
inline wxBitmapBundle wxueBundleSVG(const unsigned char* data,
    size_t size_data, size_t size_svg, wxSize def_size)
#else
static wxBitmapBundle wxueBundleSVG(const unsigned char* data,
    size_t size_data, size_t size_svg, wxSize def_size)
#endif
{
    auto str = std::make_unique<char[]>(size_svg);
    wxMemoryInputStream stream_in(data, size_data);
    wxZlibInputStream zlib_strm(stream_in);
    zlib_strm.Read(str.get(), size_svg);
    return wxBitmapBundle::FromSVG(str.get(), def_size);
};

namespace wxue_img
{
    extern const unsigned char julia_logo_svg[167];  // ../art_src/julia_logo.svg
}

bool PreferencesDlg::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    // Scaling of pos and size are handled after the dialog
    // has been created and controls added.
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
    {
        return false;
    }

    auto* dlg_sizer = new wxBoxSizer(wxVERTICAL);
    dlg_sizer->SetMinSize(900, -1);

    auto* notebook = new wxNotebook(this, wxID_ANY);
    {
        wxWithImages::Images bundle_list;
        bundle_list.push_back(wxue_img::bundle_cpp_logo_svg(24, 24));
        bundle_list.push_back(wxue_img::bundle_python_logo_only_svg(24, 24));
        bundle_list.push_back(wxue_img::bundle_ruby_logo_svg(24, 24));
        bundle_list.push_back(wxue_img::bundle_fortran_logo_svg(24, 24));
        bundle_list.push_back(wxue_img::bundle_Go_Logo_Blue_svg(24, 24));
        bundle_list.push_back(wxueBundleSVG(wxue_img::julia_logo_svg, 167, 267, wxSize(24, 24)));
        bundle_list.push_back(wxue_img::bundle_lua_logo_svg(24, 24));
        bundle_list.push_back(wxue_img::bundle_ts_logo_round_128_svg(24, 24));
        bundle_list.push_back(wxue_img::bundle_wxlogo_svg(24, 24));
        notebook->SetImages(bundle_list);
    }
    dlg_sizer->Add(notebook, wxSizerFlags(1).Expand().Border(wxALL));

    auto* page_general = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_general, "General", true);

    m_general_page_sizer = new wxBoxSizer(wxVERTICAL);

    m_box_dark_settings = new wxBoxSizer(wxHORIZONTAL);

    m_check_dark_mode = new wxCheckBox(page_general, wxID_ANY, "Dark Mode");
    m_check_dark_mode->SetToolTip("Requires closing and restarting wxUiEditor");
    m_box_dark_settings->Add(m_check_dark_mode, wxSizerFlags().Border(wxALL));

#if defined(__WINDOWS__)

    m_check_high_contrast = new wxCheckBox(page_general, wxID_ANY, "High Contrast");
    m_check_high_contrast->SetToolTip("Only used if Dark Mode is selected");
    m_box_dark_settings->Add(m_check_high_contrast, wxSizerFlags().Border(wxALL));
#endif  // limited to specific platforms
    m_box_dark_settings->ShowItems(false);
    m_general_page_sizer->Add(m_box_dark_settings,
    wxSizerFlags().Expand().Border(wxRIGHT|wxTOP|wxBOTTOM, wxSizerFlags::GetDefaultBorder()));

    auto* box_sizer2 = new wxBoxSizer(wxHORIZONTAL);

    auto* box_sizer3 = new wxBoxSizer(wxVERTICAL);

    m_check_load_last = new wxCheckBox(page_general, wxID_ANY, "Always load last project");
    box_sizer3->Add(m_check_load_last, wxSizerFlags(1).Border(wxALL));

    m_check_fullpath = new wxCheckBox(page_general, wxID_ANY, "Full project path in title bar");
    m_check_fullpath->SetValue(true);
    box_sizer3->Add(m_check_fullpath, wxSizerFlags(1).Border(wxALL));

    auto* checkBox_wakatime = new wxCheckBox(page_general, wxID_ANY, "Enable WakaTime");
    checkBox_wakatime->SetValue(true);
    checkBox_wakatime->SetValidator(wxGenericValidator(&m_isWakaTimeEnabled));
    checkBox_wakatime->SetToolTip(
    "If you have WakaTime installed, checking this will record time spent in the editor as \"designing\". (See https://wakatime.com/about)");
    box_sizer3->Add(checkBox_wakatime, wxSizerFlags().Border(wxALL));

    m_check_svg_bitmaps = new wxCheckBox(page_general, wxID_ANY, "Default SVG bitmaps");
    m_check_svg_bitmaps->SetToolTip("If checked, new bitmaps will default to SVG files");
    box_sizer3->Add(m_check_svg_bitmaps, wxSizerFlags().Border(wxALL));

    m_check_right_propgrid = new wxCheckBox(page_general, wxID_ANY, "Property Panel on Right");
    m_check_right_propgrid->SetToolTip("If checked, the Property panel will be moved to the right side");
    box_sizer3->Add(m_check_right_propgrid, wxSizerFlags(1).Border(wxALL));

    box_sizer2->Add(box_sizer3, wxSizerFlags().Border(wxALL));

    auto* box_sizer4 = new wxBoxSizer(wxVERTICAL);

    box_sizer2->Add(box_sizer4, wxSizerFlags().Border(wxALL));

    auto* box_sizer8 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_text4 = new wxStaticText(page_general, wxID_ANY, "Tree &Icon Size:");
    static_text4->SetToolTip("The size of the icons used in toolbars and tree controls");
    box_sizer8->Add(static_text4, wxSizerFlags().Center().Border(wxALL));

    m_choice_icon_size = new wxChoice(page_general, wxID_ANY);
    m_choice_icon_size->Append("16");
    m_choice_icon_size->Append("18");
    m_choice_icon_size->Append("20");
    m_choice_icon_size->Append("22");
    m_choice_icon_size->Append("24");
    m_choice_icon_size->Append("26");
    m_choice_icon_size->Append("28");
    m_choice_icon_size->Append("30");
    m_choice_icon_size->Append("32");
    m_choice_icon_size->SetStringSelection("18");
    box_sizer8->Add(m_choice_icon_size, wxSizerFlags().Border(wxALL));

    box_sizer2->Add(box_sizer8, wxSizerFlags().Border(wxALL));

    m_box_code_font = new wxBoxSizer(wxHORIZONTAL);

    m_btn_font = new wxCommandLinkButton(page_general, wxID_ANY, "Font", "Font for code panels");
    m_box_code_font->Add(m_btn_font, wxSizerFlags().Border(wxLEFT|wxRIGHT|wxBOTTOM, wxSizerFlags::GetDefaultBorder()));

    box_sizer2->Add(m_box_code_font,
    wxSizerFlags().Expand().Border(wxLEFT|wxRIGHT|wxBOTTOM, wxSizerFlags::GetDefaultBorder()));

    m_general_page_sizer->Add(box_sizer2, wxSizerFlags().Expand().Border(wxALL));
    page_general->SetSizerAndFit(m_general_page_sizer);

    auto* page_cpp = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_cpp, "C++", false, 0);

    auto* page_sizer_2 = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer = new wxBoxSizer(wxHORIZONTAL);

    auto* staticText_3 = new wxStaticText(page_cpp, wxID_ANY, "&Line Length");
    staticText_3->Wrap(200);
    box_sizer->Add(staticText_3, wxSizerFlags().Center().Border(wxALL));

    auto* text_cpp_line_length = new wxTextCtrl(page_cpp, wxID_ANY, "110");
    text_cpp_line_length->SetValidator(wxTextValidator(wxFILTER_DIGITS, &m_cpp_line_length));
    text_cpp_line_length->SetToolTip(
    "Most generated code will not exceed this length. This will be the initial value when a new project is created.");
    box_sizer->Add(text_cpp_line_length, wxSizerFlags().Border(wxALL));

    page_sizer_2->Add(box_sizer, wxSizerFlags().Border(wxALL));

    m_check_cpp_snake_case = new wxCheckBox(page_cpp, wxID_ANY, "Default variables should use snake_case");
    m_check_cpp_snake_case->SetToolTip(
    "By default, default variables use camelCase. Check this to use snake_case instead (e.g., foo_bar instead of fooBar)");
    page_sizer_2->Add(m_check_cpp_snake_case, wxSizerFlags().Border(wxALL));

    auto* box_sizer_5 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_text = new wxStaticText(page_cpp, wxID_ANY, "wxWidgets version");
    box_sizer_5->Add(static_text, wxSizerFlags().Center().Border(wxALL));

    m_choice_cpp_version = new wxChoice(page_cpp, wxID_ANY);
    m_choice_cpp_version->Append("3.2.0");
    m_choice_cpp_version->Append("3.3.0");
    m_choice_cpp_version->Append("3.4.0");
    m_choice_cpp_version->Append("3.5.0");
    m_choice_cpp_version->SetStringSelection("3.2");
    m_choice_cpp_version->SetToolTip("Code requiring a newer version then this will be placed in a conditional block.");
    box_sizer_5->Add(m_choice_cpp_version, wxSizerFlags().Border(wxALL));

    page_sizer_2->Add(box_sizer_5, wxSizerFlags().Border(wxALL));

    auto* grid_sizer3 = new wxGridSizer(2, 0, 0);

    auto* staticText_7 = new wxStaticText(page_cpp, wxID_ANY, "wxWidgets &keyword color:");
    grid_sizer3->Add(staticText_7, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_cpp = new wxColourPickerCtrl(page_cpp, wxID_ANY, wxColour("#C76605"));
    grid_sizer3->Add(m_colour_cpp, wxSizerFlags().Border(wxALL));

    auto* staticText9 = new wxStaticText(page_cpp, wxID_ANY, "&C++ keyword color:");
    grid_sizer3->Add(staticText9, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_cpp_keyword = new wxColourPickerCtrl(page_cpp, wxID_ANY, wxColour("#0000FF"));
    grid_sizer3->Add(m_colour_cpp_keyword, wxSizerFlags().Border(wxALL));

    auto* staticText10 = new wxStaticText(page_cpp, wxID_ANY, "&Comment color:");
    grid_sizer3->Add(staticText10, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_cpp_comment = new wxColourPickerCtrl(page_cpp, wxID_ANY, wxColour("#008000"));
    grid_sizer3->Add(m_colour_cpp_comment, wxSizerFlags().Border(wxALL));

    auto* staticText11 = new wxStaticText(page_cpp, wxID_ANY, "&Number color:");
    grid_sizer3->Add(staticText11, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_cpp_number = new wxColourPickerCtrl(page_cpp, wxID_ANY, wxColour("#FF0000"));
    grid_sizer3->Add(m_colour_cpp_number, wxSizerFlags().Border(wxALL));

    auto* staticText12 = new wxStaticText(page_cpp, wxID_ANY, "&String color:");
    grid_sizer3->Add(staticText12, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_cpp_string = new wxColourPickerCtrl(page_cpp, wxID_ANY, wxColour("#008000"));
    grid_sizer3->Add(m_colour_cpp_string, wxSizerFlags().Border(wxALL));

    page_sizer_2->Add(grid_sizer3, wxSizerFlags().Border(wxALL));
    page_cpp->SetSizerAndFit(page_sizer_2);

    auto* page_python = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_python, "Python", false, 1);

    auto* page_sizer_3 = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer_3 = new wxBoxSizer(wxHORIZONTAL);

    auto* staticText_4 = new wxStaticText(page_python, wxID_ANY, "&Line Length");
    staticText_4->Wrap(200);
    box_sizer_3->Add(staticText_4, wxSizerFlags().Center().Border(wxALL));

    auto* text_python_line_length = new wxTextCtrl(page_python, wxID_ANY, "90");
    text_python_line_length->SetValidator(wxTextValidator(wxFILTER_DIGITS, &m_python_line_length));
    text_python_line_length->SetToolTip(
    "Most generated code will not exceed this length. This will be the initial value when a new project is created.");
    box_sizer_3->Add(text_python_line_length, wxSizerFlags().Border(wxALL));

    page_sizer_3->Add(box_sizer_3, wxSizerFlags().Border(wxALL));

    auto* box_sizer7 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_text3 = new wxStaticText(page_python, wxID_ANY, "wxPython version");
    box_sizer7->Add(static_text3, wxSizerFlags().Center().Border(wxALL));

    m_choice_python_version = new wxChoice(page_python, wxID_ANY);
    m_choice_python_version->Append("4.2.0");
    m_choice_python_version->SetStringSelection("4.2.0");
    m_choice_python_version->SetToolTip("Code requiring a newer version then this will be placed in a conditional block.");
    box_sizer7->Add(m_choice_python_version, wxSizerFlags().Border(wxALL));

    page_sizer_3->Add(box_sizer7, wxSizerFlags().Border(wxALL));

    auto* grid_sizer2 = new wxGridSizer(2, 0, 0);

    auto* staticText = new wxStaticText(page_python, wxID_ANY, "&wxWidgets keyword color:");
    grid_sizer2->Add(staticText, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_python = new wxColourPickerCtrl(page_python, wxID_ANY, wxColour("#FF00FF"));
    grid_sizer2->Add(m_colour_python, wxSizerFlags().Border(wxALL));

    auto* staticText5 = new wxStaticText(page_python, wxID_ANY, "&wxWidgets keyword color:");
    grid_sizer2->Add(staticText5, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_python_keyword = new wxColourPickerCtrl(page_python, wxID_ANY, wxColour("#0000FF"));
    grid_sizer2->Add(m_colour_python_keyword, wxSizerFlags().Border(wxALL));

    auto* staticText6 = new wxStaticText(page_python, wxID_ANY, "&Comment color:");
    grid_sizer2->Add(staticText6, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_python_comment = new wxColourPickerCtrl(page_python, wxID_ANY, wxColour("#008000"));
    grid_sizer2->Add(m_colour_python_comment, wxSizerFlags().Border(wxALL));

    auto* staticText7 = new wxStaticText(page_python, wxID_ANY, "&Number color:");
    grid_sizer2->Add(staticText7, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_python_number = new wxColourPickerCtrl(page_python, wxID_ANY, wxColour("#FF0000"));
    grid_sizer2->Add(m_colour_python_number, wxSizerFlags().Border(wxALL));

    auto* staticText8 = new wxStaticText(page_python, wxID_ANY, "&String color:");
    grid_sizer2->Add(staticText8, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_python_string = new wxColourPickerCtrl(page_python, wxID_ANY, wxColour("#008000"));
    grid_sizer2->Add(m_colour_python_string, wxSizerFlags().Border(wxALL));

    page_sizer_3->Add(grid_sizer2, wxSizerFlags().Border(wxALL));
    page_python->SetSizerAndFit(page_sizer_3);

    auto* page_ruby = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_ruby, "Ruby", false, 2);

    auto* page_sizer_4 = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer_4 = new wxBoxSizer(wxHORIZONTAL);

    auto* staticText_5 = new wxStaticText(page_ruby, wxID_ANY, "&Line Length");
    staticText_5->Wrap(200);
    box_sizer_4->Add(staticText_5, wxSizerFlags().Center().Border(wxALL));

    auto* text_ruby_line_length = new wxTextCtrl(page_ruby, wxID_ANY, "80");
    text_ruby_line_length->SetValidator(wxTextValidator(wxFILTER_DIGITS, &m_ruby_line_length));
    text_ruby_line_length->SetToolTip(
    "Most generated code will not exceed this length. This will be the initial value when a new project is created.");
    box_sizer_4->Add(text_ruby_line_length, wxSizerFlags().Border(wxALL));

    page_sizer_4->Add(box_sizer_4, wxSizerFlags().Border(wxALL));

    auto* box_sizer6 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_text2 = new wxStaticText(page_ruby, wxID_ANY, "wxRuby version");
    box_sizer6->Add(static_text2, wxSizerFlags().Center().Border(wxALL));

    m_choice_ruby_version = new wxChoice(page_ruby, wxID_ANY);
    m_choice_ruby_version->Append("1.0.0");
    m_choice_ruby_version->Append("1.2.0");
    m_choice_ruby_version->Append("1.2.1");
    m_choice_ruby_version->SetStringSelection("1.2.1");
    m_choice_ruby_version->SetToolTip("Code requiring a newer version then this will be placed in a conditional block.");
    box_sizer6->Add(m_choice_ruby_version, wxSizerFlags().Border(wxALL));

    page_sizer_4->Add(box_sizer6, wxSizerFlags().Border(wxALL));

    auto* grid_sizer4 = new wxGridSizer(2, 0, 0);

    auto* staticText13 = new wxStaticText(page_ruby, wxID_ANY, "wxWidgets &keyword color:");
    grid_sizer4->Add(staticText13, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_ruby = new wxColourPickerCtrl(page_ruby, wxID_ANY, wxColour("#FF00FF"));
    grid_sizer4->Add(m_colour_ruby, wxSizerFlags().Border(wxALL));

    auto* staticText15 = new wxStaticText(page_ruby, wxID_ANY, "&Comment color:");
    grid_sizer4->Add(staticText15, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_ruby_comment = new wxColourPickerCtrl(page_ruby, wxID_ANY, wxColour("#008000"));
    grid_sizer4->Add(m_colour_ruby_comment, wxSizerFlags().Border(wxALL));

    auto* staticText16 = new wxStaticText(page_ruby, wxID_ANY, "&Number color:");
    grid_sizer4->Add(staticText16, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_ruby_number = new wxColourPickerCtrl(page_ruby, wxID_ANY, wxColour("#FF0000"));
    grid_sizer4->Add(m_colour_ruby_number, wxSizerFlags().Border(wxALL));

    auto* staticText17 = new wxStaticText(page_ruby, wxID_ANY, "&String color:");
    grid_sizer4->Add(staticText17, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_ruby_string = new wxColourPickerCtrl(page_ruby, wxID_ANY, wxColour("#008000"));
    grid_sizer4->Add(m_colour_ruby_string, wxSizerFlags().Border(wxALL));

    page_sizer_4->Add(grid_sizer4, wxSizerFlags().Border(wxALL));
    page_ruby->SetSizerAndFit(page_sizer_4);

    auto* page_fortran = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_fortran, "Fortran", false, 3);

    auto* page_sizer5_10 = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer13_10 = new wxBoxSizer(wxHORIZONTAL);

    auto* staticText27_10 = new wxStaticText(page_fortran, wxID_ANY, "&Line Length");
    staticText27_10->Wrap(200);
    box_sizer13_10->Add(staticText27_10, wxSizerFlags().Center().Border(wxALL));

    auto* text_fortran_line_length = new wxTextCtrl(page_fortran, wxID_ANY, "80");
    text_fortran_line_length->SetValidator(wxTextValidator(wxFILTER_DIGITS, &m_fortran_line_length));
    text_fortran_line_length->SetToolTip(
    "Most generated code will not exceed this length. This will be the initial value when a new project is created.");
    box_sizer13_10->Add(text_fortran_line_length, wxSizerFlags().Border(wxALL));

    page_sizer5_10->Add(box_sizer13_10, wxSizerFlags().Border(wxALL));

    auto* box_sizer14_10 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_text7_10 = new wxStaticText(page_fortran, wxID_ANY, "kwxFortran version");
    box_sizer14_10->Add(static_text7_10, wxSizerFlags().Center().Border(wxALL));

    m_choice_fortran_version = new wxChoice(page_fortran, wxID_ANY);
    m_choice_fortran_version->Append("0.9.0");
    m_choice_fortran_version->Append("1.0.0");
    m_choice_fortran_version->SetStringSelection("0.0.0");
    m_choice_fortran_version->SetToolTip("Code requiring a newer version then this will be placed in a conditional block.");
    box_sizer14_10->Add(m_choice_fortran_version, wxSizerFlags().Border(wxALL));

    page_sizer5_10->Add(box_sizer14_10, wxSizerFlags().Border(wxALL));

    auto* grid_sizer7_10 = new wxGridSizer(2, 0, 0);

    auto* staticText28_10 = new wxStaticText(page_fortran, wxID_ANY, "wxWidgets &keyword color:");
    grid_sizer7_10->Add(staticText28_10, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_fortran = new wxColourPickerCtrl(page_fortran, wxID_ANY, wxColour("#FF00FF"));
    grid_sizer7_10->Add(m_colour_fortran, wxSizerFlags().Border(wxALL));

    auto* staticText29_10 = new wxStaticText(page_fortran, wxID_ANY, "&Comment color:");
    grid_sizer7_10->Add(staticText29_10, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_fortran_comment = new wxColourPickerCtrl(page_fortran, wxID_ANY, wxColour("#008000"));
    grid_sizer7_10->Add(m_colour_fortran_comment, wxSizerFlags().Border(wxALL));

    auto* staticText30_10 = new wxStaticText(page_fortran, wxID_ANY, "&Number color:");
    grid_sizer7_10->Add(staticText30_10, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_fortran_number = new wxColourPickerCtrl(page_fortran, wxID_ANY, wxColour("#FF0000"));
    grid_sizer7_10->Add(m_colour_fortran_number, wxSizerFlags().Border(wxALL));

    auto* staticText31_10 = new wxStaticText(page_fortran, wxID_ANY, "&String color:");
    grid_sizer7_10->Add(staticText31_10, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_perl_string_10 = new wxColourPickerCtrl(page_fortran, wxID_ANY, wxColour("#008000"));
    grid_sizer7_10->Add(m_colour_perl_string_10, wxSizerFlags().Border(wxALL));

    page_sizer5_10->Add(grid_sizer7_10, wxSizerFlags().Border(wxALL));
    page_fortran->SetSizerAndFit(page_sizer5_10);

    auto* page_go = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_go, "GO", false, 4);

    auto* page_sizer5_11 = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer13_11 = new wxBoxSizer(wxHORIZONTAL);

    auto* staticText27_11 = new wxStaticText(page_go, wxID_ANY, "&Line Length");
    staticText27_11->Wrap(200);
    box_sizer13_11->Add(staticText27_11, wxSizerFlags().Center().Border(wxALL));

    auto* text_go_line_length = new wxTextCtrl(page_go, wxID_ANY, "80");
    text_go_line_length->SetValidator(wxTextValidator(wxFILTER_DIGITS, &m_go_line_length));
    text_go_line_length->SetToolTip(
    "Most generated code will not exceed this length. This will be the initial value when a new project is created.");
    box_sizer13_11->Add(text_go_line_length, wxSizerFlags().Border(wxALL));

    page_sizer5_11->Add(box_sizer13_11, wxSizerFlags().Border(wxALL));

    auto* box_sizer14_11 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_text7_11 = new wxStaticText(page_go, wxID_ANY, "kwxgo version");
    box_sizer14_11->Add(static_text7_11, wxSizerFlags().Center().Border(wxALL));

    m_choice_go_version = new wxChoice(page_go, wxID_ANY);
    m_choice_go_version->Append("0.9.0");
    m_choice_go_version->Append("1.0.0");
    m_choice_go_version->SetStringSelection("0.0.0");
    m_choice_go_version->SetToolTip("Code requiring a newer version then this will be placed in a conditional block.");
    box_sizer14_11->Add(m_choice_go_version, wxSizerFlags().Border(wxALL));

    page_sizer5_11->Add(box_sizer14_11, wxSizerFlags().Border(wxALL));

    auto* grid_sizer7_11 = new wxGridSizer(2, 0, 0);

    auto* staticText28_11 = new wxStaticText(page_go, wxID_ANY, "wxWidgets &keyword color:");
    grid_sizer7_11->Add(staticText28_11, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_go = new wxColourPickerCtrl(page_go, wxID_ANY, wxColour("#FF00FF"));
    grid_sizer7_11->Add(m_colour_go, wxSizerFlags().Border(wxALL));

    auto* staticText29_11 = new wxStaticText(page_go, wxID_ANY, "&Comment color:");
    grid_sizer7_11->Add(staticText29_11, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_go_comment = new wxColourPickerCtrl(page_go, wxID_ANY, wxColour("#008000"));
    grid_sizer7_11->Add(m_colour_go_comment, wxSizerFlags().Border(wxALL));

    auto* staticText30_11 = new wxStaticText(page_go, wxID_ANY, "&Number color:");
    grid_sizer7_11->Add(staticText30_11, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_go_number = new wxColourPickerCtrl(page_go, wxID_ANY, wxColour("#FF0000"));
    grid_sizer7_11->Add(m_colour_go_number, wxSizerFlags().Border(wxALL));

    auto* staticText31_11 = new wxStaticText(page_go, wxID_ANY, "&String color:");
    grid_sizer7_11->Add(staticText31_11, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_perl_string_11 = new wxColourPickerCtrl(page_go, wxID_ANY, wxColour("#008000"));
    grid_sizer7_11->Add(m_colour_perl_string_11, wxSizerFlags().Border(wxALL));

    page_sizer5_11->Add(grid_sizer7_11, wxSizerFlags().Border(wxALL));
    page_go->SetSizerAndFit(page_sizer5_11);

    auto* page_julia = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_julia, "Julia", false, 5);

    auto* page_sizer5_12 = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer13_12 = new wxBoxSizer(wxHORIZONTAL);

    auto* staticText27_12 = new wxStaticText(page_julia, wxID_ANY, "&Line Length");
    staticText27_12->Wrap(200);
    box_sizer13_12->Add(staticText27_12, wxSizerFlags().Center().Border(wxALL));

    auto* text_julia_line_length = new wxTextCtrl(page_julia, wxID_ANY, "80");
    text_julia_line_length->SetValidator(wxTextValidator(wxFILTER_DIGITS, &m_julia_line_length));
    text_julia_line_length->SetToolTip(
    "Most generated code will not exceed this length. This will be the initial value when a new project is created.");
    box_sizer13_12->Add(text_julia_line_length, wxSizerFlags().Border(wxALL));

    page_sizer5_12->Add(box_sizer13_12, wxSizerFlags().Border(wxALL));

    auto* box_sizer14_12 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_text7_12 = new wxStaticText(page_julia, wxID_ANY, "kwxjulia version");
    box_sizer14_12->Add(static_text7_12, wxSizerFlags().Center().Border(wxALL));

    m_choice_julia_version = new wxChoice(page_julia, wxID_ANY);
    m_choice_julia_version->Append("0.9.0");
    m_choice_julia_version->Append("1.0.0");
    m_choice_julia_version->SetStringSelection("0.0.0");
    m_choice_julia_version->SetToolTip("Code requiring a newer version then this will be placed in a conditional block.");
    box_sizer14_12->Add(m_choice_julia_version, wxSizerFlags().Border(wxALL));

    page_sizer5_12->Add(box_sizer14_12, wxSizerFlags().Border(wxALL));

    auto* grid_sizer7_12 = new wxGridSizer(2, 0, 0);

    auto* staticText28_12 = new wxStaticText(page_julia, wxID_ANY, "wxWidgets &keyword color:");
    grid_sizer7_12->Add(staticText28_12, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_julia = new wxColourPickerCtrl(page_julia, wxID_ANY, wxColour("#FF00FF"));
    grid_sizer7_12->Add(m_colour_julia, wxSizerFlags().Border(wxALL));

    auto* staticText29_12 = new wxStaticText(page_julia, wxID_ANY, "&Comment color:");
    grid_sizer7_12->Add(staticText29_12, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_julia_comment = new wxColourPickerCtrl(page_julia, wxID_ANY, wxColour("#008000"));
    grid_sizer7_12->Add(m_colour_julia_comment, wxSizerFlags().Border(wxALL));

    auto* staticText30_12 = new wxStaticText(page_julia, wxID_ANY, "&Number color:");
    grid_sizer7_12->Add(staticText30_12, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_julia_number = new wxColourPickerCtrl(page_julia, wxID_ANY, wxColour("#FF0000"));
    grid_sizer7_12->Add(m_colour_julia_number, wxSizerFlags().Border(wxALL));

    auto* staticText31_12 = new wxStaticText(page_julia, wxID_ANY, "&String color:");
    grid_sizer7_12->Add(staticText31_12, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_perl_string_12 = new wxColourPickerCtrl(page_julia, wxID_ANY, wxColour("#008000"));
    grid_sizer7_12->Add(m_colour_perl_string_12, wxSizerFlags().Border(wxALL));

    page_sizer5_12->Add(grid_sizer7_12, wxSizerFlags().Border(wxALL));
    page_julia->SetSizerAndFit(page_sizer5_12);

    auto* page_luajit = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_luajit, "LuaJIT", false, 6);

    auto* page_sizer5_13 = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer13_13 = new wxBoxSizer(wxHORIZONTAL);

    auto* staticText27_13 = new wxStaticText(page_luajit, wxID_ANY, "&Line Length");
    staticText27_13->Wrap(200);
    box_sizer13_13->Add(staticText27_13, wxSizerFlags().Center().Border(wxALL));

    auto* text_luajit_line_length = new wxTextCtrl(page_luajit, wxID_ANY, "80");
    text_luajit_line_length->SetValidator(wxTextValidator(wxFILTER_DIGITS, &m_luajit_line_length));
    text_luajit_line_length->SetToolTip(
    "Most generated code will not exceed this length. This will be the initial value when a new project is created.");
    box_sizer13_13->Add(text_luajit_line_length, wxSizerFlags().Border(wxALL));

    page_sizer5_13->Add(box_sizer13_13, wxSizerFlags().Border(wxALL));

    auto* box_sizer14_13 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_text7_13 = new wxStaticText(page_luajit, wxID_ANY, "kwxluajit version");
    box_sizer14_13->Add(static_text7_13, wxSizerFlags().Center().Border(wxALL));

    m_choice_luajit_version = new wxChoice(page_luajit, wxID_ANY);
    m_choice_luajit_version->Append("0.9.0");
    m_choice_luajit_version->Append("1.0.0");
    m_choice_luajit_version->SetStringSelection("0.0.0");
    m_choice_luajit_version->SetToolTip("Code requiring a newer version then this will be placed in a conditional block.");
    box_sizer14_13->Add(m_choice_luajit_version, wxSizerFlags().Border(wxALL));

    page_sizer5_13->Add(box_sizer14_13, wxSizerFlags().Border(wxALL));

    auto* grid_sizer7_13 = new wxGridSizer(2, 0, 0);

    auto* staticText28_13 = new wxStaticText(page_luajit, wxID_ANY, "wxWidgets &keyword color:");
    grid_sizer7_13->Add(staticText28_13, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_luajit = new wxColourPickerCtrl(page_luajit, wxID_ANY, wxColour("#FF00FF"));
    grid_sizer7_13->Add(m_colour_luajit, wxSizerFlags().Border(wxALL));

    auto* staticText29_13 = new wxStaticText(page_luajit, wxID_ANY, "&Comment color:");
    grid_sizer7_13->Add(staticText29_13, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_luajit_comment = new wxColourPickerCtrl(page_luajit, wxID_ANY, wxColour("#008000"));
    grid_sizer7_13->Add(m_colour_luajit_comment, wxSizerFlags().Border(wxALL));

    auto* staticText30_13 = new wxStaticText(page_luajit, wxID_ANY, "&Number color:");
    grid_sizer7_13->Add(staticText30_13, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_luajit_number = new wxColourPickerCtrl(page_luajit, wxID_ANY, wxColour("#FF0000"));
    grid_sizer7_13->Add(m_colour_luajit_number, wxSizerFlags().Border(wxALL));

    auto* staticText31_13 = new wxStaticText(page_luajit, wxID_ANY, "&String color:");
    grid_sizer7_13->Add(staticText31_13, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_perl_string_13 = new wxColourPickerCtrl(page_luajit, wxID_ANY, wxColour("#008000"));
    grid_sizer7_13->Add(m_colour_perl_string_13, wxSizerFlags().Border(wxALL));

    page_sizer5_13->Add(grid_sizer7_13, wxSizerFlags().Border(wxALL));
    page_luajit->SetSizerAndFit(page_sizer5_13);

    auto* page_typescript = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_typescript, "TypeScript", false, 7);

    auto* page_sizer5_14 = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer13_14 = new wxBoxSizer(wxHORIZONTAL);

    auto* staticText27_14 = new wxStaticText(page_typescript, wxID_ANY, "&Line Length");
    staticText27_14->Wrap(200);
    box_sizer13_14->Add(staticText27_14, wxSizerFlags().Center().Border(wxALL));

    auto* text_typescript_line_length = new wxTextCtrl(page_typescript, wxID_ANY, "80");
    text_typescript_line_length->SetValidator(wxTextValidator(wxFILTER_DIGITS, &m_typescript_line_length));
    text_typescript_line_length->SetToolTip(
    "Most generated code will not exceed this length. This will be the initial value when a new project is created.");
    box_sizer13_14->Add(text_typescript_line_length, wxSizerFlags().Border(wxALL));

    page_sizer5_14->Add(box_sizer13_14, wxSizerFlags().Border(wxALL));

    auto* box_sizer14_14 = new wxBoxSizer(wxHORIZONTAL);

    auto* static_text7_14 = new wxStaticText(page_typescript, wxID_ANY, "kwxtypescript version");
    box_sizer14_14->Add(static_text7_14, wxSizerFlags().Center().Border(wxALL));

    m_choice_typescript_version = new wxChoice(page_typescript, wxID_ANY);
    m_choice_typescript_version->Append("0.9.0");
    m_choice_typescript_version->Append("1.0.0");
    m_choice_typescript_version->SetStringSelection("0.0.0");
    m_choice_typescript_version->SetToolTip("Code requiring a newer version then this will be placed in a conditional block.");
    box_sizer14_14->Add(m_choice_typescript_version, wxSizerFlags().Border(wxALL));

    page_sizer5_14->Add(box_sizer14_14, wxSizerFlags().Border(wxALL));

    auto* grid_sizer7_14 = new wxGridSizer(2, 0, 0);

    auto* staticText28_14 = new wxStaticText(page_typescript, wxID_ANY, "wxWidgets &keyword color:");
    grid_sizer7_14->Add(staticText28_14, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_typescript = new wxColourPickerCtrl(page_typescript, wxID_ANY, wxColour("#FF00FF"));
    grid_sizer7_14->Add(m_colour_typescript, wxSizerFlags().Border(wxALL));

    auto* staticText29_14 = new wxStaticText(page_typescript, wxID_ANY, "&Comment color:");
    grid_sizer7_14->Add(staticText29_14, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_typescript_comment = new wxColourPickerCtrl(page_typescript, wxID_ANY, wxColour("#008000"));
    grid_sizer7_14->Add(m_colour_typescript_comment, wxSizerFlags().Border(wxALL));

    auto* staticText30_14 = new wxStaticText(page_typescript, wxID_ANY, "&Number color:");
    grid_sizer7_14->Add(staticText30_14, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_typescript_number = new wxColourPickerCtrl(page_typescript, wxID_ANY, wxColour("#FF0000"));
    grid_sizer7_14->Add(m_colour_typescript_number, wxSizerFlags().Border(wxALL));

    auto* staticText31_14 = new wxStaticText(page_typescript, wxID_ANY, "&String color:");
    grid_sizer7_14->Add(staticText31_14, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_perl_string_14 = new wxColourPickerCtrl(page_typescript, wxID_ANY, wxColour("#008000"));
    grid_sizer7_14->Add(m_colour_perl_string_14, wxSizerFlags().Border(wxALL));

    page_sizer5_14->Add(grid_sizer7_14, wxSizerFlags().Border(wxALL));
    page_typescript->SetSizerAndFit(page_sizer5_14);

    auto* page_xrc = new wxPanel(notebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    notebook->AddPage(page_xrc, "XRC", false, 8);

    auto* page_sizer2 = new wxBoxSizer(wxVERTICAL);

    auto* grid_sizer = new wxGridSizer(2, 0, 0);

    auto* staticText3 = new wxStaticText(page_xrc, wxID_ANY, "&Attribute color:");
    grid_sizer->Add(staticText3, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_xrc_attribute = new wxColourPickerCtrl(page_xrc, wxID_ANY, wxColour("#FF00FF"));
    grid_sizer->Add(m_colour_xrc_attribute, wxSizerFlags().Border(wxALL));

    auto* staticText4 = new wxStaticText(page_xrc, wxID_ANY, "&String color:");
    grid_sizer->Add(staticText4, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_xrc_string = new wxColourPickerCtrl(page_xrc, wxID_ANY, wxColour("#008000"));
    grid_sizer->Add(m_colour_xrc_string, wxSizerFlags().Border(wxALL));

    auto* staticText2 = new wxStaticText(page_xrc, wxID_ANY, "&Tag color:");
    grid_sizer->Add(staticText2, wxSizerFlags().CenterVertical().Border(wxALL));

    m_colour_xrc_tag = new wxColourPickerCtrl(page_xrc, wxID_ANY, wxColour("#0000FF"));
    grid_sizer->Add(m_colour_xrc_tag, wxSizerFlags().Border(wxALL));

    page_sizer2->Add(grid_sizer, wxSizerFlags().Border(wxALL));

    auto* box_sizer5 = new wxBoxSizer(wxHORIZONTAL);

    page_sizer2->Add(box_sizer5, wxSizerFlags().Border(wxALL));
    page_xrc->SetSizerAndFit(page_sizer2);

    auto* stdBtn = CreateStdDialogButtonSizer(wxOK|wxCANCEL);
    dlg_sizer->Add(CreateSeparatedSizer(stdBtn), wxSizerFlags().Expand().Border(wxALL));

    if (pos != wxDefaultPosition)
    {
        // Now that the dialog is created, set the scaled position
        SetPosition(FromDIP(pos));
    }
    if (size == wxDefaultSize)
    {
        // If default size let the sizer set the dialog's size
        // so that it is large enough to fit it's child controls.
        SetSizerAndFit(dlg_sizer);
    }
    else
    {
        SetSizer(dlg_sizer);
        if (size.x == wxDefaultCoord || size.y == wxDefaultCoord)
        {
            // Use the sizer to calculate the missing dimension
            Fit();
        }
        SetSize(FromDIP(size));
        Layout();
    }
    Centre(wxBOTH);

    // Event handlers
    Bind(wxEVT_BUTTON, &PreferencesDlg::OnOK, this, wxID_OK);
    m_btn_font->Bind(wxEVT_BUTTON, &PreferencesDlg::OnFontButton, this);
    Bind(wxEVT_INIT_DIALOG, &PreferencesDlg::OnInit, this);

    return true;
}

namespace wxue_img
{
    // ../art_src/julia_logo.svg
    const unsigned char julia_logo_svg[167] {
        120,218,117,144,193,14,130,48,16,68,253,148,205,26,143,6,232,90,40,9,229,224,209,191,40,181,192,38,53,36,21,65,
        255,222,34,122,82,55,217,100,103,50,111,14,91,93,167,14,76,96,179,247,166,113,94,227,233,230,217,32,132,193,59,
        141,124,233,16,38,118,243,113,184,107,76,33,5,153,137,101,177,174,130,179,35,204,124,30,123,141,139,3,189,227,174,
        31,223,34,196,124,38,119,8,45,251,216,186,109,95,131,73,93,89,14,214,187,143,79,170,84,34,71,176,49,47,228,114,
        60,34,72,69,108,208,168,232,27,176,13,89,162,21,200,14,114,5,72,148,127,129,82,74,213,136,21,160,188,248,5,36,241,
        9,245,230,9,95,153,73,137
    };

    }

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// NOLINTEND
// cppcheck-suppress-end *
// ***********************************************
// </auto-generated>
/////////////////// Non-generated Copyright/License Info ////////////////////
// Purpose:
// Author:    Ralph Walden
// Copyright: Copyright (c) 2024-2025 KeyWorks Software (Ralph Walden)
// License:   Apache License -- see ../../LICENSE
/////////////////////////////////////////////////////////////////////////////

#include <wx/stc/stc.h>  // A wxWidgets implementation of Scintilla.  This class is the

#include "../customprops/font_prop_dlg.h"  // FontStringProperty class
#include "../panels/base_panel.h"          // BasePanel class
#include "font_prop.h"                     // FontProperty class
#include "mainframe.h"                     // CMainFrame -- Main window frame
#include "preferences.h"                   // Set/Get wxUiEditor preferences
#include "project_handler.h"               // ProjectHandler class
#include "wxue_namespace/wxue_string.h"    // wxue::string, wxue::string_view

void PreferencesDlg::OnInit(wxInitDialogEvent& event)
{
    m_check_dark_mode->SetValue(UserPrefs.is_DarkMode());
#if defined(__WINDOWS__)
    m_check_high_contrast->SetValue(UserPrefs.is_HighContrast());
#endif
    m_check_fullpath->SetValue(UserPrefs.is_FullPathTitle());
    m_check_svg_bitmaps->SetValue(UserPrefs.is_SvgImages());

    m_check_cpp_snake_case->SetValue(UserPrefs.is_CppSnakeCase());

    m_check_load_last->SetValue(UserPrefs.is_LoadLastProject());
    m_check_right_propgrid->SetValue(UserPrefs.is_RightPropGrid());
    m_isWakaTimeEnabled = UserPrefs.is_WakaTimeEnabled();

    m_choice_cpp_version->SetStringSelection(UserPrefs.get_CppWidgetsVersion().wx());
    m_choice_python_version->SetStringSelection(UserPrefs.get_PythonVersion().wx());
    m_choice_ruby_version->SetStringSelection(UserPrefs.get_RubyVersion().wx());

    m_colour_cpp->SetColour(UserPrefs.get_CppColour());
    m_colour_cpp_comment->SetColour(UserPrefs.get_CppCommentColour());
    m_colour_cpp_keyword->SetColour(UserPrefs.get_CppKeywordColour());
    m_colour_cpp_number->SetColour(UserPrefs.get_CppNumberColour());
    m_colour_cpp_string->SetColour(UserPrefs.get_CppStringColour());

    m_colour_python->SetColour(UserPrefs.get_PythonColour());
    m_colour_python_comment->SetColour(UserPrefs.get_PythonCommentColour());
    m_colour_python_keyword->SetColour(UserPrefs.get_PythonKeywordColour());
    m_colour_python_number->SetColour(UserPrefs.get_PythonNumberColour());
    m_colour_python_string->SetColour(UserPrefs.get_PythonStringColour());

    m_colour_ruby->SetColour(UserPrefs.get_RubyColour());
    m_colour_ruby_comment->SetColour(UserPrefs.get_RubyCommentColour());
    m_colour_ruby_number->SetColour(UserPrefs.get_RubyNumberColour());
    m_colour_ruby_string->SetColour(UserPrefs.get_RubyStringColour());

    m_colour_xrc_attribute->SetColour(UserPrefs.get_XrcAttributeColour());
    m_colour_xrc_string->SetColour(UserPrefs.get_XrcDblStringColour());
    m_colour_xrc_tag->SetColour(UserPrefs.get_XrcTagColour());

    m_cpp_line_length = std::to_string(UserPrefs.get_CppLineLength());
    m_python_line_length = std::to_string(UserPrefs.get_PythonLineLength());
    m_ruby_line_length = std::to_string(UserPrefs.get_RubyLineLength());

    m_choice_icon_size->SetStringSelection(std::to_string(UserPrefs.get_IconSize()));

    FontProperty font_prop(UserPrefs.get_CodeDisplayFont().ToStdView());
    m_btn_font->SetMainLabel(font_prop.as_wxString());

    m_box_dark_settings->ShowItems(true);

    m_general_page_sizer->Layout();
    Fit();

    // This will transfer data from the validator variables to the controls
    event.Skip();
}

void PreferencesDlg::OnFontButton(wxCommandEvent& /* event unused */)
{
    FontPropDlg dlg(this, m_btn_font->GetMainLabel());
    if (dlg.ShowModal() == wxID_OK)
    {
        FontProperty font_prop(dlg.GetFontDescription());
        m_btn_font->SetMainLabel(dlg.GetResults());
        m_general_page_sizer->Layout();
        Fit();
    }
}

void PreferencesDlg::OnOK(wxCommandEvent& /* event unused */)
{
    if (!Validate() || !TransferDataFromWindow())
    {
        // TODO: [Randalphwa - 08-01-2023]
        // If either of these fail, there's no warning to the user
        return;
    }

    bool is_prop_grid_changed = false;
    bool is_dark_changed = false;
    bool is_fullpath_changed = false;

    if (m_check_dark_mode->GetValue() != UserPrefs.is_DarkMode())
        is_dark_changed = true;
#if defined(__WINDOWS__)
    if (m_check_high_contrast->GetValue() != UserPrefs.is_HighContrast())
        is_dark_changed = true;
#endif
    if (m_check_fullpath->GetValue() != UserPrefs.is_FullPathTitle())
        is_fullpath_changed = true;

    if (m_choice_cpp_version->GetStringSelection().ToStdString() !=
        UserPrefs.get_CppWidgetsVersion())
    {
        UserPrefs.set_CppWidgetsVersion(m_choice_cpp_version->GetStringSelection().ToStdString());
        Project.get_ProjectNode()->ModifyProperty(prop_wxWidgets_version,
                                                  UserPrefs.get_CppWidgetsVersion());
    }

    if (m_choice_python_version->GetStringSelection().ToStdString() !=
        UserPrefs.get_PythonVersion())
    {
        UserPrefs.set_PythonVersion(m_choice_python_version->GetStringSelection().ToStdString());
        Project.get_ProjectNode()->ModifyProperty(prop_wxPython_version,
                                                  UserPrefs.get_PythonVersion());
    }

    if (m_choice_ruby_version->GetStringSelection().ToStdString() != UserPrefs.get_RubyVersion())
    {
        UserPrefs.set_RubyVersion(m_choice_ruby_version->GetStringSelection().ToStdString());
        Project.get_ProjectNode()->ModifyProperty(prop_wxRuby_version, UserPrefs.get_RubyVersion());
    }

    UserPrefs.set_DarkModePending(Prefs::PENDING_DARK_MODE_ENABLE |
                                  (m_check_dark_mode->GetValue() ? Prefs::PENDING_DARK_MODE_ON :
                                                                   Prefs::PENDING_DARK_MODE_OFF));
#if defined(__WINDOWS__)
    UserPrefs.set_HighContrast(m_check_high_contrast->GetValue());
#endif
    UserPrefs.set_FullPathTitle(m_check_fullpath->GetValue());
    UserPrefs.set_SvgImages(m_check_svg_bitmaps->GetValue());

    UserPrefs.set_CppSnakeCase(m_check_cpp_snake_case->GetValue());
    UserPrefs.set_LoadLastProject(m_check_load_last->GetValue());
    UserPrefs.set_RightPropGrid(m_check_right_propgrid->GetValue());
    UserPrefs.set_WakaTimeEnabled(m_isWakaTimeEnabled);

    if (auto panel = wxGetFrame().GetCppPanel(); panel)
    {
        if (UserPrefs.get_CppColour() != m_colour_cpp->GetColour())
        {
            UserPrefs.set_CppColour(m_colour_cpp->GetColour());
            panel->SetColor(wxSTC_C_WORD, m_colour_cpp->GetColour());
        }

        if (UserPrefs.get_CppCommentColour() != m_colour_cpp_comment->GetColour())
        {
            UserPrefs.set_CppCommentColour(m_colour_cpp_comment->GetColour());
            panel->SetColor(wxSTC_C_COMMENTLINE, m_colour_cpp_comment->GetColour());
        }

        if (UserPrefs.get_CppKeywordColour() != m_colour_cpp_keyword->GetColour())
        {
            UserPrefs.set_CppKeywordColour(m_colour_cpp_keyword->GetColour());
            panel->SetColor(wxSTC_C_WORD2, m_colour_cpp_keyword->GetColour());
        }

        if (UserPrefs.get_CppNumberColour() != m_colour_cpp_number->GetColour())
        {
            UserPrefs.set_CppNumberColour(m_colour_cpp_number->GetColour());
            panel->SetColor(wxSTC_C_NUMBER, m_colour_cpp_number->GetColour());
        }

        if (UserPrefs.get_CppStringColour() != m_colour_cpp_string->GetColour())
        {
            UserPrefs.set_CppStringColour(m_colour_cpp_string->GetColour());
            panel->SetColor(wxSTC_C_STRING, m_colour_cpp_string->GetColour());
        }
    }

    if (auto panel = wxGetFrame().GetPythonPanel(); panel)
    {
        if (UserPrefs.get_PythonColour() != m_colour_python->GetColour())
        {
            UserPrefs.set_PythonColour(m_colour_python->GetColour());
            panel->SetColor(wxSTC_P_WORD, m_colour_python->GetColour());
        }

        if (UserPrefs.get_PythonKeywordColour() != m_colour_python_keyword->GetColour())
        {
            UserPrefs.set_PythonKeywordColour(m_colour_python_keyword->GetColour());
            panel->SetColor(wxSTC_P_WORD2, m_colour_python_keyword->GetColour());
        }

        if (UserPrefs.get_PythonCommentColour() != m_colour_python_comment->GetColour())
        {
            UserPrefs.set_PythonCommentColour(m_colour_python_comment->GetColour());
            panel->SetColor(wxSTC_P_COMMENTLINE, m_colour_python_comment->GetColour());
        }

        if (UserPrefs.get_PythonNumberColour() != m_colour_python_number->GetColour())
        {
            UserPrefs.set_PythonNumberColour(m_colour_python_number->GetColour());
            panel->SetColor(wxSTC_P_NUMBER, m_colour_python_number->GetColour());
        }

        if (UserPrefs.get_PythonStringColour() != m_colour_python_string->GetColour())
        {
            UserPrefs.set_PythonStringColour(m_colour_python_string->GetColour());
            panel->SetColor(wxSTC_P_STRING, m_colour_python_string->GetColour());
        }
    }

    if (auto panel = wxGetFrame().GetRubyPanel(); panel)
    {
        if (UserPrefs.get_RubyColour() != m_colour_ruby->GetColour())
        {
            UserPrefs.set_RubyColour(m_colour_ruby->GetColour());
            panel->SetColor(wxSTC_RB_WORD, m_colour_ruby->GetColour());
        }

        if (UserPrefs.get_RubyCommentColour() != m_colour_ruby_comment->GetColour())
        {
            UserPrefs.set_RubyCommentColour(m_colour_ruby_comment->GetColour());
            panel->SetColor(wxSTC_RB_COMMENTLINE, m_colour_ruby_comment->GetColour());
        }

        if (UserPrefs.get_RubyNumberColour() != m_colour_ruby_number->GetColour())
        {
            UserPrefs.set_RubyNumberColour(m_colour_ruby_number->GetColour());
            panel->SetColor(wxSTC_RB_NUMBER, m_colour_ruby_number->GetColour());
        }

        if (UserPrefs.get_RubyStringColour() != m_colour_ruby_string->GetColour())
        {
            UserPrefs.set_RubyStringColour(m_colour_ruby_string->GetColour());
            panel->SetColor(wxSTC_RB_STRING, m_colour_ruby_string->GetColour());
            panel->SetColor(wxSTC_RB_STRING_Q, m_colour_ruby_string->GetColour());
            panel->SetColor(wxSTC_RB_STRING_QQ, m_colour_ruby_string->GetColour());
            panel->SetColor(wxSTC_RB_STRING_QX, m_colour_ruby_string->GetColour());
            panel->SetColor(wxSTC_RB_STRING_QR, m_colour_ruby_string->GetColour());
            panel->SetColor(wxSTC_RB_STRING_QW, m_colour_ruby_string->GetColour());
        }
    }

    if (auto panel = wxGetFrame().GetXrcPanel(); panel)
    {
        if (UserPrefs.get_XrcAttributeColour() != m_colour_xrc_attribute->GetColour())
        {
            UserPrefs.set_XrcAttributeColour(m_colour_xrc_attribute->GetColour());
            panel->SetColor(wxSTC_H_ATTRIBUTE, m_colour_xrc_attribute->GetColour());
        }

        if (UserPrefs.get_XrcDblStringColour() != m_colour_xrc_string->GetColour())
        {
            UserPrefs.set_XrcDblStringColour(m_colour_xrc_string->GetColour());
            panel->SetColor(wxSTC_H_DOUBLESTRING, m_colour_xrc_string->GetColour());
        }

        if (UserPrefs.get_XrcTagColour() != m_colour_xrc_tag->GetColour())
        {
            UserPrefs.set_XrcTagColour(m_colour_xrc_tag->GetColour());
            panel->SetColor(wxSTC_H_TAG, m_colour_xrc_tag->GetColour());
        }
    }

    if (UserPrefs.get_CodeDisplayFont() != m_btn_font->GetMainLabel().utf8_string())
    {
        FontProperty font_prop(wxue::string_view(m_btn_font->GetMainLabel().utf8_string()));
        auto font = font_prop.GetFont();
        UserPrefs.set_CodeDisplayFont(font_prop.as_string());
        if (auto* cpp_panel = wxGetFrame().GetCppPanel(); cpp_panel)
        {
            cpp_panel->SetCodeFont(font);
        }
        if (auto* python_panel = wxGetFrame().GetPythonPanel(); python_panel)
        {
            python_panel->SetCodeFont(font);
        }
        if (auto* ruby_panel = wxGetFrame().GetRubyPanel(); ruby_panel)
        {
            ruby_panel->SetCodeFont(font);
        }
        if (auto* xrc_panel = wxGetFrame().GetXrcPanel(); xrc_panel)
        {
            xrc_panel->SetCodeFont(font);
        }
    }

    auto line_length = wxue::atoi(m_cpp_line_length.ToStdString());

    auto fix_line_length = [&]()
    {
        if (line_length < 40)
            line_length = 40;
        else if (line_length > 300)
            line_length = 300;
    };

    fix_line_length();
    UserPrefs.set_CppLineLength(line_length);

    line_length = wxue::atoi(m_python_line_length.ToStdString());
    fix_line_length();
    UserPrefs.set_PythonLineLength(line_length);

    line_length = wxue::atoi(m_ruby_line_length.ToStdString());
    fix_line_length();
    UserPrefs.set_RubyLineLength(line_length);

    auto old_size = UserPrefs.get_IconSize();
    UserPrefs.set_IconSize(wxue::atoi(m_choice_icon_size->GetStringSelection().ToStdString()));
    bool is_icon_size_changed = old_size != UserPrefs.get_IconSize();

    // UserPrefs.set_CodeDisplayFont(m_code_font_picker->GetSelectedFontInfo());

    UserPrefs.WriteConfig();

    if (is_prop_grid_changed || is_dark_changed || is_icon_size_changed)
    {
        wxue::string msg("You must close and reopen wxUiEditor for");
        if (is_prop_grid_changed)
        {
            msg += " the Property Panel";
            if (is_dark_changed)
                msg += " and Dark Mode";
        }
        if (is_dark_changed)
            msg += " the Dark Mode";
        if (is_icon_size_changed)
        {
            if (!msg.ends_with("for"))
                msg += " and";
            msg += " Icon Size";
        }

        msg += " setting(s) to take effect.";

        wxMessageBox(msg);
    }

    if (is_fullpath_changed)
    {
        wxGetFrame().UpdateFrame();
    }

    EndModal(wxID_OK);
}
