# Requires ttBld.exe version 1.8.0 or higher to process -- see https://github.com/KeyWorksRW/ttBld

Options:
    Project:      wxUiTesting  # project name
    # Exe_type:     window       # [window | console | lib | dll]
    Exe_type:     lib       # [window | console | lib | dll]
    Pch:          pch.h        # name of precompiled header file, or "none" if not using precompiledheaders
    Optimize:     space        # [space | speed] optimization to use in release builds
    Warn:         4            # [1-4] warning level

    Crt_rel:      dll          # [static | dll] type of CRT to link to in release builds
    Crt_dbg:      dll          # [static | dll] type of CRT to link to in debug builds
    Ms_linker:    false        # true means use link.exe even when compiling with clang

    CFlags_cmn:   /Zc:__cplusplus /utf-8 # common compiler flags

    msvc_cmn:     -std:c++latest
    Clang_cmn:    -std:c++17

    CFlags_rel:  /DNDEBUG       # static wxWidgets libraries in release build

    IncDirs:       ./;ui;../../wxSnapshot/include;../../wxSnapshot/win
    TargetDir:   ../build/Debug              # target directory
    Natvis:      ../../src/wxui.natvis  # Use Natvis from wxUiEditor

Files:
    wxUiTesting.rc
    mainapp.cpp

    custom_ctrls/split_button.cpp  # Split Button Custom widget (button + menu)

    ui/mainframe.cpp       # Main window
    ui/mainframe_base.cpp  # wxUiEditor generated file

    ui/commonctrls.cpp
    ui/dlgmultitest.cpp
    ui/other_ctrls.cpp
    ui/popupwin.cpp
    ui/ribbondlg.cpp
    ui/wizard.cpp

    ui/wxui_code.cmake

XPM:
    art/english.png: art/english.xpm
    art/french.png: art/french.xpm
    art/japanese.png: art/japanese.xpm

Other:
    ui/wxui_code.cmake
