/////////////////////////////////////////////////////////////////////////////
// Purpose:   Generate Perl code files
// Author:    Ralph Walden
// Copyright: Copyright (c) 2024-2025 KeyWorks Software (Ralph Walden)
// License:   Apache License -- see ../../LICENSE
/////////////////////////////////////////////////////////////////////////////

#include <set>
#include <thread>

#include <frozen/map.h>

#include "gen_perl.h"

#include "base_generator.h"   // BaseGenerator -- Base widget generator class
#include "code.h"             // Code -- Helper class for generating code
#include "file_codewriter.h"  // FileCodeWriter -- Classs to write code to disk
#include "gen_common.h"       // Common component functions
#include "gen_timer.h"        // TimerGenerator class
#include "image_gen.h"        // Functions for generating embedded images
#include "image_handler.h"    // ImageHandler class
#include "node.h"             // Node class
#include "project_handler.h"  // ProjectHandler class
#include "tt_view_vector.h"   // tt_view_vector -- Read/Write line-oriented strings/files
#include "utils.h"            // Miscellaneous utilities
#include "write_code.h"       // Write code to Scintilla or file

#include "../customprops/eventhandler_dlg.h"  // EventHandlerDlg static functions

using namespace code;
using namespace GenEnum;

// clang-format off

inline constexpr const auto txt_PoundCmtBlock =
R"===(###############################################################################
# Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# Do not edit any code above the "End of generated code" comment block.
# Any changes before that block will be lost if it is re-generated!
###############################################################################

)===";

inline constexpr const auto txt_perl_frame_app =
R"===(# Sample code for displaying your MainFrame window.
# Place this code after the closing comment block in your
# generated file. You can then call 'Perl filename.pl'
# where filename.pl is the name of your generated file.

package main;

my $app = Wx::SimpleApp->new;
my $frame = MainFrame->new(undef, -1, "wxPerl app");
$frame->Show;
$app->MainLoop;
)===";

inline constexpr const auto txt_perl_get_bundle =
R"===(
# Loads image(s) from a string and returns a Wx::BitmapBundle object.
sub wxue_get_bundle {
    my ($image_data1, $image_data2, $image_data3) = @_;

    my $image1 = Wx::Image->new;
    $image1->LoadStream(IO::String->new($image_data1));

    if (defined $image_data2) {
        my $image2 = Wx::Image->new;
        $image2->LoadStream(IO::String->new($image_data2));
        if (defined $image_data3) {
            my $image3 = Wx::Image->new;
            $image3->LoadStream(IO::String->new($image_data3));
            my @bitmaps = (
                Wx::Bitmap->new($image1),
                Wx::Bitmap->new($image2),
                Wx::Bitmap->new($image3)
            );
            my $bundle = Wx::BitmapBundle::FromBitmaps(\@bitmaps);
            return $bundle;
        } else {
            my $bundle = Wx::BitmapBundle::FromBitmaps(
                Wx::Bitmap->new($image1),
                Wx::Bitmap->new($image2)
            );
            return $bundle;
        }
    }
    my $bundle = Wx::BitmapBundle::FromImage($image1);
    return $bundle;
})===";

// clang-format on

extern const char* python_perl_ruby_end_cmt_line;  // "# ************* End of generated code"

// extern constexpr auto map_perl_constants = frozen::make_map<GenEnum::PropName, std::string_view>;

// If the node contains the specified property, then the string contains all
// possible contants that could be used separated by spaces.
constexpr auto map_perl_constants = frozen::make_map<GenEnum::PropName, std::string_view>({

    { prop_bitmap, "wxNullBitmap" },

});

// This *MUST* be written without any indendation
const char* perl_begin_cmt_block = "=pod";

// This *MUST* be written without any indendation
const char* perl_end_cmt_block = "=cut";

PerlCodeGenerator::PerlCodeGenerator(Node* form_node) : BaseCodeGenerator(GEN_LANG_PERL, form_node)
{
}

void PerlCodeGenerator::GenerateClass(PANEL_PAGE panel_type)
{
    Code code(m_form_node, GEN_LANG_PERL);

    m_embedded_images.clear();

    SetImagesForm();
    std::set<std::string> img_include_set;

    std::thread thrd_get_events(&PerlCodeGenerator::CollectEventHandlers, this, m_form_node,
                                std::ref(m_events));
    std::thread thrd_need_img_func(&PerlCodeGenerator::ParseImageProperties, this, m_form_node);
    std::thread thrd_collect_img_headers(&PerlCodeGenerator::CollectImageHeaders, this, m_form_node,
                                         std::ref(img_include_set));

    // If the code files are being written to disk, then UpdateEmbedNodes() has already been called.
    if (panel_type != NOT_PANEL)
    {
        ProjectImages.UpdateEmbedNodes();
    }

    std::vector<Node*> forms;
    Project.CollectForms(forms);

    m_panel_type = panel_type;

    m_header->Clear();
    m_source->Clear();

    if (m_form_node->isType(type_frame_form))
    {
        code += txt_perl_frame_app;
        if (m_form_node->hasValue(prop_class_name))
        {
            tt_string class_name = m_form_node->as_string(prop_class_name);
            if (class_name.ends_with("Base"))
                class_name.erase(class_name.size() - 4);
            code.Replace("MainFrame", class_name);
        }
        m_header->writeLine(code);
        code.clear();
    }

    m_source->SetLastLineBlank();

#if !defined(_DEBUG)
    if (m_panel_type == NOT_PANEL)
#else
    if (m_panel_type != NOT_PANEL)
    {
        m_source->writeLine("-- The following comment block is only displayed in a _DEBUG build, "
                            "or when written to a file.\n\n");
    }
#endif  // _DEBUG
    {
        m_source->writeLine(txt_PoundCmtBlock);
    }

    code.Str("use Wx;").Eol();
    code.Str("package ").NodeName();
    if (code.ends_with("Base"))
        code.erase(code.size() - 4);
    code.Str(";").Eol();

    m_source->writeLine(code);
    code.clear();

    if (Project.hasValue(prop_perl_project_preamble))
    {
        WritePropSourceCode(Project.getProjectNode(), prop_perl_project_preamble);
    }

    m_source->writeLine();

    InitializeUsageStatements();
    WriteUsageStatements();

    m_set_enum_ids.clear();
    m_set_const_ids.clear();
    // Do this early to give thrd_get_events and thrd_collect_img_headers a chance to run before we
    // need to join (finish) them.
    BaseCodeGenerator::CollectIDs(m_form_node, m_set_enum_ids, m_set_const_ids);

    m_source->writeLine();
    m_source->writeLine(
        "use utf8;");  // required since C++, wxPython, and wxRuby use utf8 by default
    m_source->writeLine("use strict;");

    try
    {
        thrd_collect_img_headers.join();
    }
    catch (const std::system_error& err)
    {
#if defined(_DEBUG)
        MSG_ERROR(err.what());
#else
        wxMessageDialog dlg_error(nullptr, wxString::FromUTF8(err.what()), "Internal Thread Error",
                                  wxICON_ERROR | wxOK);
        dlg_error.ShowModal();
#endif  // _DEBUG
    }

    if (m_form_node->isGen(gen_Images))
    {
        m_source->writeLine("use MIME::Base64;");
        thrd_get_events.join();
        thrd_need_img_func.join();
        GenerateImagesForm();
        return;
    }

    else if (m_embedded_images.size())
    {
        CheckMimeBase64Requirement(code);
    }

    int id_value = wxID_HIGHEST;
    for (auto& iter: m_set_enum_ids)
    {
        m_source->writeLine(tt_string() << '$' << iter << " = " << id_value++);
    }
    for (auto& iter: m_set_const_ids)
    {
        if (tt::contains(iter, " wx"))
        {
            tt_string id = '$' + iter;
            id.Replace(" wx", " wx.", true, tt::CASE::exact);
            m_source->writeLine(id);
        }
        else
        {
            m_source->writeLine('$' + iter);
        }
    }

    auto generator = m_form_node->getNodeDeclaration()->getGenerator();
    code.clear();
    if (generator->ConstructionCode(code))
    {
        m_source->writeLine(code);
        m_source->writeLine();
        m_source->Indent();
        m_source->Indent();

        id_value = wxID_HIGHEST;
        for (auto& iter: m_set_enum_ids)
        {
            m_source->writeLine(tt_string() << '@' << iter << id_value++);
        }

        if (id_value > 1)
        {
            // If at least one id was set, add a blank line
            m_source->writeLine();
        }
    }

    code.clear();
    m_source->ResetIndent(1);
    if (generator->SettingsCode(code))
    {
        if (code.size())
        {
            m_source->writeLine(code);
            m_source->writeLine();
        }
    }

    if (m_form_node->getPropPtr(prop_window_extra_style))
    {
        code.clear();
        code.GenWindowSettings();
        if (code.size())
        {
            m_source->writeLine(code);
        }
    }

    m_source->SetLastLineBlank();
    for (const auto& child: m_form_node->getChildNodePtrs())
    {
        if (child->isGen(gen_wxContextMenuEvent))
            continue;
        GenConstruction(child.get());
    }

    code.clear();
    if (generator->AfterChildrenCode(code))
    {
        if (code.size())
        {
            m_source->writeLine();
            m_source->writeLine(code);
        }
    }

    // TODO: [Randalphwa - 07-13-2023] Need to figure out if wxPerl supports persistence

    // Timer code must be created before the events, otherwise the timer variable won't exist
    // when the event is created.

    code.clear();
    if (TimerGenerator::StartIfChildTimer(m_form_node, code))
    {
        m_source->writeLine(code);
        m_source->writeLine();
    }

    // Delay calling join() for as long as possible to increase the chance that the thread will
    // have already completed.
    thrd_get_events.join();
    if (m_events.size())
    {
        m_source->writeLine();
        m_source->writeLine("# Event handlers");
        GenSrcEventBinding(m_form_node, m_events);

        m_source->writeLine("\t# end Event handlers\n", indent::none);
        m_source->SetLastLineBlank();

        m_source->ResetIndent();
        m_source->writeLine();
        m_source->Indent();
        GenUnhandledEvents(m_events);
    }
    else
    {
        m_source->ResetIndent();
    }

    if (m_form_node->isGen(gen_wxWizard))
    {
        code.clear();
        code.Eol().Str("# Add the following below the comment block to add a simple");
        code.Eol().Str("# Run() function to launch the wizard").Eol();
        m_source->writeLine(code);
    }

    // Make certain indentation is reset after all construction code is written
    m_source->ResetIndent();
    m_source->writeLine("\treturn $self;", indent::none);
    m_source->writeLine("}\n\n", indent::none);

    thrd_need_img_func.join();
    if (m_NeedImageFunction)
    {
        m_source->writeLine(txt_perl_get_bundle, indent::auto_keep_whitespace);
    }

    // Only add this when writing to disk. Otherwise, it needs to be added after
    // the comment block, and only if there is no user code after the comment
    // block. This is to ensure that the user can add event handlers that are
    // part of the package.
    if (panel_type != NOT_PANEL)
    {
        m_source->writeLine("1;", indent::none);
    }

    m_header->ResetIndent();

    code.clear();
    // Now write any embedded images that aren't declared in the gen_Images List
    for (auto& iter: m_embedded_images)
    {
        // Only write the images that aren't declared in any gen_Images List. Note that
        // this *WILL* result in duplicate images being written to different forms.
        if (iter->form != m_ImagesForm)
        {
            WriteImageConstruction(code);
            m_source->doWrite("\n");  // force an extra line break
            m_source->SetLastLineBlank();
            break;
        }
    }

    // TODO: [Randalphwa - 07-13-2023] If we use embedded images, we need to write them out here.
#if 0
    std::sort(m_embedded_images.begin(), m_embedded_images.end(),
              [](const EmbeddedImage* a, const EmbeddedImage* b)
              {
                  return (a->array_name.compare(b->array_name) < 0);
              });
#endif
}

void PerlCodeGenerator::WriteUsageStatements()
{
    if (m_use_classes.size())
    {
        m_source->writeLine();
        for (const auto& import: m_use_classes)
        {
            m_source->writeLine(import);
        }
        m_source->writeLine();
    }

    if (m_use_classes.size())
    {
        for (auto& iter: m_use_packages)
        {
            m_source->writeLine(iter);
        }
        m_source->writeLine();
    }

    if (m_use_expands.size())
    {
        for (auto& iter: m_use_expands)
        {
            m_source->writeLine(iter);
        }
        m_source->writeLine();
    }

    if (m_use_constants.size())
    {
        for (auto& iter: m_use_constants)
        {
            m_source->writeLine(iter);
        }
        m_source->writeLine();
    }
}

void PerlCodeGenerator::GenerateImagesForm()
{
    if (m_embedded_images.empty() || !m_form_node->getChildCount())
    {
        return;
    }

    // TODO: [Randalphwa - 05-29-2025] Implement Perl image generation
}

// This function simply generates unhandled event handlers in a multi-string comment.

void PerlCodeGenerator::GenUnhandledEvents(EventVector& events)
{
    ASSERT_MSG(events.size(), "GenUnhandledEvents() shouldn't be called if there are no events");
    if (events.empty())
    {
        return;
    }

    // Multiple events can be bound to the same function, so use a set to make sure we only generate
    // each function once.
    std::unordered_set<std::string> code_lines;

    Code code(m_form_node, GEN_LANG_PERL);
    auto sort_event_handlers = [](NodeEvent* a, NodeEvent* b)
    {
        return (EventHandlerDlg::GetPerlValue(a->get_value()) <
                EventHandlerDlg::GetPerlValue(b->get_value()));
    };

    // Sort events by function name
    std::sort(events.begin(), events.end(), sort_event_handlers);

    bool found_user_handlers = false;
    if (m_panel_type == NOT_PANEL)
    {
        tt_view_vector org_file;
        auto [path, has_base_file] = Project.GetOutputPath(m_form_node, GEN_LANG_PERL);

        if (has_base_file && path.extension().empty())
        {
            path += ".pl";
        }

        // If the user has defined any event handlers, add them to the code_lines set so we
        // don't generate them again.
        if (has_base_file && org_file.ReadFile(path))
        {
            size_t line_index;
            for (line_index = 0; line_index < org_file.size(); ++line_index)
            {
                if (org_file[line_index].is_sameprefix(python_perl_ruby_end_cmt_line))
                {
                    break;
                }
            }
            for (++line_index; line_index < org_file.size(); ++line_index)
            {
                auto handler = org_file[line_index].view_nonspace();
                if (org_file[line_index].view_nonspace().starts_with("sub "))
                {
                    code_lines.emplace(handler);
                    found_user_handlers = true;
                }
            }
        }
    }

    bool is_all_events_implemented = true;
    if (found_user_handlers)
    {
        for (auto& event: events)
        {
            auto handler = EventHandlerDlg::GetPerlValue(event->get_value());
            // Ignore lambda's
            if (handler.starts_with("[perl:lambda]"))
                continue;

            tt_string set_code;
            // If the user doesn't use the `event` parameter, they may use '_' instead to indicate
            // an unused parameter.
            set_code << "sub " << handler << " {";
            if (code_lines.find(set_code) != code_lines.end())
                continue;
            set_code << "sub " << handler << " {";
            if (code_lines.find(set_code) != code_lines.end())
                continue;

            // At least one event wasn't implemented, so stop looking for more
            is_all_events_implemented = false;

            code.Str("# Unimplemented Event handler functions\n# Copy any listed and paste them "
                     "below the comment block, or "
                     "to your inherited class.");
            break;
        }
        if (is_all_events_implemented)
        {
            // If the user has defined all the event handlers, then we don't need to output anything
            // else.
            return;
        }
    }
    else
    {
        // The user hasn't defined their own event handlers in this module
        is_all_events_implemented = false;

        code.Str("# Event handler functions\n# Add these below the comment block, or to your "
                 "inherited class.");
    }
    m_source->writeLine(code);

    code.clear();
    if (!is_all_events_implemented)
    {
        for (auto& event: events)
        {
            auto handler = EventHandlerDlg::GetPerlValue(event->get_value());
            // Ignore lambda's
            if (handler.empty() || handler.starts_with("[perl:lambda]"))
                continue;

            tt_string set_code;
            // If the user doesn't use the `event` parameter, they may use '_' instead to indicate
            // an unused parameter.
            set_code << "sub " << handler << " {";

            if (code_lines.find(set_code) != code_lines.end())
                continue;
            code_lines.emplace(set_code);

            code.Str(set_code).Eol();
            code.Tab().Str("my ($self, $event) = @_;").Eol();
#if defined(_DEBUG)
            auto& dbg_event_name = event->get_name();
            wxUnusedVar(dbg_event_name);
#endif  // _DEBUG
            if (event->get_name() == "CloseButtonClicked")
            {
                code.Tab().Str("$self->EndModal(wxID_CLOSE);").Eol();
            }
            else if (event->get_name() == "YesButtonClicked")
            {
                code.Tab().Str("$self->EndModal(wxID_YES);").Eol();
            }
            else if (event->get_name() == "NoButtonClicked")
            {
                code.Tab().Str("$self->EndModal(wxID_NO);").Eol();
            }
            else
            {
                code.Tab().Str("$event->Skip();").Eol();
            }
            code.Str("}").Eol();
        }
    }

    // Write the unimplemented event handlers to the source file without the
    // comment block to make it easier for the user to cut and paste and/or add
    // them to an inherited class.
    if (found_user_handlers && !is_all_events_implemented)
    {
        m_header->writeLine("# Unimplemented Event handler functions");
    }
    else
    {
        m_header->writeLine("# Event handler functions");
    }
    m_header->writeLine(code);

    if (!is_all_events_implemented)
    {
        m_source->ResetIndent();
        m_source->writeLine(perl_begin_cmt_block);
        m_source->Indent();
        m_source->writeLine(code);
        m_source->Unindent();
        m_source->writeLine(perl_end_cmt_block);
        m_source->Indent();
    }
}

void PerlCodeGenerator::CheckMimeBase64Requirement(Code& code)
{
    ASSERT_MSG(m_embedded_images.size(),
               "CheckMimeBase64Requirement() should only be called if there are embedded images");
    if (m_embedded_images.empty())
    {
        return;
    }
    bool images_file_imported = false;
    bool svg_import_libs = false;
    for (auto& iter: m_embedded_images)
    {
        if (iter->form == m_ImagesForm)
        {
            if (!images_file_imported)
            {
                tt_string import_name = iter->form->as_string(prop_perl_file).filename();
                import_name.remove_extension();
                code.Eol().Str("use ").Str(import_name) << "'";
                m_source->writeLine(code);
                code.clear();
                images_file_imported = true;
            }
            if (iter->imgs[0].type == wxBITMAP_TYPE_SVG)
            {
                if (!svg_import_libs)
                {
                    // TODO: [Randalphwa - 05-29-2025] Currently, wxPerl does not support SVG
                    // files. We could take advantage of wxLunaSVG and convert the SVG files to
                    // PNG -- in fact we could even generate multiple resolution PNG files.

                    // svg_import_libs = true;
                }
            }

            if (iter->form != m_ImagesForm)
            {
                // If the image isn't in the images file, then we need to add the base64 version
                // of the bitmap
                if (!m_base64_requirement_written)
                {
                    m_source->writeLine("use MIME::Base64;");
                    m_base64_requirement_written = true;
                }

                // At this point we know that some method is required, but until we have
                // processed all the images, we won't know if the images file is required. The
                // images file provides it's own function for loading images, so we can use that
                // if it's available.
                m_NeedImageFunction = true;
            }
        }
    }  // end of for (auto& iter: m_embedded_images)

    if (m_NeedImageFunction)
    {
        if (images_file_imported)
        {
            // The images file supplies the function we need
            m_NeedImageFunction = false;
        }
        else
        {
            // REVIEW: [Randalphwa - 05-29-2025] This is just here as a placeholder in case we
            // need to bring in another package for loading images.
            if (!m_stringio_requirement_written)
            {
                // No further check for this is needed
                // stringio_requirement_written = true;
                // m_source->writeLine("require 'stringio'");
            }
        }
    }
}

void PerlCodeGenerator::InitializeUsageStatements()
{
    m_use_expands.emplace("use Wx qw[:id];");

    ParseNodesForUsage(m_form_node);

    if (m_art_ids.size())
    {
        tt_string art_ids;
        for (auto& iter: m_art_ids)
        {
            if (art_ids.empty())
            {
                art_ids = "use Wx::ArtProvider qw(";
            }
            else
            {
                art_ids += ' ';
            }
            art_ids += iter;
            if (art_ids.size() > (Project.as_size_t(prop_perl_line_length) - 15))
            {
                art_ids += ");";
                m_use_packages.emplace(art_ids);
                art_ids.clear();
            }
        }
        if (art_ids.size())
        {
            art_ids += ");";
            m_use_packages.emplace(art_ids);
        }
    }
}

void PerlCodeGenerator::ParseNodesForUsage(Node* node)
{
    if (node->isSizer())
    {
        m_use_expands.emplace("use Wx qw[:sizer];");

        // Now recurse through any children and their children
        for (auto& child: node->getChildNodePtrs())
        {
            ParseNodesForUsage(child.get());
        }
        return;
    }

    if (node->hasValue(prop_window_style) || node->hasValue(prop_window_extra_style) ||
        (node->hasValue(prop_variant) && node->as_string(prop_variant) != "normal"))
    {
        m_use_expands.emplace("use Wx qw[:window];");
    }

    if (node->hasValue(prop_bitmap))
    {
        if (node->as_string(prop_bitmap).contains("wxART_"))
        {
            m_use_packages.emplace("use Wx::ArtProvider qw[:artid :clientid];");
        }
        else if (node->as_string(prop_bitmap).starts_with("XPM"))
        {
            m_use_expands.emplace("use Wx qw[:image];");
        }
    }

    if (node->hasValue(prop_font))
    {
        m_use_expands.emplace("use Wx qw[:font];");
        FontProperty fontprop(node->getPropPtr(prop_font));
        if (fontprop.isDefGuiFont())
        {
            // If the font is a default GUI font, then we need to include the wxDefaultGuiFont
            // constant.
            m_use_expands.emplace("use Wx qw[:systemsettings];");
        }
    }
    if (node->hasValue(prop_foreground_colour) || node->hasValue(prop_background_colour))
    {
        if (node->as_string(prop_foreground_colour).contains("wxSYS") ||
            node->as_string(prop_background_colour).contains("wxSYS"))
        {
            m_use_expands.emplace("use Wx qw[:systemsettings];");
        }
    }
    if (auto* gen = node->getGenerator(); gen)
    {
        std::set<std::string> imports;
        gen->GetImports(node, imports, GEN_LANG_PERL);
        for (auto& iter: imports)
        {
            if (iter.starts_with("use Wx qw[:"))
                m_use_expands.emplace(iter);
            else if (iter.starts_with("use Wx::"))
                m_use_packages.emplace(iter);
            else if (iter.starts_with("use Wx "))
                m_use_constants.emplace(iter);
            else
                m_use_classes.emplace(iter);
        }
        for (auto& iter: map_perl_constants)
        {
            if (node->hasProp(iter.first))
            {
                tt_string constants("use Wx qw(");
                constants += iter.second;
                constants += ");";
                m_use_constants.emplace(constants);
            }
        }
    }

    // Now recurse through any children and their children
    for (auto& child: node->getChildNodePtrs())
    {
        ParseNodesForUsage(child.get());
    }
}

tt_string MakePerlPath(Node* node)
{
    auto [path, has_base_file] = Project.GetOutputPath(node->getForm(), GEN_LANG_PERL);

    if (path.empty())
        path = "./";
    else if (has_base_file)
        path.remove_filename();
    return path;
}

bool HasPerlMapConstant(std::string_view value)
{
    for (auto& iter: map_perl_constants)
    {
        if (tt::contains(iter.second, value))
            return true;
    }
    return false;
}

bool PerlBitmapList(Code& code, GenEnum::PropName prop)
{
    auto& description = code.node()->as_string(prop);
    ASSERT_MSG(description.size(), "PerlBitmapList called with empty description");
    tt_view_vector parts(description, BMP_PROP_SEPARATOR, tt::TRIM::both);

    if (parts[IndexImage].empty() || parts[IndexType].contains("Art") ||
        parts[IndexType].contains("SVG"))
    {
        return false;
    }

    auto bundle = ProjectImages.GetPropertyImageBundle(description);

    if (!bundle || bundle->lst_filenames.size() < 3)
    {
        return false;
    }

    bool is_xpm = (parts[IndexType].is_sameas("XPM"));
    auto path = MakePerlPath(code.node());

    code += "bitmaps = [ ";
    bool needs_comma = false;
    for (auto& iter: bundle->lst_filenames)
    {
        if (needs_comma)
        {
            code.UpdateBreakAt();
            code.Comma(false).Eol().Tab(3);
        }

        bool is_embed_success = false;
        if (parts[IndexType].starts_with("Embed"))
        {
            if (auto embed = ProjectImages.GetEmbeddedImage(iter); embed)
            {
                code.AddPerlImageName(embed);
                code += ".Bitmap";
                needs_comma = true;
                is_embed_success = true;
            }
        }

        if (!is_embed_success)
        {
            tt_string name(iter);
            name.make_absolute();
            name.make_relative(path);
            name.backslashestoforward();

            code.Str("Wx::Bitmap->new(").QuotedString(name);
            if (is_xpm)
                code.Comma().Str("wxBITMAP_TYPE_XPM");
            code += ")";
            needs_comma = true;
        }
    }
    code += " ]\n";
    code.UpdateBreakAt();

    return true;
}
