///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/gdicmn.h>
#include <wx/panel.h>
#include <wx/splitter.h>
#include <wx/stattext.h>

class FormPanelTest : public wxPanel
{
public:
    FormPanelTest() {}
    FormPanelTest(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(500, 300), long style = wxTAB_TRAVERSAL, const wxString &name = wxPanelNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = wxEmptyString, const wxPoint& pos =
        wxDefaultPosition, const wxSize& size = wxSize(500, 300),
        long style = , long style = wxTAB_TRAVERSAL, const wxString &name = wxPanelNameStr);

protected:

    // Class member variables

    wxSplitterWindow* m_splitter;
    wxStaticText* m_staticText2;
    wxStaticText* m_staticText;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
