/////////////////////////////////////////////////////////////////////////////
// Purpose:   Generate Julia code via kwxFFI
// Author:    Ralph Walden
// Copyright: Copyright (c) 2026 KeyWorks Software (Ralph Walden)
// License:   Apache License -- see ../../LICENSE
/////////////////////////////////////////////////////////////////////////////

#include "gen_julia.h"

#include "base_generator.h"   // BaseGenerator -- Base widget generator class
#include "code.h"             // Code -- Helper class for generating code
#include "gen_common.h"       // Common component functions
#include "node.h"             // Node class
#include "project_handler.h"  // ProjectHandler class
#include "write_code.h"       // Write code to Scintilla or file

#include "wxue_namespace/wxue_string.h"  // wxue::string

using namespace code;
using namespace GenEnum;

JuliaCodeGenerator::JuliaCodeGenerator(Node* form_node) :
    BaseCodeGenerator(GEN_LANG_JULIA, form_node)
{
}

void JuliaCodeGenerator::GenerateClass(GenLang language, PANEL_PAGE panel_type,
                                       wxProgressDialog* /* progress */)
{
    m_language = language;
    m_panel_type = panel_type;
    ASSERT(m_language == GEN_LANG_JULIA);
    Code code(m_form_node, m_language);

    if (m_header)
    {
        m_header->Clear();
    }
    m_source->Clear();
    m_source->SetTabToSpaces(GetLanguageTraits(m_language)->indent_size);
    m_source->SetLastLineBlank();

    // File header comment
    m_source->writeLine("# This file was generated by wxUiEditor. Do not edit.");
    m_source->writeLine();

    if (m_form_node->is_Gen(gen_Images))
    {
        return;
    }

    // Module imports
    m_source->writeLine("using WxWidgets");
    m_source->writeLine();

    wxue::string class_name(m_form_node->as_string(prop_class_name));

    // Julia uses a function to create the form (no classes needed)
    m_source->writeLine(wxue::string("function create_") << class_name << "(parent)");
    m_source->Indent();

    GenerateConstructionCode(code);

    m_source->Unindent();
    m_source->writeLine("end");

    // Reset indentation
    m_source->ResetIndent();
}

auto JuliaCodeGenerator::GenerateConstructionCode(Code& code) -> void
{
    auto* generator = m_form_node->get_NodeDeclaration()->get_Generator();
    code.clear();
    if (generator->ConstructionCode(code))
    {
        m_source->writeLine(code);
        m_source->writeLine();
    }

    code.clear();
    if (generator->SettingsCode(code))
    {
        if (code.size())
        {
            m_source->writeLine(code);
            m_source->writeLine();
        }
    }

    if (m_form_node->get_PropPtr(prop_window_extra_style))
    {
        code.clear();
        code.GenWindowSettings();
        if (code.size())
        {
            m_source->writeLine(code);
        }
    }

    m_source->SetLastLineBlank();
    for (const auto& child: m_form_node->get_ChildNodePtrs())
    {
        if (child->is_Gen(gen_wxContextMenuEvent))
        {
            continue;
        }
        GenConstruction(child.get());
    }

    code.clear();
    if (generator->AfterChildrenCode(code))
    {
        if (code.size())
        {
            m_source->writeLine();
            m_source->writeLine(code);
        }
    }
}
