/////////////////////////////////////////////////////////////////////////////
// Purpose:   Generate Fortran code via kwxFFI
// Author:    Ralph Walden
// Copyright: Copyright (c) 2026 KeyWorks Software (Ralph Walden)
// License:   Apache License -- see ../../LICENSE
/////////////////////////////////////////////////////////////////////////////

#include "gen_fortran.h"

#include "base_generator.h"   // BaseGenerator -- Base widget generator class
#include "code.h"             // Code -- Helper class for generating code
#include "gen_common.h"       // Common component functions
#include "node.h"             // Node class
#include "project_handler.h"  // ProjectHandler class
#include "write_code.h"       // Write code to Scintilla or file

#include "wxue_namespace/wxue_string.h"  // wxue::string

using namespace code;
using namespace GenEnum;

FortranCodeGenerator::FortranCodeGenerator(Node* form_node) :
    BaseCodeGenerator(GEN_LANG_FORTRAN, form_node)
{
}

void FortranCodeGenerator::GenerateClass(GenLang language, PANEL_PAGE panel_type,
                                         wxProgressDialog* /* progress */)
{
    m_language = language;
    m_panel_type = panel_type;
    ASSERT(m_language == GEN_LANG_FORTRAN);
    Code code(m_form_node, m_language);

    if (m_header)
    {
        m_header->Clear();
    }
    m_source->Clear();
    m_source->SetTabToSpaces(GetLanguageTraits(m_language)->indent_size);
    m_source->SetLastLineBlank();

    // File header comment
    m_source->writeLine("! This file was generated by wxUiEditor. Do not edit.");
    m_source->writeLine();

    if (m_form_node->is_Gen(gen_Images))
    {
        return;
    }

    wxue::string class_name(m_form_node->as_string(prop_class_name));

    // Module declaration
    m_source->writeLine(wxue::string("module ") << class_name << "_mod");
    m_source->Indent();
    m_source->writeLine("use, intrinsic :: iso_c_binding");
    m_source->writeLine("use kwx_types");
    m_source->writeLine("use kwx_constants");
    m_source->writeLine("implicit none");
    m_source->writeLine();
    m_source->Unindent();
    m_source->writeLine("contains");
    m_source->writeLine();
    m_source->Indent();

    // Subroutine wrapping the form construction
    m_source->writeLine(wxue::string("subroutine create_") << class_name << "(parent)");
    m_source->Indent();
    m_source->writeLine("type(c_ptr), intent(in) :: parent");
    m_source->writeLine();

    GenerateConstructionCode(code);

    m_source->Unindent();
    m_source->writeLine(wxue::string("end subroutine create_") << class_name);

    // Close module
    m_source->ResetIndent();
    m_source->writeLine();
    m_source->writeLine(wxue::string("end module ") << class_name << "_mod");
}

auto FortranCodeGenerator::GenerateConstructionCode(Code& code) -> void
{
    auto* generator = m_form_node->get_NodeDeclaration()->get_Generator();
    code.clear();
    if (generator->ConstructionCode(code))
    {
        m_source->writeLine(code);
        m_source->writeLine();
    }

    code.clear();
    if (generator->SettingsCode(code))
    {
        if (code.size())
        {
            m_source->writeLine(code);
            m_source->writeLine();
        }
    }

    if (m_form_node->get_PropPtr(prop_window_extra_style))
    {
        code.clear();
        code.GenWindowSettings();
        if (code.size())
        {
            m_source->writeLine(code);
        }
    }

    m_source->SetLastLineBlank();
    for (const auto& child: m_form_node->get_ChildNodePtrs())
    {
        if (child->is_Gen(gen_wxContextMenuEvent))
        {
            continue;
        }
        GenConstruction(child.get());
    }

    code.clear();
    if (generator->AfterChildrenCode(code))
    {
        if (code.size())
        {
            m_source->writeLine();
            m_source->writeLine(code);
        }
    }
}
