///////////////////////////////////////////////////////////////////////////////
// <auto-generated>
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT ANYTHING IN THIS FILE UNTIL AFTER THE </auto-generated> MARKER
// All changes before that marker will be lost if the code is re-generated.
///////////////////////////////////////////////////////////////////////////////

// clang-format off
// NOLINTBEGIN
// cppcheck-suppress-begin *

#include <wx/sizer.h>

#include "code_compare_base.h"

#include "../internal/WinMerge.xpm"

bool CodeCompareBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    // Scaling of pos and size are handled after the dialog
    // has been created and controls added.
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
    {
        return false;
    }

    auto* dlg_sizer = new wxBoxSizer(wxVERTICAL);

    auto* box_sizer = new wxBoxSizer(wxVERTICAL);

    auto* staticText_2 = new wxStaticText(this, wxID_ANY,
        "Select the Project, a Folder, or a Form and this dialog will list the names of any classes that have changed from what you have on disk. Click the Diff button to see details of what has changed.");
    staticText_2->Wrap(320);
    box_sizer->Add(staticText_2, wxSizerFlags().Border(wxLEFT|wxRIGHT|wxTOP, wxSizerFlags::GetDefaultBorder()));

    auto* grid_sizer = new wxGridSizer(3, 0, 0);

    m_radio_cplusplus = new wxRadioButton(this, wxID_ANY, "&C++", wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    grid_sizer->Add(m_radio_cplusplus, wxSizerFlags().Border(wxALL));

    m_radio_python = new wxRadioButton(this, wxID_ANY, "&Python");
    grid_sizer->Add(m_radio_python, wxSizerFlags().Border(wxALL));

    m_radio_ruby = new wxRadioButton(this, wxID_ANY, "&Ruby");
    grid_sizer->Add(m_radio_ruby, wxSizerFlags().Border(wxALL));

    m_radio_perl = new wxRadioButton(this, wxID_ANY, "&Perl");
    grid_sizer->Add(m_radio_perl, wxSizerFlags().Border(wxALL));

    m_radio_xrc = new wxRadioButton(this, wxID_ANY, "&XRC");
    grid_sizer->Add(m_radio_xrc, wxSizerFlags().Border(wxALL));

    box_sizer->Add(grid_sizer, wxSizerFlags().Center().Border(wxALL));

    box_sizer->AddSpacer(15);

    m_changed_classes_text = new wxStaticText(this, wxID_ANY, "C&hanged Classes:");
    box_sizer->Add(m_changed_classes_text, wxSizerFlags().Border(wxALL));

    m_list_changes = new wxListBox(this, wxID_ANY);
    m_list_changes->SetMinSize(FromDIP(wxSize(250, 200)));
    box_sizer->Add(m_list_changes, wxSizerFlags().Expand().Border(wxALL));

    m_diff_results = new wxStaticText(this, wxID_ANY, "Diff Results");
    box_sizer->Add(m_diff_results, wxSizerFlags().Border(wxALL));

    m_btn = new wxButton(this, wxID_ANY, "View &Diffs...");
        m_btn->SetBitmap(wxBitmapBundle::FromBitmap(wxImage(WinMerge_xpm)));
    m_btn->Enable(false);
    box_sizer->Add(m_btn, wxSizerFlags().Border(wxALL));

    dlg_sizer->Add(box_sizer, wxSizerFlags().Border(wxALL));

    auto* stdBtn = CreateStdDialogButtonSizer(wxCLOSE|wxNO_DEFAULT);
    stdBtn->GetCancelButton()->SetDefault();
    dlg_sizer->Add(CreateSeparatedSizer(stdBtn), wxSizerFlags().Expand().Border(wxALL));

    if (pos != wxDefaultPosition)
    {
        // Now that the dialog is created, set the scaled position
        SetPosition(FromDIP(pos));
    }
    if (size == wxDefaultSize)
    {
        // If default size let the sizer set the dialog's size
        // so that it is large enough to fit it's child controls.
        SetSizerAndFit(dlg_sizer);
    }
    else
    {
        SetSizer(dlg_sizer);
        if (size.x == wxDefaultCoord || size.y == wxDefaultCoord)
        {
            // Use the sizer to calculate the missing dimension
            Fit();
        }
        SetSize(FromDIP(size));
        Layout();
    }
    Centre(wxBOTH);

    // Event handlers
    m_btn->Bind(wxEVT_BUTTON, &CodeCompareBase::OnDiff, this);
    Bind(wxEVT_INIT_DIALOG, &CodeCompareBase::OnInit, this);
    m_radio_cplusplus->Bind(wxEVT_RADIOBUTTON, &CodeCompareBase::OnCPlusPlus, this);
    m_radio_perl->Bind(wxEVT_RADIOBUTTON, &CodeCompareBase::OnPerl, this);
    m_radio_python->Bind(wxEVT_RADIOBUTTON, &CodeCompareBase::OnPython, this);
    m_radio_ruby->Bind(wxEVT_RADIOBUTTON, &CodeCompareBase::OnRuby, this);
    m_radio_xrc->Bind(wxEVT_RADIOBUTTON, &CodeCompareBase::OnXRC, this);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// NOLINTEND
// cppcheck-suppress-end *
// ***********************************************
// </auto-generated>
