///////////////////////////////////////////////////////////////////////////////
// <auto-generated>
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT ANYTHING IN THIS FILE UNTIL AFTER THE </auto-generated> MARKER
// All changes before that marker will be lost if the code is re-generated.
///////////////////////////////////////////////////////////////////////////////

// clang-format off
// NOLINTBEGIN
// cppcheck-suppress-begin *

#include <wx/button.h>
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/stattext.h>
#include <wx/valgen.h>

#include "generate_xrc_dlg_base.h"

bool GenerateXrcDlgBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    // Scaling of pos and size are handled after the dialog
    // has been created and controls added.
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
    {
        return false;
    }

    auto* dlg_sizer = new wxBoxSizer(wxVERTICAL);

    m_radio_combined = new wxRadioButton(this, wxID_ANY, "Combined File", wxDefaultPosition, wxDefaultSize, wxRB_SINGLE);
    m_radio_combined->SetValidator(wxGenericValidator(&m_create_combined));

    m_combined_box = new wxStaticBoxSizer(
#if defined(__WXOSX__)
        wxVERTICAL, this, "Combined File");
#else
        new wxStaticBox(this, wxID_ANY, m_radio_combined), wxVERTICAL);
#endif

    m_filePicker = new wxFilePickerCtrl(m_combined_box->GetStaticBox(), wxID_ANY, wxEmptyString, "Combined XRC File", "*.xrc",
        wxDefaultPosition, wxDefaultSize, wxFLP_USE_TEXTCTRL|wxFLP_SAVE);
    m_filePicker->SetMinSize(FromDIP(wxSize(240, -1)));
    m_combined_box->Add(m_filePicker, wxSizerFlags(1).Expand().Border(wxALL));

    dlg_sizer->Add(m_combined_box, wxSizerFlags().Expand().Border(wxALL));

    m_radio_separate = new wxRadioButton(this, wxID_ANY, "Separate Files", wxDefaultPosition, wxDefaultSize, wxRB_SINGLE);
    m_separate_box = new wxStaticBoxSizer(
#if defined(__WXOSX__)
        wxVERTICAL, this, "Separate Files");
#else
        new wxStaticBox(this, wxID_ANY, m_radio_separate), wxVERTICAL);
#endif

    auto* staticText = new wxStaticText(m_separate_box->GetStaticBox(), wxID_ANY,
        "Forms not listed do not have xrc_file set.");
    m_separate_box->Add(staticText, wxSizerFlags().Border(wxALL));

    m_listbox = new wxListBox(m_separate_box->GetStaticBox(), wxID_ANY);
    m_listbox->SetMinSize(FromDIP(wxSize(-1, 125)));
    m_separate_box->Add(m_listbox, wxSizerFlags(1).Expand().Border(wxALL));

    dlg_sizer->Add(m_separate_box, wxSizerFlags().Expand().Border(wxALL));

    auto* stdBtn = new wxStdDialogButtonSizer();
    stdBtn->AddButton(new wxButton(this, wxID_SAVE));
    stdBtn->AddButton(new wxButton(this, wxID_CANCEL));
    stdBtn->Realize();
    dlg_sizer->Add(CreateSeparatedSizer(stdBtn), wxSizerFlags().Expand().Border(wxALL));

    if (pos != wxDefaultPosition)
    {
        // Now that the dialog is created, set the scaled position
        SetPosition(FromDIP(pos));
    }
    if (size == wxDefaultSize)
    {
        // If default size let the sizer set the dialog's size
        // so that it is large enough to fit it's child controls.
        SetSizerAndFit(dlg_sizer);
    }
    else
    {
        SetSizer(dlg_sizer);
        if (size.x == wxDefaultCoord || size.y == wxDefaultCoord)
        {
            // Use the sizer to calculate the missing dimension
            Fit();
        }
        SetSize(FromDIP(size));
        Layout();
    }
    Centre(wxBOTH);

    wxPersistentRegisterAndRestore(this, "GenerateXrcDlgBase");

    // Event handlers
    Bind(wxEVT_BUTTON, &GenerateXrcDlgBase::OnSave, this, wxID_SAVE);
    m_filePicker->Bind(wxEVT_FILEPICKER_CHANGED, &GenerateXrcDlgBase::OnCombinedFilenameChanged, this);
    Bind(wxEVT_INIT_DIALOG, &GenerateXrcDlgBase::OnInit, this);
    m_radio_combined->Bind(wxEVT_RADIOBUTTON, &GenerateXrcDlgBase::OnCombinedFile, this);
    m_radio_separate->Bind(wxEVT_RADIOBUTTON, &GenerateXrcDlgBase::OnSeparateFiles, this);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// NOLINTEND
// cppcheck-suppress-end *
// ***********************************************
// </auto-generated>
