////////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////////

#include <wx/button.h>
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/stattext.h>
#include <wx/valgen.h>

#include "generate_xrc_dlg_base.h"

bool GenerateXrcDlgBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
        const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;

    auto* dlg_sizer = new wxBoxSizer(wxVERTICAL);

    m_radio_combined = new wxRadioButton(this, wxID_ANY, "Combined File");
    m_radio_combined->SetValidator(wxGenericValidator(&m_create_combined));
    m_combined_box = new wxStaticBoxSizer(new wxStaticBox(this, wxID_ANY,m_radio_combined), wxVERTICAL);
    dlg_sizer->Add(m_combined_box, wxSizerFlags().Expand().Border(wxALL));

    m_filePicker = new wxFilePickerCtrl(m_combined_box->GetStaticBox(), wxID_ANY, wxEmptyString, 
        "Combined XRC File", 
        "*.xrc", wxDefaultPosition, wxDefaultSize,
        wxFLP_USE_TEXTCTRL|wxFLP_SAVE);
    m_filePicker->SetMinSize(ConvertDialogToPixels(wxSize(120, -1)));
    m_combined_box->Add(m_filePicker, wxSizerFlags(1).Expand().Border(wxALL));

    m_radio_separate = new wxRadioButton(this, wxID_ANY, "Separate Files");
    m_separate_box = new wxStaticBoxSizer(new wxStaticBox(this, wxID_ANY,m_radio_separate), wxVERTICAL);
    dlg_sizer->Add(m_separate_box, wxSizerFlags().Expand().Border(wxALL));

    auto* staticText = new wxStaticText(m_separate_box->GetStaticBox(), wxID_ANY, "Forms not listed do not have xrc_file set.");
    m_separate_box->Add(staticText, wxSizerFlags().Border(wxALL));

    m_listbox = new wxListBox(m_separate_box->GetStaticBox(), wxID_ANY);
    m_listbox->SetMinSize(ConvertDialogToPixels(wxSize(-1, 50)));
    m_separate_box->Add(m_listbox, wxSizerFlags(1).Expand().Border(wxALL));

    auto* stdBtn = new wxStdDialogButtonSizer();
    stdBtn->AddButton(new wxButton(this, wxID_SAVE));
    stdBtn->AddButton(new wxButton(this, wxID_CANCEL));
    stdBtn->Realize();
    dlg_sizer->Add(CreateSeparatedSizer(stdBtn), wxSizerFlags().Expand().Border(wxALL));

    SetSizerAndFit(dlg_sizer);
    Centre(wxBOTH);

    wxPersistentRegisterAndRestore(this, "GenerateXrcDlgBase");

    // Event handlers
    Bind(wxEVT_INIT_DIALOG, &GenerateXrcDlgBase::OnInit, this);
    m_radio_combined->Bind(wxEVT_RADIOBUTTON, &GenerateXrcDlgBase::OnCombinedFile, this);
    m_filePicker->Bind(wxEVT_FILEPICKER_CHANGED, &GenerateXrcDlgBase::OnCombinedFilenameChanged, this);
    m_radio_separate->Bind(wxEVT_RADIOBUTTON, &GenerateXrcDlgBase::OnSeparateFiles, this);
    Bind(wxEVT_BUTTON, &GenerateXrcDlgBase::OnSave, this, wxID_SAVE);

    return true;
}
