///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#include <wx/artprov.h>

#include "../panels/nav_panel.h"
#include "ui_images.h"

#include "mainframe_base.h"

#include "mainframe.h"
#include "project_handler.h"

#include <wx/mstream.h>  // memory stream classes
#include <wx/zstream.h>  // zlib stream classes

#include <memory>  // for std::make_unique

// Convert compressed SVG string into a wxBitmapBundle
#ifdef __cpp_inline_variables
inline wxBitmapBundle wxueBundleSVG(const unsigned char* data,
    size_t size_data, size_t size_svg, wxSize def_size)
#else
static wxBitmapBundle wxueBundleSVG(const unsigned char* data,
    size_t size_data, size_t size_svg, wxSize def_size)
#endif
{
    auto str = std::make_unique<char[]>(size_svg);
    wxMemoryInputStream stream_in(data, size_data);
    wxZlibInputStream zlib_strm(stream_in);
    zlib_strm.Read(str.get(), size_svg);
    return wxBitmapBundle::FromSVG(str.get(), def_size);
};

namespace wxue_img
{
    extern const unsigned char expand_svg[648];  // ../art_src/expand.svg
    extern const unsigned char generate_svg[2435];  // ../art_src/generate.svg
    extern const unsigned char hidden_svg[1993];  // ../art_src/hidden.svg
    extern const unsigned char magnify_svg[4117];  // ../art_src/magnify.svg
    extern const unsigned char save_svg[1064];  // ../art_src/save.svg
    extern const unsigned char wxlogo_svg[1476];  // ../art_src/wxlogo.svg
    extern const unsigned char xrc_preview_svg[689];  // ../art_src/xrc_preview.svg
}

bool MainFrameBase::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{

    if (!wxImage::FindHandler(wxBITMAP_TYPE_PNG))
        wxImage::AddHandler(new wxPNGHandler);

    if (!wxFrame::Create(parent, id, title, pos, size, style, name))
        return false;
    SetMinSize(wxSize(800, 800));

    m_mainframe_sizer = new wxBoxSizer(wxVERTICAL);

    m_toolbar = new wxToolBar(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTB_FLAT|wxTB_HORIZONTAL|wxTB_NODIVIDER);

    m_toolbar->AddSeparator();
    m_toolbar->AddTool(id_DifferentProject, "Different Project...",
        wxue_img::bundle_wxUiEditor_svg(FromDIP(24), FromDIP(24)), "Different Project... (Ctrl+D)");

    m_toolbar->AddTool(wxID_SAVE, "Save",
        wxueBundleSVG(wxue_img::save_svg, 1064, 2928, FromDIP(wxSize(24, 24))), "Save current project");

    m_toolbar->AddTool(id_GenerateCode, "Generate...",
        wxueBundleSVG(wxue_img::generate_svg, 2435, 7248, FromDIP(wxSize(24, 24))), "Generate code...");

    m_toolbar->AddSeparator();
    m_toolbar->AddTool(wxID_UNDO, wxEmptyString,
        wxue_img::bundle_undo_svg(FromDIP(24), FromDIP(24)), "Undo");

    m_toolbar->AddTool(wxID_REDO, wxEmptyString,
        wxue_img::bundle_redo_svg(FromDIP(24), FromDIP(24)), "Redo");

    m_toolbar->AddSeparator();
    m_toolbar->AddTool(wxID_CUT, wxEmptyString, wxArtProvider::GetBitmapBundle(wxART_CUT, wxART_TOOLBAR), "Cut");

    m_toolbar->AddTool(wxID_COPY, wxEmptyString, wxArtProvider::GetBitmapBundle(wxART_COPY, wxART_TOOLBAR), "Copy");

    m_toolbar->AddTool(wxID_PASTE, wxEmptyString, wxArtProvider::GetBitmapBundle(wxART_PASTE, wxART_TOOLBAR), "Paste");

    m_toolbar->AddTool(wxID_DELETE, wxEmptyString, wxArtProvider::GetBitmapBundle(wxART_DELETE, wxART_TOOLBAR),
        "Delete selected object without using clipboard.");

    m_toolbar->AddSeparator();
    m_toolbar->AddTool(id_AlignLeft, wxEmptyString,
        wxue_img::bundle_alignleft_svg(FromDIP(24), FromDIP(24)), "Align left", wxITEM_CHECK);

    m_toolbar->AddTool(id_AlignCenterHorizontal, wxEmptyString,
        wxue_img::bundle_aligncenter_svg(FromDIP(24), FromDIP(24)), "Center horizontally", wxITEM_CHECK);

    m_toolbar->AddTool(id_AlignRight, wxEmptyString,
        wxue_img::bundle_alignright_svg(FromDIP(24), FromDIP(24)), "Align right", wxITEM_CHECK);

    m_toolbar->AddSeparator();
    m_toolbar->AddTool(id_AlignTop, wxEmptyString,
        wxue_img::bundle_aligntop_svg(FromDIP(24), FromDIP(24)), "Align top", wxITEM_CHECK);

    m_toolbar->AddTool(id_AlignCenterVertical, wxEmptyString,
        wxue_img::bundle_alignvertcenter_svg(FromDIP(24), FromDIP(24)), "Center vertically", wxITEM_CHECK);

    m_toolbar->AddTool(id_AlignBottom, wxEmptyString,
        wxue_img::bundle_alignbottom_svg(FromDIP(24), FromDIP(24)), "Align bottom", wxITEM_CHECK);

    m_toolbar->AddSeparator();
    m_toolbar->AddTool(id_BorderLeft, wxEmptyString,
        wxue_img::bundle_left_svg(FromDIP(24), FromDIP(24)), "Left border", wxITEM_CHECK);

    m_toolbar->AddTool(id_BorderRight, wxEmptyString,
        wxue_img::bundle_right_svg(FromDIP(24), FromDIP(24)), "Right border", wxITEM_CHECK);

    m_toolbar->AddTool(id_BorderTop, wxEmptyString,
        wxue_img::bundle_top_svg(FromDIP(24), FromDIP(24)), "Top border", wxITEM_CHECK);

    m_toolbar->AddTool(id_BorderBottom, wxEmptyString,
        wxue_img::bundle_bottom_svg(FromDIP(24), FromDIP(24)), "Bottom border", wxITEM_CHECK);

    m_toolbar->AddSeparator();
    m_toolbar->AddTool(id_Expand, wxEmptyString,
        wxueBundleSVG(wxue_img::expand_svg, 648, 1215, FromDIP(wxSize(24, 24))), "Expand to fill the space", wxITEM_CHECK);

    m_toolbar->AddSeparator();
    m_toolbar->AddTool(id_ShowHidden, wxEmptyString,
        wxueBundleSVG(wxue_img::hidden_svg, 1993, 5117, FromDIP(wxSize(24, 24))), "Show hidden controls in Mockup panel",
        wxITEM_CHECK);

    m_toolbar->AddTool(id_Magnify, wxEmptyString,
        wxueBundleSVG(wxue_img::magnify_svg, 4117, 13046, FromDIP(wxSize(24, 24))), "Magnify the size of the Mockup window",
        wxITEM_CHECK);

    m_toolbar->AddTool(id_PreviewForm, "Preview Form...",
        wxueBundleSVG(wxue_img::xrc_preview_svg, 689, 1806, FromDIP(wxSize(24, 24))), "Preview form using XRC and/or C++",
        wxITEM_CHECK);

    m_toolbar->Realize();
    m_mainframe_sizer->Add(m_toolbar, wxSizerFlags().Expand());

    m_MainSplitter = new wxSplitterWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_LIVE_UPDATE);
    m_MainSplitter->SetSashGravity(0.0);
    m_MainSplitter->SetMinimumPaneSize(2);
    m_mainframe_sizer->Add(m_MainSplitter, wxSizerFlags(1).Expand());

    m_nav_panel = new NavigationPanel(m_MainSplitter);

    m_panel_right = new wxPanel(m_MainSplitter);

    m_right_panel_sizer = new wxBoxSizer(wxVERTICAL);
    m_panel_right->SetSizerAndFit(m_right_panel_sizer);
    m_MainSplitter->SplitVertically(m_nav_panel, m_panel_right);
    SetSizer(m_mainframe_sizer);

    m_menubar = new wxMenuBar();

    m_menuFile = new wxMenu();
    auto* menuItem3 = new wxMenuItem(m_menuFile, id_DifferentProject, "&Different Project...\tCtrl+D", "Open a project",
        wxITEM_NORMAL);
    menuItem3->SetBitmap(wxue_img::bundle_wxUiEditor_svg(16, 16));
    m_menuFile->Append(menuItem3);
    auto* menuItem = new wxMenuItem(m_menuFile, id_NewProject, "&New Project...\tCtrl+N", "Create an empty project",
        wxITEM_NORMAL);
    menuItem->SetBitmap(wxue_img::bundle_new_project_svg(16, 16));
    m_menuFile->Append(menuItem);
    auto* menuItem2 = new wxMenuItem(m_menuFile, id_OpenProject, "&Open Project...\tCtrl+O", "Open a project", wxITEM_NORMAL);
    menuItem2->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_FILE_OPEN, wxART_MENU));

    m_menuFile->Append(menuItem2);

    m_submenu_recent = new wxMenu();
    m_menuFile->AppendSubMenu(m_submenu_recent, "Open &Recent");
    auto* menu_import = new wxMenuItem(m_menuFile, wxID_ANY, "&Import Project...");
    menu_import->SetBitmap(wxue_img::bundle_import_svg(16, 16));
    m_menuFile->Append(menu_import);
    m_menuFile->AppendSeparator();
    auto* menu_item = new wxMenuItem(m_menuFile, wxID_SAVE, "&Save\tCtrl+S", "Save current project", wxITEM_NORMAL);
    menu_item->SetBitmap(wxueBundleSVG(wxue_img::save_svg, 1064, 2928, wxSize(16, 16)));

    m_menuFile->Append(menu_item);
    auto* menu_item2 = new wxMenuItem(m_menuFile, id_SaveProjectAs, "Save &As...\tCtrl-Shift+S",
        "Save current project to a different filename", wxITEM_NORMAL);
    menu_item2->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_FILE_SAVE_AS, wxART_MENU));

    m_menuFile->Append(menu_item2);
    m_menuFile->AppendSeparator();

    auto* submenu = new wxMenu();
    auto* menu_item_7 = new wxMenuItem(submenu, id_AppendCrafter, "wxCrafter Project...",
        "Append wxCrafter project into current project", wxITEM_NORMAL);
    submenu->Append(menu_item_7);
    auto* menu_item_1 = new wxMenuItem(submenu, id_AppendFormBuilder, "wxFormBuilder Project...",
        "Append wxFormBuilder project into current project", wxITEM_NORMAL);
    submenu->Append(menu_item_1);
    auto* menu_item_2 = new wxMenuItem(submenu, id_AppendGlade, "wxGlade Project...",
        "Append wxGlade project into current project", wxITEM_NORMAL);
    submenu->Append(menu_item_2);
    auto* menu_item_3 = new wxMenuItem(submenu, id_AppendSmith, "wxSmith Project...",
        "Append wxSmith project into current project", wxITEM_NORMAL);
    submenu->Append(menu_item_3);
    auto* menu_item_11 = new wxMenuItem(submenu, id_AppendCrafter, "DialogBlocks Project...",
        "Append wxCrafter project into current project", wxITEM_NORMAL);
    submenu->Append(menu_item_11);
    auto* menu_item_5 = new wxMenuItem(submenu, id_AppendWinRes, "Windows Resource...",
        "Append Windows Resource into current project", wxITEM_NORMAL);
    submenu->Append(menu_item_5);
    auto* menu_item_4 = new wxMenuItem(submenu, id_AppendXRC, "XRC File...", "Append XRC project into current project",
        wxITEM_NORMAL);
    submenu->Append(menu_item_4);
    m_menuFile->AppendSubMenu(submenu, "&Append");
    m_menuFile->AppendSeparator();
    auto* menu_preferences = new wxMenuItem(m_menuFile, id_PreferencesDlg, "&Preferences...", "Various global preferences",
        wxITEM_NORMAL);
    m_menuFile->Append(menu_preferences);
    m_menuFile->AppendSeparator();
    auto* menu_quit = new wxMenuItem(m_menuFile, wxID_EXIT, wxEmptyString);
    menu_quit->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_QUIT, wxART_MENU));

    m_menuFile->Append(menu_quit);
    m_menubar->Append(m_menuFile, "&File");

    m_menuEdit = new wxMenu();
    auto* menu_undo = new wxMenuItem(m_menuEdit, wxID_UNDO, wxEmptyString);
    menu_undo->SetBitmap(wxue_img::bundle_undo_svg(16, 16));
    m_menuEdit->Append(menu_undo);
    auto* menu_redo = new wxMenuItem(m_menuEdit, wxID_REDO, wxEmptyString);
    menu_redo->SetBitmap(wxue_img::bundle_redo_svg(16, 16));
    m_menuEdit->Append(menu_redo);
    m_menuEdit->AppendSeparator();
    auto* menu_cut = new wxMenuItem(m_menuEdit, wxID_CUT, wxEmptyString);
    menu_cut->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_CUT, wxART_MENU));

    m_menuEdit->Append(menu_cut);
    auto* menu_copy = new wxMenuItem(m_menuEdit, wxID_COPY, wxEmptyString);
    menu_copy->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_COPY, wxART_MENU));

    m_menuEdit->Append(menu_copy);
    auto* menu_paste = new wxMenuItem(m_menuEdit, wxID_PASTE, wxEmptyString);
    menu_paste->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_PASTE, wxART_MENU));

    m_menuEdit->Append(menu_paste);
    auto* menu_delete = new wxMenuItem(m_menuEdit, wxID_DELETE, wxEmptyString,
        "Delete selected object without using clipboard.", wxITEM_NORMAL);
    menu_delete->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_DELETE, wxART_MENU));

    m_menuEdit->Append(menu_delete);
    auto* menu_duplicate = new wxMenuItem(m_menuEdit, wxID_ANY, "Duplicate",
        "Delete selected object without using clipboard.", wxITEM_NORMAL);
    m_menuEdit->Append(menu_duplicate);
    m_menuEdit->AppendSeparator();
    auto* menu_find = new wxMenuItem(m_menuEdit, wxID_FIND, wxEmptyString, "Find text in the active code viewer.",
        wxITEM_NORMAL);
    menu_find->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_FIND, wxART_MENU));

    m_menuEdit->Append(menu_find);
    auto* menu_insert_widget = new wxMenuItem(m_menuEdit, id_insert_widget, "&Insert widget...",
        "Find text in the active code viewer.", wxITEM_NORMAL);
    menu_insert_widget->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_EDIT, wxART_MENU));

    m_menuEdit->Append(menu_insert_widget);
    m_menuEdit->AppendSeparator();

    auto* submenu3 = new wxMenu();
    auto* menu_item4 = new wxMenuItem(submenu3, id_MoveUp, "Up\tAlt+Up", "Moves selected item up", wxITEM_NORMAL);
    menu_item4->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_GO_UP, wxART_MENU));

    submenu3->Append(menu_item4);
    auto* menu_item5 = new wxMenuItem(submenu3, id_MoveDown, "Down\tAlt+Down", "Moves selected item down", wxITEM_NORMAL);
    menu_item5->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_GO_DOWN, wxART_MENU));

    submenu3->Append(menu_item5);
    auto* menu_item6 = new wxMenuItem(submenu3, id_MoveLeft, "Left\tAlt+Left", "Moves selected item left", wxITEM_NORMAL);
    menu_item6->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_GO_BACK, wxART_MENU));

    submenu3->Append(menu_item6);
    auto* menu_item7 = new wxMenuItem(submenu3, id_MoveRight, "Right\tAlt+Right", "Moves selected item right", wxITEM_NORMAL);
    menu_item7->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_GO_FORWARD, wxART_MENU));

    submenu3->Append(menu_item7);
    m_menuEdit->AppendSubMenu(submenu3, "Move");

    auto* submenu2 = new wxMenu();
    auto* menu_item8 = new wxMenuItem(submenu2, id_AlignLeft, "&Left\tAlt+Shift+Left", "Align selected item to the left",
        wxITEM_CHECK);
    menu_item8->SetBitmap(wxue_img::bundle_alignleft_svg(16, 16));
    submenu2->Append(menu_item8);
    auto* menu_item10 = new wxMenuItem(submenu2, id_AlignCenterHorizontal, "Center &Horizontal\tAlt+Shift+H",
        "Align selected item to the center horizontally", wxITEM_CHECK);
    menu_item10->SetBitmap(wxue_img::bundle_aligncenter_svg(16, 16));
    submenu2->Append(menu_item10);
    menu_item10->Check();
    auto* menu_item9 = new wxMenuItem(submenu2, id_AlignRight, "&Right\tAlt+Shift+Right", "Align selected item to the right",
        wxITEM_CHECK);
    menu_item9->SetBitmap(wxue_img::bundle_alignright_svg(16, 16));
    submenu2->Append(menu_item9);
    submenu2->AppendSeparator();
    auto* menu_item11 = new wxMenuItem(submenu2, id_AlignTop, "&Top\tAlt+Shift+Up", "Align selected item to the top",
        wxITEM_CHECK);
    menu_item11->SetBitmap(wxue_img::bundle_aligntop_svg(16, 16));
    submenu2->Append(menu_item11);
    auto* menu_item12 = new wxMenuItem(submenu2, id_AlignCenterVertical, "Center &Vertical\tAlt+Shift+V",
        "Align selected item to the center vertically", wxITEM_CHECK);
    menu_item12->SetBitmap(wxue_img::bundle_alignvertcenter_svg(16, 16));
    submenu2->Append(menu_item12);
    auto* menu_item13 = new wxMenuItem(submenu2, id_AlignBottom, "&Bottom\tAlt+Shift+Down",
        "Align selected item to the bottom", wxITEM_CHECK);
    menu_item13->SetBitmap(wxue_img::bundle_alignright_svg(16, 16));
    submenu2->Append(menu_item13);
    m_menuEdit->AppendSubMenu(submenu2, "Align");

    auto* submenu4 = new wxMenu();
    auto* menu_item14 = new wxMenuItem(submenu4, id_BorderLeft, "&Left", "Toggle border on the left side of the item",
        wxITEM_CHECK);
    menu_item14->SetBitmap(wxue_img::bundle_left_svg(16, 16));
    submenu4->Append(menu_item14);
    auto* menu_item15 = new wxMenuItem(submenu4, id_BorderRight, "&Right", "Toggle border on the right side of the item",
        wxITEM_CHECK);
    menu_item15->SetBitmap(wxue_img::bundle_right_svg(16, 16));
    submenu4->Append(menu_item15);
    auto* menu_item16 = new wxMenuItem(submenu4, id_BorderTop, "&Top", "Toggle border on the top side of the item",
        wxITEM_CHECK);
    menu_item16->SetBitmap(wxue_img::bundle_top_svg(16, 16));
    submenu4->Append(menu_item16);
    auto* menu_item17 = new wxMenuItem(submenu4, id_BorderBottom, "&Bottom", "Toggle border on the bottom side of the item",
        wxITEM_CHECK);
    menu_item17->SetBitmap(wxue_img::bundle_bottom_svg(16, 16));
    submenu4->Append(menu_item17);
    m_menuEdit->AppendSubMenu(submenu4, "Borders");
    auto* menu_item18 = new wxMenuItem(m_menuEdit, id_Expand, "&Expand\tAlt+E", "Toggle the wxEXPAND flag", wxITEM_CHECK);
    menu_item18->SetBitmap(wxueBundleSVG(wxue_img::expand_svg, 648, 1215, wxSize(16, 16)));

    m_menuEdit->Append(menu_item18);
    m_menubar->Append(m_menuEdit, "&Edit");

    m_menuTools = new wxMenu();
    auto* menu_item19 = new wxMenuItem(m_menuTools, id_GenerateCode, "Generate &Code...",
        "Generates code for the selected language", wxITEM_NORMAL);
    menu_item19->SetBitmap(wxueBundleSVG(wxue_img::generate_svg, 2435, 7248, wxSize(16, 16)));

    m_menuTools->Append(menu_item19);
    m_mi_preview = new wxMenuItem(m_menuTools, id_PreviewForm, "&Preview Form...\tF5", "Preview form using XRC and/or C++",
        wxITEM_NORMAL);
    m_mi_preview->SetBitmap(wxueBundleSVG(wxue_img::xrc_preview_svg, 689, 1806, wxSize(16, 16)));

    m_menuTools->Append(m_mi_preview);
    auto* menu_item_8 = new wxMenuItem(m_menuTools, wxID_ANY, "&Global Edit Custom IDs...");
    m_menuTools->Append(menu_item_8);
    m_menubar->Append(m_menuTools, "&Tools");

    m_menuHelp = new wxMenu();
    auto* menu_help = new wxMenuItem(m_menuHelp, wxID_ABOUT, wxEmptyString);
    menu_help->SetBitmap(wxArtProvider::GetBitmapBundle(wxART_HELP, wxART_MENU));

    m_menuHelp->Append(menu_help);
    auto* menu_item_6 = new wxMenuItem(m_menuHelp, wxID_ANY, "wxWidgets Documentation",
        "Open wxWidgets documentation in your default browser.", wxITEM_NORMAL);
    menu_item_6->SetBitmap(wxueBundleSVG(wxue_img::wxlogo_svg, 1476, 5078, wxSize(16, 16)));

    m_menuHelp->Append(menu_item_6);
    auto* menu_item_9 = new wxMenuItem(m_menuHelp, wxID_ANY, "wxPython Documentation",
        "Open wxPython documentation in your default browser.", wxITEM_NORMAL);
    menu_item_9->SetBitmap(wxue_img::bundle_wxPython_png());
    m_menuHelp->Append(menu_item_9);
    auto* menu_item_10 = new wxMenuItem(m_menuHelp, wxID_ANY, "wxRuby Documentation",
        "Open wxRuby documentation in your default browser.", wxITEM_NORMAL);
    menu_item_10->SetBitmap(wxue_img::bundle_ruby_logo_svg(16, 16));
    m_menuHelp->Append(menu_item_10);
    m_menubar->Append(m_menuHelp, "&Help");

    SetMenuBar(m_menubar);

    Centre(wxBOTH);

    // Event handlers
    Bind(wxEVT_CLOSE_WINDOW, &MainFrameBase::OnClose, this);
    Bind(wxEVT_MENU, &MainFrameBase::OnToggleExpandLayout, this, id_Expand);
    Bind(wxEVT_MENU, &MainFrameBase::OnGenerateCode, this, id_GenerateCode);
    Bind(wxEVT_MENU, &MainFrameBase::OnDifferentProject, this, id_DifferentProject);
    Bind(wxEVT_MENU,
        [](wxCommandEvent&)
        {
            Project.NewProject(true);
        },
        id_NewProject);
    Bind(wxEVT_MENU, &MainFrameBase::OnOpenProject, this, id_OpenProject);
    Bind(wxEVT_MENU,
        [](wxCommandEvent&)
        {
            // Specifying false tells NewProject to import
            Project.NewProject(false);
        },
        menu_import->GetId());
    Bind(wxEVT_MENU, &MainFrameBase::OnSaveProject, this, wxID_SAVE);
    Bind(wxEVT_MENU, &MainFrameBase::OnPreviewXrc, this, id_PreviewForm);
    Bind(wxEVT_MENU, &MainFrameBase::OnSaveAsProject, this, id_SaveProjectAs);
    Bind(wxEVT_MENU, &MainFrameBase::OnAppendCrafter, this, id_AppendCrafter);
    Bind(wxEVT_MENU, &MainFrameBase::OnAppendFormBuilder, this, id_AppendFormBuilder);
    Bind(wxEVT_MENU, &MainFrameBase::OnAppendGlade, this, id_AppendGlade);
    Bind(wxEVT_MENU, &MainFrameBase::OnAppendSmith, this, id_AppendSmith);
    Bind(wxEVT_MENU, &MainFrameBase::OnAppendDialogBlocks, this, id_AppendCrafter);
    Bind(wxEVT_MENU, &MainFrameBase::OnImportWindowsResource, this, id_AppendWinRes);
    Bind(wxEVT_MENU, &MainFrameBase::OnAppendXRC, this, id_AppendXRC);
    Bind(wxEVT_MENU, &MainFrameBase::OnPreferencesDlg, this, id_PreferencesDlg);
    Bind(wxEVT_MENU,
        [](wxCommandEvent&)
        {
            wxGetFrame().Undo();
        },
        wxID_UNDO);
    Bind(wxEVT_MENU, &MainFrameBase::OnEditCustomIds, this, menu_item_8->GetId());
    Bind(wxEVT_MENU,
        [](wxCommandEvent&)
        {
            wxGetFrame().Redo();
        },
        wxID_REDO);
    Bind(wxEVT_MENU, &MainFrameBase::OnAbout, this, wxID_ABOUT);
    Bind(wxEVT_MENU, &MainFrameBase::OnCut, this, wxID_CUT);
    Bind(wxEVT_MENU, &MainFrameBase::OnBrowseDocs, this, menu_item_6->GetId());
    Bind(wxEVT_MENU, &MainFrameBase::OnCopy, this, wxID_COPY);
    Bind(wxEVT_MENU, &MainFrameBase::OnPaste, this, wxID_PASTE);
    Bind(wxEVT_MENU, &MainFrameBase::OnBrowsePython, this, menu_item_9->GetId());
    Bind(wxEVT_MENU, &MainFrameBase::OnDelete, this, wxID_DELETE);
    Bind(wxEVT_MENU, &MainFrameBase::OnBrowseRuby, this, menu_item_10->GetId());
    Bind(wxEVT_MENU, &MainFrameBase::OnDuplicate, this, menu_duplicate->GetId());
    Bind(wxEVT_MENU, &MainFrameBase::OnFindDialog, this, wxID_FIND);
    Bind(wxEVT_MENU, &MainFrameBase::OnInsertWidget, this, id_insert_widget);
    Bind(wxEVT_MENU,
        [](wxCommandEvent&)
        {
            wxGetFrame().MoveNode(MoveDirection::Up);
        },
        id_MoveUp);
    Bind(wxEVT_MENU,
        [](wxCommandEvent&)
        {
            wxGetFrame().MoveNode(MoveDirection::Down);
        },
        id_MoveDown);
    Bind(wxEVT_MENU,
        [](wxCommandEvent&)
        {
            wxGetFrame().MoveNode(MoveDirection::Left);
        },
        id_MoveLeft);
    Bind(wxEVT_MENU,
        [](wxCommandEvent&)
        {
            wxGetFrame().MoveNode(MoveDirection::Right);
        },
        id_MoveRight);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeAlignment, this, id_AlignLeft);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeAlignment, this, id_AlignCenterHorizontal);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeAlignment, this, id_AlignRight);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeAlignment, this, id_AlignTop);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeAlignment, this, id_AlignCenterVertical);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeAlignment, this, id_AlignBottom);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeBorder, this, id_BorderLeft);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeBorder, this, id_BorderRight);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeBorder, this, id_BorderTop);
    Bind(wxEVT_MENU, &MainFrameBase::OnChangeBorder, this, id_BorderBottom);
    Bind(wxEVT_TOOL, &MainFrameBase::OnGenerateCode, this, id_GenerateCode);
    Bind(wxEVT_TOOL, &MainFrameBase::OnPreviewXrc, this, id_PreviewForm);
    Bind(wxEVT_UPDATE_UI,
        [](wxUpdateUIEvent& event)
        {
            event.Enable(wxGetFrame().isModified());
        },
        wxID_SAVE);
    Bind(wxEVT_UPDATE_UI,
        [](wxUpdateUIEvent& event)
        {
            event.Enable(wxGetFrame().CanUndo());
        },
        wxID_UNDO);
    Bind(wxEVT_UPDATE_UI,
        [](wxUpdateUIEvent& event)
        {
            event.Enable(wxGetFrame().CanRedo());
        },
        wxID_REDO);
    Bind(wxEVT_UPDATE_UI,
        [](wxUpdateUIEvent& event)
        {
            event.Enable(wxGetFrame().CanCopyNode());
        },
        wxID_CUT);
    Bind(wxEVT_UPDATE_UI,
        [](wxUpdateUIEvent& event)
        {
            event.Enable(wxGetFrame().CanPasteNode());
        },
        wxID_PASTE);
    Bind(wxEVT_UPDATE_UI,
        [](wxUpdateUIEvent& event)
        {
            event.Enable(wxGetFrame().CanCopyNode());
        },
        wxID_DELETE);
    Bind(wxEVT_UPDATE_UI,
        [](wxUpdateUIEvent& event)
        {
            event.Enable(wxGetFrame().CanCopyNode());
        },
        menu_duplicate->GetId());
    Bind(wxEVT_UPDATE_UI, &MainFrameBase::OnUpdateBrowsePython, this, menu_item_9->GetId());
    Bind(wxEVT_UPDATE_UI, &MainFrameBase::OnUpdateBrowseDocs, this, menu_item_6->GetId());
    Bind(wxEVT_UPDATE_UI, &MainFrameBase::OnUpdateBrowseRuby, this, menu_item_10->GetId());

    return true;
}

namespace wxue_img
{
    // ../art_src/expand.svg
    const unsigned char expand_svg[648] {
        120,218,157,84,77,143,218,48,16,237,79,137,220,203,174,100,140,63,226,175,64,184,246,146,170,82,219,189,244,82,
        101,19,3,81,67,28,57,97,97,251,235,59,54,139,88,212,75,213,3,114,222,140,253,230,205,243,152,245,244,178,203,78,
        93,59,239,75,36,232,120,70,217,222,117,187,253,124,69,47,46,76,157,31,74,196,8,67,217,249,208,15,83,49,185,208,
        109,75,180,159,231,177,88,46,79,167,19,73,17,210,248,195,18,101,211,252,218,187,18,109,187,190,95,132,99,239,10,
        247,226,6,223,182,171,166,239,198,251,8,218,172,119,89,215,150,232,217,159,225,59,184,102,206,206,80,153,88,170,
        80,246,90,34,78,12,19,232,170,143,113,194,140,185,41,100,130,48,46,239,42,22,97,247,252,64,49,151,50,254,30,87,
        211,28,252,47,87,28,67,255,240,241,231,215,186,237,234,158,93,163,139,68,91,64,99,114,60,175,208,114,179,94,238,
        64,208,102,61,214,243,62,201,170,67,240,39,148,193,215,103,46,137,96,2,51,6,218,76,197,57,145,66,99,150,19,170,
        68,197,115,34,164,138,57,102,43,206,8,103,23,160,121,197,12,161,58,79,72,138,136,24,205,177,38,202,230,105,99,46,
        1,104,198,19,133,81,17,8,22,217,21,80,228,196,8,40,21,11,99,69,172,129,35,144,183,57,54,196,112,72,192,66,57,182,
        36,55,42,102,76,172,67,9,139,26,222,139,253,241,183,65,202,96,166,41,166,143,171,219,45,13,126,248,237,130,191,
        249,144,28,104,253,105,64,111,142,68,27,36,161,150,99,144,110,85,94,105,34,52,195,32,93,89,94,89,194,21,100,52,
        116,31,129,21,0,76,188,159,10,68,41,161,98,138,9,93,177,216,92,60,164,169,170,192,64,80,136,161,97,170,32,37,136,
        80,50,34,43,242,10,212,27,14,36,2,122,54,9,89,80,77,20,183,145,145,230,23,196,42,67,56,213,241,91,218,8,152,22,
        152,67,69,173,34,200,211,121,169,42,5,91,19,181,81,188,122,223,197,127,218,147,102,53,58,228,143,179,11,40,142,
        45,77,35,75,209,237,57,189,127,76,247,101,128,206,37,174,214,109,39,96,75,147,249,41,46,110,184,240,94,167,21,101,
        205,133,187,185,144,7,152,123,148,237,222,182,62,13,221,60,149,232,8,15,240,219,88,55,238,203,240,52,185,91,250,
        123,168,135,105,235,195,161,68,135,122,14,221,249,97,17,199,211,26,225,22,84,225,5,179,68,25,45,227,117,24,169,
        53,6,95,41,85,202,42,153,220,21,112,125,113,165,48,77,143,48,6,211,236,199,204,111,183,147,155,147,150,183,142,
        98,120,209,248,222,135,226,185,175,155,95,171,20,240,160,167,155,95,11,22,219,188,59,201,254,241,36,77,102,223,
        123,3,129,139,101,75,248,227,218,124,248,3,243,109,83,173
    };
    // ../art_src/generate.svg
    const unsigned char generate_svg[2435] {
        120,218,173,88,75,111,27,57,18,222,159,210,208,94,18,172,76,147,197,183,19,231,162,195,92,100,44,48,187,115,241,
        37,240,216,178,45,140,34,9,146,242,240,252,250,253,170,216,47,182,237,77,50,24,24,70,243,19,171,138,236,98,85,125,
        197,126,127,252,242,208,124,93,223,157,30,47,103,86,239,191,205,154,199,213,250,225,241,212,161,47,171,195,113,
        189,219,94,206,140,50,179,230,219,167,205,246,120,113,92,29,214,247,151,179,199,211,105,127,113,126,254,245,235,
        87,37,191,168,219,221,167,243,89,115,60,61,109,86,151,179,251,245,102,115,118,248,188,89,93,172,190,172,182,187,
        187,187,119,183,155,245,190,254,101,246,225,253,67,179,190,187,156,237,111,246,88,167,135,15,135,221,231,253,100,
        18,171,203,42,23,149,252,254,230,244,88,132,118,155,167,135,221,54,207,26,128,43,74,42,132,121,80,54,184,37,101,
        101,179,169,1,63,66,94,26,82,209,60,67,172,75,203,98,162,2,98,226,186,122,195,139,195,195,239,111,136,194,220,196,
        60,55,218,191,125,55,188,247,118,183,253,115,117,216,189,155,157,63,223,167,49,237,70,163,178,52,247,74,135,200,
        139,104,111,106,192,143,72,75,99,148,141,52,69,208,13,126,89,76,84,64,76,252,77,27,181,101,163,38,170,148,211,156,
        180,178,54,44,201,97,7,121,130,76,86,209,197,101,43,57,65,73,57,67,189,100,141,32,66,212,75,214,40,40,151,82,47,
        89,35,207,34,189,100,141,156,242,193,246,146,53,178,42,71,215,75,214,72,171,148,76,47,57,69,148,105,36,57,66,86,
        69,156,89,144,0,26,143,249,17,253,18,194,154,15,169,70,78,153,228,123,95,214,200,42,159,67,103,125,130,72,81,232,
        119,53,65,70,133,104,122,201,26,201,105,189,20,22,222,99,210,205,141,249,126,88,156,118,135,237,199,251,245,225,
        120,58,219,223,60,172,198,73,57,76,253,171,76,113,220,120,101,230,70,105,29,151,60,114,42,91,196,132,194,98,101,
        216,79,191,176,45,142,84,222,154,161,244,221,109,201,178,31,135,101,241,202,148,242,92,195,111,203,118,220,58,81,
        171,160,39,192,43,79,1,91,137,102,60,28,235,242,248,250,10,97,148,125,100,63,70,143,83,236,145,9,200,1,149,157,
        121,6,106,57,160,222,8,82,32,89,179,28,16,57,211,234,77,65,45,7,52,24,9,42,235,176,28,144,53,177,211,155,128,90,
        14,104,48,130,71,162,229,128,44,194,186,213,155,128,90,14,104,48,98,81,174,98,63,73,202,133,212,233,85,160,150,
        19,52,24,1,199,88,219,79,194,233,206,118,122,21,168,229,4,245,70,162,114,190,247,87,80,41,116,158,28,143,43,33,
        1,47,197,159,177,56,53,61,247,63,80,44,49,48,45,247,88,104,32,205,221,18,3,48,75,246,194,44,70,211,20,21,106,193,
        155,197,96,167,168,84,243,172,28,77,65,41,19,122,24,32,133,12,34,150,98,154,159,233,46,215,135,145,133,88,75,11,
        163,161,83,46,198,150,214,198,227,126,231,50,184,190,170,249,178,166,210,49,199,142,201,178,230,209,154,99,43,123,
        215,87,53,203,213,4,56,102,198,49,197,213,236,87,51,99,101,15,230,171,34,60,46,207,227,178,93,23,244,186,216,215,
        68,80,147,68,77,32,53,185,212,196,83,147,82,77,88,53,153,213,68,87,147,96,77,144,53,121,214,196,90,147,110,77,200,
        53,89,215,68,94,147,124,77,34,53,193,212,228,83,19,83,77,90,53,161,213,100,87,19,97,77,146,213,217,93,95,213,69,
        124,92,222,135,98,61,170,224,227,194,94,85,252,202,206,245,213,64,74,3,81,77,232,73,70,215,47,244,181,227,74,112,
        88,221,158,164,18,240,128,184,83,190,156,73,169,153,53,79,24,9,45,204,186,62,27,41,161,77,24,58,109,222,252,115,
        35,118,98,164,208,194,79,26,241,83,35,66,11,63,105,36,78,141,8,45,252,164,145,60,53,34,180,240,115,70,236,212,177,
        133,22,126,210,200,212,177,66,12,223,181,113,254,48,252,183,183,148,213,205,97,116,73,57,61,90,242,174,187,147,
        72,115,143,26,98,45,167,154,53,139,22,224,225,162,111,16,134,38,19,103,147,179,174,65,209,112,57,182,104,145,85,
        210,166,155,66,248,135,78,73,198,197,90,25,38,101,156,111,138,60,91,76,161,51,85,208,162,93,166,157,235,246,83,
        212,198,187,155,176,223,231,195,230,205,63,63,254,122,115,183,190,217,152,215,200,143,29,81,17,160,37,215,93,22,
        192,235,206,50,51,197,184,128,67,83,18,144,82,195,108,64,9,128,140,101,224,37,99,201,50,77,248,208,15,81,14,230,
        156,168,11,148,119,143,242,14,138,54,185,193,105,231,204,124,29,124,96,224,80,73,34,202,109,92,38,21,179,155,179,
        83,252,34,161,120,241,239,198,164,6,179,196,150,188,197,208,7,51,136,219,121,86,33,89,150,142,94,170,61,249,6,142,
        209,165,188,195,63,177,235,46,28,202,70,15,188,116,178,217,100,6,137,242,2,117,59,17,55,57,104,66,26,0,240,32,135,
        182,75,3,136,129,22,45,128,99,240,34,0,120,41,0,138,162,147,165,21,242,120,119,172,99,69,44,165,132,189,233,36,
        125,23,74,21,246,102,225,32,208,4,249,8,16,185,15,130,42,26,69,188,25,9,17,120,237,22,168,189,28,25,108,135,223,
        135,74,152,88,18,29,45,12,17,162,229,90,235,224,25,200,185,108,217,203,186,32,40,55,64,33,251,18,38,142,15,201,
        81,105,74,99,16,54,119,36,12,129,197,128,114,148,70,23,161,207,161,71,58,20,84,2,209,181,96,97,152,104,251,25,135,
        247,42,114,28,4,104,63,138,22,69,233,46,35,7,44,86,211,102,129,23,116,73,214,214,16,12,10,55,1,222,100,180,196,
        40,100,137,122,107,161,134,87,116,18,217,30,9,132,71,140,162,102,2,162,38,227,97,69,207,51,240,37,89,172,40,177,
        15,61,142,135,221,194,30,128,4,90,108,95,90,223,196,32,7,207,231,17,185,153,230,248,179,140,108,246,11,36,168,54,
        210,209,154,100,27,65,110,46,30,73,35,196,103,63,32,91,178,144,157,38,117,38,9,50,18,89,129,251,98,94,60,49,162,
        100,100,83,57,112,60,134,36,27,115,160,71,32,67,153,145,198,28,130,152,208,81,34,135,17,184,56,244,16,88,43,91,
        78,25,132,42,139,33,42,0,116,34,209,193,12,210,132,47,216,1,107,88,214,33,203,142,142,172,31,248,120,56,9,57,129,
        108,78,124,58,193,179,49,226,15,36,240,137,149,28,93,240,25,218,200,73,157,229,168,57,40,36,221,219,115,111,83,
        31,158,242,105,152,160,88,102,164,226,153,108,7,49,227,11,72,50,99,252,32,166,163,31,196,116,240,131,152,246,197,
        154,108,160,175,55,215,92,125,44,137,163,208,106,202,30,130,92,32,108,202,178,187,118,166,221,105,39,230,184,121,
        232,102,224,14,23,36,247,41,245,136,112,26,113,209,33,244,121,33,54,173,154,227,192,232,12,10,224,220,48,229,154,
        148,29,167,148,225,169,86,169,69,173,193,22,97,49,158,227,203,129,92,126,156,23,139,195,171,188,88,164,151,235,
        45,104,136,94,42,210,199,211,97,247,199,170,92,101,56,113,202,255,219,246,247,51,225,187,11,88,118,251,111,82,208,
        199,68,150,236,152,200,16,43,58,155,178,97,188,89,139,208,181,57,241,64,226,106,225,57,3,139,11,76,139,248,213,
        114,138,253,28,238,54,35,189,22,181,54,91,100,56,246,154,78,15,13,161,163,222,166,160,69,183,94,59,215,238,165,
        213,27,239,115,226,46,120,101,245,186,147,190,62,174,79,171,206,51,187,253,205,237,250,244,4,223,4,255,170,183,
        94,160,191,228,91,250,3,227,105,14,84,159,228,254,83,50,208,115,110,226,197,56,231,112,238,236,128,132,216,230,
        60,22,128,240,4,64,210,49,61,21,254,67,9,76,146,65,204,96,196,20,64,156,152,222,11,59,37,201,120,20,115,20,56,151,
        184,20,100,230,179,100,10,159,105,86,112,12,12,211,154,144,1,49,136,62,44,131,228,56,215,160,156,208,76,200,215,
        31,46,79,220,112,16,137,11,57,110,1,156,148,63,66,149,73,220,68,8,81,197,204,251,226,192,116,16,224,117,146,84,
        82,107,208,140,152,92,152,9,229,140,11,146,84,94,39,26,148,202,237,5,229,146,95,203,9,77,177,118,244,185,124,245,
        112,66,76,252,187,28,53,106,99,144,238,197,105,195,153,161,219,11,143,149,60,17,45,94,2,87,14,20,0,146,43,78,38,
        206,120,114,210,216,100,43,25,159,172,23,196,137,136,224,179,78,144,151,15,34,206,22,182,52,129,51,91,39,42,68,
        17,132,110,202,109,139,248,124,184,104,122,249,116,66,133,110,66,97,72,29,133,110,130,88,65,251,209,8,249,8,48,
        142,233,70,167,88,140,148,139,24,31,1,83,142,103,53,19,37,57,116,97,26,110,116,184,174,106,65,161,92,38,193,24,
        204,59,33,164,242,181,36,112,35,9,58,224,19,2,85,52,3,178,90,122,186,96,165,112,129,9,120,155,124,243,97,110,49,
        194,11,174,112,139,134,158,116,8,114,177,197,133,153,81,32,135,16,146,136,5,129,24,18,54,97,37,116,29,210,64,177,
        190,132,159,139,162,192,25,26,203,135,24,132,137,196,174,75,236,196,100,24,104,166,94,228,170,244,104,1,253,20,
        179,71,9,95,146,111,55,154,114,73,17,233,14,164,150,35,174,57,240,2,115,137,15,210,123,244,137,244,119,164,179,
        253,255,233,124,183,186,63,226,178,32,109,239,47,252,88,109,203,181,161,107,133,103,205,45,110,14,26,143,39,121,
        28,112,93,152,53,15,173,232,111,219,245,233,120,57,251,124,92,29,254,131,37,87,255,222,254,118,92,13,211,255,61,
        220,108,143,247,187,195,167,203,217,167,155,211,97,253,237,13,98,10,97,148,230,26,127,40,251,36,201,202,253,123,
        136,165,45,215,230,45,202,240,241,180,219,55,187,251,251,227,234,36,171,182,110,224,159,207,110,119,155,221,225,
        226,247,205,205,237,31,239,228,135,225,101,113,187,57,159,40,155,31,85,22,143,212,142,248,240,126,35,84,83,59,166,
        165,31,220,168,140,236,237,169,60,190,145,44,246,68,130,254,178,131,16,124,168,53,86,34,56,33,191,207,186,65,55,
        33,221,156,227,138,26,99,10,233,199,188,37,159,188,249,134,85,254,223,214,239,254,220,107,168,165,254,85,59,40,
        188,237,255,15,216,121,221,12,161,3,46,255,63,96,38,190,106,199,72,239,47,255,223,181,99,254,162,111,206,235,56,
        192,15,37,111,206,143,95,30,62,252,227,127,72,71,193,130
    };
    // ../art_src/hidden.svg
    const unsigned char hidden_svg[1993] {
        120,218,181,152,219,110,27,55,16,134,251,40,11,93,181,128,178,230,12,207,78,156,155,189,117,95,160,119,109,162,
        218,106,29,203,144,149,67,251,244,253,255,33,41,75,137,147,6,5,10,4,209,124,203,89,46,15,195,127,134,126,245,248,
        225,102,250,184,125,123,184,189,90,121,247,240,105,53,221,110,182,55,183,135,65,31,54,251,199,237,238,254,106,37,
        179,172,166,79,239,238,238,31,47,31,55,251,237,239,87,171,219,195,225,225,242,226,226,227,199,143,179,61,153,223,
        236,222,93,172,166,199,195,95,119,155,171,213,239,219,187,187,23,251,247,119,155,203,205,135,205,253,238,237,219,
        151,111,238,182,15,231,79,30,15,251,221,159,155,23,119,219,251,205,31,187,237,253,229,126,247,254,254,248,244,221,
        246,176,217,223,109,241,115,169,47,87,175,95,221,76,219,183,87,171,27,248,60,8,240,225,215,195,173,61,161,145,220,
        106,130,249,179,214,57,39,89,75,152,85,235,66,18,35,137,105,2,133,80,214,226,231,156,243,164,101,174,181,146,212,
        149,133,164,129,36,226,217,86,130,145,107,148,35,60,117,174,205,51,229,64,42,46,176,45,22,163,84,141,66,49,207,
        104,142,190,90,83,72,246,57,173,145,228,67,37,137,249,169,194,49,207,49,249,181,200,28,42,154,18,102,128,215,220,
        156,208,97,156,139,234,154,147,130,95,156,83,138,128,164,158,45,209,5,64,224,92,226,236,125,5,120,175,116,147,204,
        22,41,137,45,206,37,128,11,50,105,152,139,247,107,76,174,166,5,224,37,1,66,66,111,88,19,116,93,102,231,19,65,48,
        167,60,39,191,40,38,93,5,118,168,113,2,228,202,6,159,148,16,13,148,223,212,217,85,191,78,88,33,140,70,230,152,9,
        137,166,243,17,38,125,220,92,48,233,196,245,158,0,201,9,64,156,16,124,89,71,124,169,208,203,133,10,40,193,79,210,
        246,47,206,153,166,79,116,138,169,46,0,241,116,10,69,39,41,220,23,2,77,238,13,86,67,227,2,240,234,1,42,112,202,
        115,77,25,32,13,146,139,0,135,24,1,132,98,128,145,8,231,22,214,97,174,57,18,52,40,33,202,34,201,194,5,224,208,1,
        246,40,210,173,36,33,68,151,9,216,75,128,19,190,147,217,130,209,10,109,69,103,177,25,215,8,198,214,81,230,24,9,
        195,3,118,105,238,201,32,107,3,122,101,205,79,45,152,53,193,219,59,202,113,100,142,16,182,55,175,168,214,128,173,
        62,129,102,211,75,176,90,125,128,30,159,76,132,108,80,146,141,178,248,197,192,222,41,161,181,156,216,177,52,160,
        87,40,109,234,58,217,217,225,100,74,174,19,66,59,199,60,214,14,16,188,65,176,150,102,103,179,133,61,35,30,121,132,
        156,45,48,247,20,193,229,196,54,197,222,224,65,234,219,5,40,220,85,231,205,205,99,149,8,209,32,217,59,62,211,77,
        163,1,162,27,32,193,222,41,54,50,231,131,69,66,89,12,124,131,214,162,167,96,54,190,233,102,177,72,74,82,167,194,
        232,71,224,70,28,227,132,136,142,237,160,192,196,57,163,153,240,56,215,66,59,40,109,40,2,237,10,159,228,120,98,
        114,46,120,30,208,37,162,210,177,27,133,218,224,240,5,246,163,106,118,164,143,58,59,148,217,195,150,98,118,41,11,
        78,138,210,86,172,20,6,149,121,164,67,129,25,16,37,56,2,229,250,201,148,5,27,34,166,6,97,98,28,80,38,18,116,6,39,
        94,10,101,70,157,95,0,88,110,130,176,37,225,83,4,172,42,32,53,55,108,36,52,15,239,67,168,56,58,181,51,8,128,166,
        76,56,242,85,77,235,24,22,88,28,49,21,12,216,61,72,135,65,114,116,11,216,8,66,210,5,122,224,133,34,235,49,28,55,
        7,8,5,3,50,16,180,118,217,246,112,211,156,13,176,12,0,196,40,161,10,33,26,96,153,232,70,113,7,72,100,11,191,195,
        44,96,239,248,50,82,194,11,232,139,1,245,186,3,244,194,165,225,22,121,24,150,222,65,180,84,209,187,6,148,56,62,
        10,168,246,209,100,80,160,105,125,160,148,236,52,166,64,29,203,112,243,174,181,36,186,65,157,12,48,2,64,72,4,100,
        31,186,197,6,222,220,146,189,83,35,167,224,115,53,128,250,185,57,122,184,49,34,232,86,196,32,38,104,3,86,2,144,
        17,73,136,109,30,122,218,60,142,24,180,53,136,208,70,64,208,14,144,3,164,12,243,194,18,162,197,227,52,19,40,7,109,
        171,32,136,158,125,217,38,2,106,158,250,246,66,55,99,26,27,143,20,38,200,41,232,26,83,43,204,70,136,28,69,234,50,
        221,102,228,121,168,6,133,190,102,68,164,207,6,1,91,5,168,201,0,7,26,218,38,13,226,66,133,203,180,115,64,104,59,
        232,186,101,19,177,56,79,4,47,60,11,71,168,253,4,60,3,56,86,1,66,129,52,37,89,39,158,198,76,168,133,231,185,98,
        152,200,121,41,230,5,128,165,37,96,204,128,104,54,94,129,141,188,96,80,151,10,47,188,130,32,44,8,105,7,183,66,74,
        93,52,152,102,139,44,93,78,26,77,93,105,140,116,136,80,35,19,171,100,158,53,88,91,168,230,89,171,169,26,146,195,
        154,121,60,152,103,230,0,73,77,74,67,167,60,36,215,200,116,178,228,70,217,20,16,201,213,136,125,54,165,102,161,
        32,233,154,132,72,105,68,73,247,201,250,20,10,52,38,140,4,76,170,67,250,149,25,213,94,99,186,104,180,244,76,66,
        210,58,245,36,67,242,181,167,31,2,163,178,37,166,70,83,207,89,39,20,26,212,165,231,57,82,178,68,199,20,72,66,56,
        244,236,216,104,233,137,243,164,173,54,104,57,245,72,215,18,187,181,180,204,60,156,90,206,30,163,109,233,220,170,
        40,93,122,166,39,181,182,222,157,171,101,212,7,99,193,91,233,64,82,171,29,88,85,216,38,214,81,112,144,160,45,189,
        22,177,205,47,83,47,83,148,25,181,140,10,134,209,148,173,132,97,105,211,98,171,213,60,176,35,211,83,43,135,64,193,
        203,210,235,36,150,116,83,47,160,24,157,216,192,86,90,1,156,179,10,140,69,23,162,184,176,208,132,116,88,224,103,
        72,105,47,212,122,128,247,10,78,155,52,247,226,14,132,159,81,247,177,22,100,77,218,74,66,252,36,104,86,175,22,233,
        2,57,233,117,164,50,73,47,189,194,68,207,149,117,109,43,62,249,29,159,71,93,10,18,228,162,94,178,42,207,85,157,
        122,53,107,197,99,24,133,46,39,210,10,98,214,192,160,216,42,98,150,199,156,113,43,137,89,57,171,107,245,105,47,
        170,185,106,211,168,183,11,107,140,81,138,51,43,235,50,170,116,236,87,180,38,171,224,225,239,253,177,184,199,206,
        66,80,70,225,159,45,119,140,75,1,68,181,166,227,133,1,218,91,101,25,151,137,196,19,50,141,139,6,234,133,78,188,
        132,176,98,208,101,92,80,146,165,173,113,121,105,165,240,184,216,48,35,45,222,81,213,71,226,26,212,114,218,217,
        13,232,151,179,219,216,229,254,230,183,31,121,242,69,32,243,154,127,122,249,116,71,187,223,221,255,189,217,239,
        94,174,46,62,191,89,133,118,179,194,225,65,174,87,241,75,187,8,117,154,236,71,219,237,40,31,9,177,219,173,108,81,
        51,222,193,202,148,204,98,184,89,75,91,163,227,115,254,148,227,59,157,236,28,152,213,191,209,223,233,223,31,227,
        122,102,174,144,88,254,75,223,55,209,114,156,40,83,155,142,74,221,0,154,31,173,118,11,200,198,161,21,72,202,100,
        129,52,231,160,151,205,119,97,139,101,80,108,11,222,160,200,178,10,202,71,33,50,50,33,50,139,71,50,48,23,54,47,
        134,183,107,129,195,75,89,178,60,131,249,243,185,180,15,218,213,137,175,216,176,166,49,216,95,126,62,174,233,24,
        247,88,97,91,180,70,105,250,108,87,190,216,173,190,194,253,29,62,12,99,236,109,149,175,79,226,224,124,31,206,247,
        232,139,189,235,95,60,223,239,49,230,231,226,180,80,104,153,41,226,119,109,95,238,127,1,248,79,251,241,255,174,
        216,183,226,40,60,23,71,207,45,71,164,180,201,247,47,135,126,101,57,142,31,228,72,124,31,201,233,16,207,111,168,
        137,234,211,175,158,206,198,206,196,31,228,63,86,213,214,1,42,215,104,151,167,224,207,178,246,83,162,62,217,157,
        178,156,109,220,233,142,254,203,146,193,15,255,170,126,223,122,13,153,251,150,128,61,5,197,105,192,92,159,109,247,
        242,89,40,60,47,143,207,12,151,162,141,195,143,75,215,215,6,124,113,243,250,213,126,243,230,96,131,222,189,63,108,
        246,171,233,211,213,10,129,255,151,253,127,252,43,222,233,223,240,206,63,132,238,54,173,175,199,15,55,175,127,248,
        7,169,134,65,218
    };
    // ../art_src/magnify.svg
    const unsigned char magnify_svg[4117] {
        120,218,197,91,77,115,27,71,146,221,159,210,129,185,216,17,96,171,190,63,100,211,23,28,246,2,199,70,236,238,92,
        116,153,160,73,72,194,152,34,25,32,100,201,251,235,55,223,203,170,110,128,34,52,160,61,182,195,38,153,89,93,93,
        149,149,249,42,63,170,75,223,63,254,242,110,248,180,189,217,191,191,92,120,243,240,121,49,188,223,108,223,189,223,
        119,238,151,205,238,113,123,127,119,185,176,163,93,12,159,63,220,222,61,190,126,220,236,182,111,47,23,239,247,251,
        135,215,175,94,125,250,244,105,100,203,120,125,255,225,213,98,120,220,255,122,187,185,92,188,221,222,222,94,236,
        62,222,110,94,111,126,217,220,221,223,220,124,119,125,187,125,56,110,121,220,239,238,127,222,92,220,110,239,54,
        215,87,15,175,119,247,31,239,110,190,91,252,240,253,59,254,255,112,181,127,63,220,92,46,126,180,50,183,45,75,249,
        237,253,42,142,62,70,165,7,51,166,28,151,113,44,54,52,90,186,198,156,86,141,201,163,15,131,190,224,220,104,172,
        31,218,80,202,173,172,31,99,113,211,179,56,230,152,150,206,142,198,199,65,94,142,201,46,109,29,147,73,43,225,130,
        173,75,103,70,47,115,225,153,9,236,41,29,203,104,106,5,19,99,93,59,145,38,10,87,70,111,242,202,165,49,251,165,171,
        163,73,113,144,54,19,50,30,85,229,138,137,224,76,141,43,233,18,147,72,146,71,103,211,32,92,0,23,199,106,50,122,
        198,74,206,6,153,192,140,197,201,218,202,24,140,91,65,160,104,177,210,90,237,32,194,230,12,166,164,0,198,86,114,
        53,84,116,140,85,116,152,70,43,207,32,44,20,20,100,225,117,226,84,119,141,83,173,74,255,106,124,83,55,148,231,171,
        50,235,67,163,188,129,137,140,104,75,20,105,194,74,94,10,185,49,131,76,44,139,22,35,212,216,104,233,27,108,88,53,
        6,106,198,52,62,230,37,215,22,134,62,24,57,49,120,169,126,122,52,38,44,87,164,138,182,51,58,156,50,98,194,4,147,
        103,168,157,243,31,74,246,230,8,157,175,119,239,126,250,198,57,179,108,63,223,126,55,99,246,238,254,238,255,54,
        187,251,134,208,215,31,119,183,223,252,237,31,107,193,233,213,206,126,219,113,203,109,243,90,166,119,15,159,191,
        91,188,58,70,172,169,105,137,223,22,136,117,74,2,164,14,170,205,37,54,26,74,79,110,213,24,0,54,15,124,1,160,12,
        118,104,35,41,71,192,166,50,61,155,1,27,51,65,9,133,10,96,29,240,234,197,220,128,135,43,120,20,136,80,3,92,8,226,
        114,33,94,139,37,94,83,34,94,129,18,193,107,8,0,172,85,224,81,117,2,95,83,8,88,199,158,214,23,2,182,120,2,54,86,
        2,182,4,2,54,120,244,148,61,67,192,230,66,192,2,40,0,44,113,232,101,6,2,182,18,176,201,19,177,185,16,177,178,29,
        241,44,38,69,44,109,109,179,59,66,172,59,68,108,241,7,136,21,161,165,127,41,22,184,148,126,147,29,132,161,81,68,
        65,126,244,89,52,25,69,37,94,25,78,44,251,89,80,149,67,103,0,43,151,87,157,147,193,115,28,218,91,210,24,32,175,
        14,168,220,42,141,169,63,112,178,184,254,138,210,58,24,105,157,5,189,219,228,7,98,189,24,159,64,221,171,67,95,73,
        159,225,38,123,70,58,49,186,33,17,5,170,17,187,4,177,82,128,149,130,87,46,30,91,73,224,83,228,133,12,206,139,117,
        197,32,185,6,128,201,152,10,252,216,224,128,159,164,254,110,158,239,88,252,195,77,227,78,9,127,189,221,93,223,110,
        134,235,207,18,97,140,200,37,42,184,254,85,104,59,58,191,24,118,151,11,65,72,60,30,87,94,223,60,183,49,253,147,
        141,105,198,108,101,99,62,9,50,63,125,220,239,255,197,204,222,39,78,93,70,231,242,115,107,250,239,171,155,237,213,
        109,232,243,209,80,161,44,97,232,244,66,41,102,151,1,3,132,101,24,109,92,229,209,58,37,7,249,37,134,144,6,223,72,
        246,171,171,198,88,177,104,145,39,193,11,70,157,108,101,188,81,196,142,94,212,150,87,112,135,186,105,138,23,200,
        101,147,193,120,177,162,152,212,196,198,172,228,77,83,250,19,11,204,4,206,147,10,184,226,177,53,164,109,37,61,146,
        116,140,186,183,100,186,232,84,202,3,225,79,235,43,158,194,192,12,94,49,182,169,128,43,67,41,98,174,131,251,113,
        49,172,5,132,14,177,90,162,134,177,107,217,104,49,87,184,138,108,4,188,135,239,189,57,141,150,79,239,183,251,206,
        92,220,63,92,93,111,247,191,138,129,130,127,145,201,176,223,222,13,91,17,248,211,246,238,230,254,211,226,208,138,
        105,132,31,79,216,27,171,137,129,231,16,26,126,36,105,24,19,167,22,74,227,214,8,181,181,49,52,153,239,253,132,177,
        185,141,48,209,216,118,202,72,156,77,105,213,105,175,157,228,109,161,141,29,116,88,210,235,54,33,153,85,147,69,
        123,169,144,250,118,167,101,212,245,225,74,222,156,222,216,233,43,81,19,219,34,47,205,210,126,177,37,140,251,138,
        126,119,155,235,253,32,187,18,153,148,248,0,217,147,121,76,53,44,122,154,42,96,115,201,206,137,42,243,169,103,60,
        39,2,25,28,85,176,71,27,213,75,210,133,220,237,75,161,226,89,251,52,138,187,246,75,68,106,183,70,60,48,153,46,61,
        129,49,226,94,69,99,1,180,227,182,81,58,24,168,181,56,134,157,96,65,35,98,71,104,122,73,175,76,166,224,73,69,186,
        41,123,80,188,42,67,25,55,164,203,124,39,144,137,124,199,113,198,28,226,52,75,225,251,74,199,72,169,44,104,73,34,
        103,121,115,60,16,62,218,40,140,169,174,207,40,76,86,193,196,137,8,147,28,153,28,192,132,72,249,57,128,209,94,158,
        189,10,253,68,112,149,131,101,140,108,235,193,52,147,194,222,60,83,30,60,235,9,146,76,189,68,50,108,215,36,17,192,
        242,58,49,242,28,210,226,24,99,20,58,132,252,132,158,94,37,249,130,137,35,181,101,124,93,41,77,227,138,243,140,
        216,87,213,85,144,153,22,168,12,250,150,166,205,240,175,41,209,102,232,173,91,178,36,233,145,115,237,173,197,145,
        228,120,226,93,155,181,241,155,180,207,3,166,224,156,165,145,16,37,174,38,58,99,254,106,161,105,107,49,103,53,150,
        225,1,226,150,2,59,33,193,79,172,66,132,46,164,29,212,96,41,111,174,142,42,113,16,50,170,122,106,19,152,52,214,
        20,195,212,158,12,105,131,185,98,2,92,108,246,80,141,142,25,48,78,83,89,205,195,129,250,222,64,151,37,206,186,84,
        154,129,40,86,154,203,66,15,201,121,46,128,202,12,133,11,64,115,166,252,146,32,117,217,132,134,252,49,206,237,37,
        245,238,197,218,105,148,226,211,52,122,9,4,101,113,51,237,243,74,105,81,158,20,37,218,95,232,228,219,56,9,217,192,
        74,135,167,178,7,157,150,118,154,108,43,244,74,197,236,237,137,30,86,251,99,85,125,28,172,182,143,15,45,244,121,
        39,237,156,141,78,233,109,251,190,80,154,56,2,93,194,19,90,54,181,40,193,208,217,212,52,100,150,107,192,8,72,79,
        160,102,118,9,138,212,128,118,6,143,194,222,116,38,2,96,24,63,247,86,231,181,3,233,168,96,174,235,222,94,165,62,
        135,112,92,162,227,128,149,42,116,32,115,158,164,74,118,106,13,105,238,220,6,97,23,134,174,234,43,5,7,25,65,105,
        150,158,48,141,209,161,11,222,52,4,181,17,167,52,209,158,26,106,96,239,218,122,153,47,144,176,99,233,98,214,8,64,
        32,196,228,66,102,130,84,10,29,161,27,26,65,58,34,176,74,143,72,231,233,152,102,197,16,219,94,202,172,29,116,143,
        101,212,3,83,187,196,222,182,199,132,214,116,143,166,113,85,103,178,208,118,86,239,90,102,58,176,143,2,176,64,61,
        78,203,139,192,97,74,195,40,134,79,205,235,232,180,205,150,161,212,110,225,24,106,111,197,41,65,239,156,116,99,
        152,204,85,83,245,30,243,167,74,67,21,215,104,221,226,19,29,14,218,3,85,163,38,145,44,78,132,137,69,105,8,150,172,
        134,159,73,7,214,97,173,65,87,77,45,177,53,177,149,222,10,59,191,107,18,30,65,36,86,197,179,93,181,109,19,180,209,
        188,21,103,210,173,214,108,198,121,208,163,153,247,205,143,16,69,17,148,96,107,235,149,198,146,140,86,108,92,54,
        97,72,37,233,14,163,1,98,119,18,144,164,41,157,18,78,250,15,147,239,208,5,161,59,212,18,24,226,171,143,180,17,95,
        141,132,64,210,224,157,135,3,185,94,128,90,117,139,138,122,245,97,234,23,36,127,120,66,87,139,53,106,36,42,21,75,
        40,37,183,132,68,170,112,122,128,12,241,106,219,247,208,90,77,29,43,181,1,168,72,66,215,28,135,144,177,245,196,
        57,131,186,25,246,32,102,100,120,105,183,26,238,36,251,20,218,54,183,32,100,212,148,7,173,138,66,140,231,98,236,
        179,76,115,120,230,86,28,11,120,194,75,5,207,139,83,188,162,189,42,94,211,76,231,184,86,90,149,35,180,45,71,52,
        29,243,106,162,179,195,187,86,205,30,73,107,112,96,31,102,37,213,7,136,168,14,222,81,220,238,124,133,204,236,110,
        217,165,193,4,75,118,186,55,173,69,31,205,48,216,174,46,23,80,18,58,53,104,20,158,185,233,129,151,208,174,182,132,
        68,105,184,53,183,238,180,174,196,68,127,68,99,167,66,59,141,78,88,149,81,183,43,251,65,104,175,154,162,25,93,67,
        167,208,198,54,201,196,208,217,55,137,113,54,227,230,118,175,52,97,97,117,225,240,205,69,125,179,119,68,148,83,
        165,129,86,39,146,44,81,151,166,157,85,26,202,221,76,123,191,238,244,140,228,179,252,119,175,31,138,100,94,150,
        245,3,51,198,169,126,48,72,7,230,242,1,199,144,225,104,7,21,40,172,101,175,74,235,174,169,56,103,123,66,87,235,
        86,66,83,63,69,98,84,101,204,1,32,157,208,82,39,107,114,40,125,108,219,66,1,237,177,193,27,39,94,45,81,148,50,215,
        197,222,218,98,171,20,224,66,171,159,46,24,68,145,41,153,167,180,171,217,4,45,149,39,220,208,113,70,151,220,142,
        152,64,50,23,51,7,180,215,46,154,75,66,68,223,34,27,251,68,77,197,176,36,239,91,110,133,73,233,38,165,20,129,48,
        26,229,40,111,104,160,67,187,237,169,164,30,226,105,152,195,74,15,218,189,110,189,72,205,16,164,6,227,24,117,230,
        92,148,161,104,182,144,78,12,4,178,109,59,61,91,68,203,137,31,213,12,153,135,163,19,77,13,154,196,216,105,75,51,
        137,230,200,152,56,246,117,217,208,130,8,232,220,83,76,172,101,106,118,190,246,222,46,245,60,21,90,40,45,195,20,
        237,180,252,178,81,170,96,186,18,63,104,79,32,158,3,180,8,74,213,217,182,209,48,157,215,66,128,170,107,53,65,109,
        245,122,107,214,108,136,221,141,58,179,128,245,38,54,19,82,13,142,53,15,7,58,57,59,104,84,41,229,20,7,85,148,29,
        45,21,191,2,197,133,58,44,69,193,129,185,34,13,47,238,26,61,84,207,9,70,141,53,78,154,75,126,210,103,74,7,205,213,
        78,221,179,41,90,180,73,159,172,129,62,96,248,236,85,211,118,166,45,52,210,104,3,97,50,203,15,67,29,103,230,254,
        166,112,28,82,152,72,107,86,238,131,196,23,77,194,32,81,177,31,41,175,215,60,10,42,142,86,247,7,172,19,170,38,230,
        3,142,115,213,201,2,191,129,75,53,6,243,132,166,110,200,24,162,109,78,121,162,99,93,77,52,215,20,212,255,115,72,
        13,239,92,82,80,135,168,83,169,39,96,159,94,253,135,149,90,3,78,36,171,13,152,183,131,140,154,160,103,46,74,105,
        182,87,223,189,72,178,147,111,73,209,77,173,101,118,68,217,212,86,8,64,189,122,22,129,102,61,98,192,162,115,43,
        83,225,125,114,11,80,24,69,211,78,207,65,20,145,49,173,97,23,69,36,122,107,100,167,118,179,134,57,239,27,4,52,80,
        212,158,85,90,182,107,96,81,235,185,70,99,113,37,79,237,49,105,192,225,66,131,70,93,226,84,3,17,85,167,25,86,152,
        73,197,169,210,52,181,166,105,73,21,170,169,1,132,209,148,40,87,42,183,213,22,152,178,135,208,174,231,90,39,53,
        87,186,252,164,249,34,23,196,18,220,112,155,100,199,72,198,205,147,131,122,7,232,133,174,76,28,197,160,26,213,44,
        25,106,84,148,74,23,124,25,236,224,213,202,214,212,137,180,88,112,175,119,209,106,52,95,166,225,138,250,43,110,
        5,238,0,75,215,164,167,62,150,210,234,86,115,132,113,170,90,133,112,151,164,217,85,39,63,121,240,152,221,212,12,
        205,105,97,131,77,66,143,89,33,77,72,173,104,65,187,30,197,4,76,53,57,149,179,29,145,53,172,25,53,232,79,140,20,
        0,43,48,73,131,79,197,129,115,139,32,150,76,207,121,42,186,153,169,180,2,99,220,20,116,42,55,179,164,92,34,114,
        213,106,130,182,172,42,38,73,174,208,102,88,187,234,177,67,2,102,170,105,46,143,52,125,149,135,2,43,135,87,7,169,
        107,141,141,50,72,18,234,148,46,212,156,142,104,248,32,78,162,52,247,90,213,202,146,234,173,26,104,1,221,170,199,
        28,158,35,171,62,4,48,88,155,130,32,166,121,213,56,252,1,19,84,109,170,2,13,241,73,149,211,28,240,129,14,219,59,
        86,221,171,184,99,48,205,219,39,62,81,243,122,237,166,133,154,170,218,234,137,147,248,47,50,122,26,104,15,152,232,
        214,141,209,197,243,240,54,28,51,79,140,253,146,18,93,94,242,197,207,35,248,230,219,56,118,104,30,242,128,129,215,
        5,67,23,92,20,72,65,143,78,10,151,170,39,126,40,122,192,120,219,106,25,48,45,247,35,221,147,54,139,15,183,83,179,
        30,0,181,254,41,181,179,62,118,170,173,248,17,58,155,216,170,31,48,45,107,70,167,172,85,120,97,123,175,178,240,
        105,69,189,62,7,42,117,150,162,170,120,28,180,106,149,36,94,10,76,59,148,210,39,234,110,125,58,96,36,165,106,204,
        164,185,106,211,49,163,197,208,204,200,230,38,227,91,57,4,70,235,184,160,221,140,111,17,129,98,134,86,17,129,209,
        176,193,53,182,83,79,27,230,133,161,148,0,227,91,133,196,110,122,208,163,79,114,238,231,106,96,52,240,122,206,169,
        33,139,119,1,12,83,2,13,195,141,209,226,104,98,218,218,82,60,162,213,181,79,116,114,106,200,208,202,35,48,94,21,
        200,78,83,34,102,77,59,42,105,66,182,106,128,210,235,113,74,127,160,37,155,126,37,139,182,199,62,0,175,182,243,
        46,69,97,171,146,64,107,152,81,167,23,52,254,100,194,34,240,84,23,133,210,204,224,50,70,103,14,182,193,89,27,105,
        254,150,181,222,62,238,23,199,247,110,50,190,97,75,81,178,182,78,63,197,147,59,253,121,237,167,219,171,235,159,
        159,126,85,241,225,248,171,202,63,239,183,119,237,166,79,107,253,176,221,111,118,183,91,249,243,218,142,113,22,
        235,88,18,143,130,113,109,3,111,131,40,247,23,73,226,198,132,47,106,126,244,2,43,168,38,252,85,146,88,4,88,232,
        4,73,56,62,92,151,63,205,58,7,98,72,157,93,60,62,243,120,241,229,40,186,255,20,33,158,168,66,2,155,135,77,16,202,
        17,37,255,52,69,224,135,39,14,216,68,247,31,165,207,2,135,15,134,7,15,102,49,223,173,59,188,89,247,140,112,24,239,
        102,243,246,241,135,239,111,249,97,245,63,119,87,55,219,205,157,142,219,175,30,201,208,86,199,214,63,159,221,229,
        2,71,28,142,220,187,246,202,223,239,182,251,199,203,197,199,199,205,238,127,30,174,174,55,255,117,247,247,199,205,
        252,248,127,119,87,119,143,111,239,119,31,46,23,31,174,246,187,237,231,111,60,178,209,128,219,83,146,3,136,183,
        191,232,68,127,96,17,201,45,61,64,8,206,127,43,142,226,113,127,255,48,220,191,125,251,184,217,115,242,182,32,52,
        95,92,223,223,222,239,248,177,85,202,229,101,251,193,247,86,121,214,63,187,91,44,248,104,16,123,106,16,36,160,248,
        255,185,17,94,29,107,235,107,218,115,127,144,246,28,138,65,169,29,46,196,49,20,212,168,243,95,125,128,171,50,94,
        98,160,195,61,141,232,94,160,61,124,129,215,159,127,169,61,137,45,39,135,225,165,64,254,252,118,35,240,22,148,254,
        252,78,59,248,63,200,14,23,72,179,60,142,12,153,87,57,177,200,68,204,143,236,232,2,211,14,201,244,76,58,207,22,
        253,222,200,111,49,192,51,239,74,214,235,206,83,252,169,137,191,208,246,142,55,108,142,181,221,110,41,45,120,197,
        201,232,237,38,195,139,77,246,119,104,25,199,215,80,169,145,255,46,58,195,139,120,184,52,20,240,61,252,5,0,183,
        184,90,135,123,181,79,145,41,58,122,9,56,191,50,78,42,212,216,177,134,190,166,177,248,111,214,152,164,8,14,159,
        2,168,49,205,33,157,196,73,73,27,88,107,248,106,203,111,134,33,210,230,223,12,165,174,227,47,116,115,122,239,166,
        63,104,239,226,214,134,247,155,11,4,31,230,204,142,49,157,127,15,158,161,204,192,117,52,94,143,242,245,124,160,
        225,59,2,210,89,123,134,31,181,39,97,134,15,49,184,39,151,206,24,197,157,26,196,73,110,143,157,226,207,25,228,164,
        79,71,173,131,203,124,231,4,134,112,114,61,82,10,65,148,122,198,32,249,180,86,252,18,23,110,99,56,103,148,252,181,
        81,196,61,199,115,22,84,236,87,86,36,165,143,141,231,88,168,156,84,174,120,18,220,26,78,103,201,82,79,141,34,53,
        36,110,98,198,115,180,91,79,218,8,176,197,229,204,231,211,159,167,195,148,83,195,224,95,2,240,159,13,156,3,187,
        90,79,103,36,208,174,89,218,90,127,71,42,17,113,1,28,87,208,127,79,62,130,127,5,146,235,169,65,190,136,144,175,
        52,185,126,245,248,203,187,31,254,227,255,1,17,229,174,112
    };
    // ../art_src/save.svg
    const unsigned char save_svg[1064] {
        120,218,165,150,207,114,219,54,16,198,251,40,24,157,218,25,6,198,95,130,144,227,92,112,165,95,192,183,54,102,100,
        182,178,228,145,20,59,237,211,247,219,5,64,129,158,100,166,211,28,108,236,143,0,22,11,96,247,131,62,158,95,119,
        226,109,126,188,60,221,109,172,122,249,182,17,79,211,188,123,186,84,122,157,78,231,249,120,184,219,104,169,55,226,
        219,243,254,112,222,158,167,211,252,229,110,243,116,185,188,108,111,110,222,222,222,36,127,145,159,143,207,55,27,
        113,190,252,189,159,238,54,95,230,253,254,195,233,235,126,218,78,175,211,225,248,248,120,251,121,63,191,172,191,
        156,47,167,227,95,211,135,253,124,152,254,60,206,135,237,233,248,245,176,124,125,158,47,211,105,63,163,217,154,
        219,205,167,143,47,191,95,158,196,252,120,183,33,35,110,4,172,123,19,164,87,67,167,101,223,219,209,120,105,220,
        202,142,210,247,67,42,223,149,84,102,16,198,201,161,143,68,78,57,34,52,133,198,94,154,88,187,146,151,67,237,16,
        94,186,62,123,176,182,0,187,30,75,7,47,233,164,138,197,228,255,29,125,48,197,166,64,141,75,11,196,1,139,195,157,
        235,204,32,109,15,219,197,33,219,236,52,174,108,221,75,235,124,42,128,200,6,47,114,124,30,251,143,2,221,170,194,
        72,123,210,149,18,237,55,44,3,233,40,124,246,80,109,118,61,102,224,53,1,249,84,51,37,138,182,175,36,168,113,142,
        183,16,93,67,222,96,229,66,216,11,22,174,160,44,214,205,62,120,251,162,189,180,135,85,190,108,79,187,63,126,29,
        250,78,7,211,25,227,126,187,189,38,209,225,120,248,103,58,29,111,55,55,239,50,65,219,156,10,65,106,67,51,165,118,
        110,204,64,33,132,209,88,233,157,91,195,106,88,134,135,123,29,113,164,216,168,151,61,174,77,201,65,155,12,9,96,
        189,205,32,34,46,143,109,227,134,10,78,134,193,164,5,172,17,117,138,149,209,89,81,189,49,141,117,33,166,100,48,
        82,133,58,18,212,15,134,157,104,223,16,249,175,68,75,243,72,158,199,65,181,177,95,119,162,145,164,122,217,10,211,
        178,23,166,26,63,138,27,9,89,64,201,96,66,90,192,224,214,203,36,242,139,204,41,14,51,213,221,100,170,187,41,35,
        107,196,228,165,1,242,95,137,150,142,203,102,114,84,171,248,191,147,34,198,35,113,35,226,177,63,74,145,29,231,199,
        206,216,247,194,161,253,85,57,58,53,90,25,208,36,100,133,181,157,18,22,87,215,161,204,17,145,149,218,7,216,198,
        153,145,255,119,252,37,113,47,108,186,30,133,214,67,84,168,13,126,84,92,8,73,81,174,13,1,231,132,244,194,52,133,
        234,246,104,184,174,208,166,220,77,29,118,25,107,243,228,145,90,248,64,195,179,5,119,199,238,131,226,178,65,251,
        64,153,110,179,232,120,206,103,20,203,10,6,25,236,152,7,53,38,15,169,147,169,24,172,175,61,104,124,92,92,173,104,
        53,48,195,195,125,110,243,102,175,118,244,165,206,235,192,28,113,241,64,73,107,205,59,34,241,49,49,85,130,44,133,
        44,208,12,46,178,64,219,24,10,85,129,102,72,85,0,105,88,209,97,124,234,125,5,246,93,20,186,46,187,196,147,160,75,
        78,215,64,249,108,186,28,252,21,252,152,77,210,113,205,242,174,203,65,23,33,110,108,122,14,170,62,211,67,35,234,
        243,97,163,175,242,204,192,242,76,5,194,196,242,220,87,98,73,70,162,177,135,133,200,245,88,123,242,61,211,185,178,
        153,242,185,103,16,245,46,32,185,253,21,252,216,220,87,107,127,183,176,58,36,155,182,234,191,73,111,40,181,132,
        82,54,208,10,236,129,5,64,211,137,19,80,33,7,84,139,145,161,95,192,210,101,143,5,60,194,135,38,101,232,241,112,
        145,18,32,255,96,135,33,235,31,60,51,36,200,129,130,98,148,30,45,29,234,147,166,44,192,206,198,2,188,76,98,48,20,
        64,176,162,56,200,161,181,65,255,252,73,148,223,35,141,22,162,240,26,157,12,54,53,26,138,88,32,175,144,0,18,70,
        215,64,80,44,188,129,181,79,147,18,98,82,81,66,167,69,163,228,78,143,141,74,58,157,26,5,205,167,88,213,53,180,194,
        171,174,194,171,218,87,164,68,181,138,255,167,79,197,232,213,169,208,11,135,223,39,205,91,136,223,39,205,59,137,
        223,39,101,239,78,154,208,64,192,43,89,0,101,160,204,114,42,248,81,19,130,184,62,213,160,241,250,18,130,210,245,
        145,164,145,205,3,170,66,251,184,230,103,184,16,173,221,60,202,8,107,181,129,255,115,44,55,59,252,225,151,246,167,
        95,254,5,102,180,147,237
    };
    // ../art_src/wxlogo.svg
    const unsigned char wxlogo_svg[1476] {
        120,218,205,87,75,79,228,70,16,206,79,177,156,203,34,13,61,253,126,12,59,92,124,200,197,81,14,201,94,114,137,8,
        24,112,50,140,71,30,243,216,252,250,84,85,119,219,30,196,194,2,66,90,9,228,250,60,221,213,245,248,190,238,246,231,
        253,221,85,113,223,94,12,215,235,82,241,221,67,89,92,55,237,213,245,144,209,93,211,239,219,110,187,46,5,19,101,
        241,112,179,217,238,87,251,166,111,47,215,229,245,48,236,86,203,229,253,253,61,163,55,236,188,187,89,150,197,126,
        248,186,105,214,229,101,187,217,28,247,183,155,102,213,220,53,219,238,226,226,228,124,211,238,14,223,236,135,190,
        251,183,57,222,180,219,230,159,174,221,174,250,238,118,59,190,189,105,135,166,223,180,240,88,73,126,82,158,126,
        190,162,191,221,217,112,93,92,172,203,95,37,243,11,33,153,243,161,14,204,43,145,64,37,4,83,94,37,84,192,195,42,
        185,16,154,113,229,71,100,152,9,117,2,18,30,82,84,25,105,38,156,44,146,19,105,152,150,162,136,254,35,168,113,221,
        104,86,130,73,29,242,160,99,158,39,163,69,78,107,176,104,173,10,141,20,2,205,73,209,77,57,252,121,80,184,213,109,
        191,249,244,243,95,53,20,230,172,23,71,39,83,49,183,221,246,191,166,239,78,202,229,172,20,129,5,1,62,29,51,210,
        85,150,121,163,9,216,194,50,46,236,66,66,239,184,43,20,147,65,19,208,178,146,76,8,71,192,56,136,73,8,72,150,51,
        101,48,120,17,152,10,170,78,105,24,83,165,212,60,142,148,38,39,12,193,115,153,171,130,37,146,99,93,176,122,58,143,
        155,85,22,61,76,85,55,38,247,64,120,38,133,199,121,222,73,140,221,115,152,199,89,8,132,140,48,197,60,199,71,197,
        234,175,254,254,36,141,89,240,5,79,165,234,118,103,231,237,240,117,197,33,92,42,85,223,156,15,197,3,178,216,184,
        80,22,95,193,210,76,89,95,102,238,75,198,189,158,200,31,152,118,250,219,45,145,71,135,13,192,82,64,112,138,137,
        145,140,104,99,66,194,218,8,48,115,137,191,104,8,202,142,40,83,17,193,68,69,66,138,5,28,24,125,64,49,185,156,152,
        200,101,38,34,151,192,67,61,142,224,76,243,113,110,2,145,140,17,224,130,222,87,9,96,44,10,186,10,217,166,40,103,
        169,60,42,51,80,175,121,130,137,81,174,212,4,33,125,108,66,146,240,212,6,147,95,81,185,225,133,223,61,80,9,151,
        143,84,13,217,114,33,22,26,251,84,3,45,184,150,17,84,192,74,19,84,4,5,112,213,195,47,134,121,233,51,112,76,193,
        156,4,32,51,45,170,12,12,11,22,68,29,61,0,135,164,0,122,69,231,17,213,105,221,136,42,104,191,9,121,32,114,83,100,
        31,9,160,247,58,218,180,108,21,237,24,79,156,29,3,157,231,243,140,198,213,139,26,135,112,65,163,160,76,97,43,136,
        133,91,131,64,195,10,208,67,233,112,27,241,193,225,122,134,27,68,65,1,49,64,210,146,182,152,160,29,196,165,164,
        70,32,84,200,137,0,185,188,172,167,172,180,169,166,124,157,197,92,172,24,75,134,201,76,37,195,2,230,114,198,246,
        232,60,114,86,120,112,50,235,137,54,99,135,56,227,220,99,139,184,151,11,156,141,13,146,28,109,197,117,49,75,248,
        9,189,3,205,128,240,230,37,189,7,220,91,73,239,22,118,186,183,202,93,63,146,59,213,1,59,28,252,196,209,224,177,
        6,202,89,178,49,103,173,197,2,118,96,109,51,0,170,248,58,217,68,33,98,40,33,195,28,140,75,14,4,236,225,19,65,17,
        140,252,68,0,244,180,227,40,207,172,72,243,77,6,228,186,142,0,233,233,171,104,99,48,10,90,106,97,115,166,32,103,
        137,188,90,236,216,1,16,252,123,196,14,201,11,27,144,9,168,118,9,212,73,118,37,61,115,70,36,84,40,142,68,69,105,
        161,165,72,231,96,97,237,68,133,134,32,109,166,73,176,247,17,5,209,93,180,235,180,80,68,149,192,106,184,60,14,24,
        11,7,65,246,145,17,186,174,19,136,43,86,25,197,72,146,147,20,225,65,38,207,232,220,188,168,115,12,219,123,108,40,
        42,93,162,184,21,33,144,58,68,172,188,193,211,18,165,14,107,90,171,16,145,212,129,195,222,18,2,169,195,67,123,58,
        87,81,235,57,114,71,98,159,165,8,106,159,165,15,74,165,172,194,88,66,200,202,141,53,132,192,120,174,110,108,80,
        174,111,145,122,0,14,82,91,64,230,216,42,27,37,14,178,214,241,164,195,30,41,75,249,128,196,15,114,125,66,228,2,
        143,127,248,127,249,88,167,172,227,185,46,223,33,116,251,248,92,199,2,80,147,65,233,153,159,32,116,200,194,40,29,
        65,33,113,239,162,43,29,73,61,33,69,90,143,128,216,36,170,140,4,105,61,249,128,195,217,103,178,162,57,114,21,1,
        82,213,143,131,160,85,206,166,249,102,68,228,187,78,136,168,234,171,140,36,9,30,157,104,153,163,157,165,244,166,
        3,158,14,249,215,170,30,255,169,89,45,148,181,187,133,155,125,137,125,227,212,50,94,78,95,32,243,239,143,39,162,
        67,127,23,205,229,254,244,243,134,26,246,75,127,118,209,54,219,232,55,223,151,193,181,136,190,227,227,65,2,45,0,
        73,66,87,105,202,151,109,59,236,215,229,45,124,187,252,14,73,52,191,109,191,236,155,233,231,63,250,179,237,254,
        178,235,111,214,229,205,217,208,183,15,159,142,45,170,15,36,112,76,183,86,184,88,231,231,248,11,52,88,57,151,191,
        27,142,224,163,101,63,116,187,162,187,188,220,55,3,173,158,50,194,215,199,231,221,166,235,15,111,175,244,62,215,
        84,96,182,7,14,196,115,14,164,68,162,232,167,156,44,15,171,245,92,245,228,7,85,15,24,236,56,101,185,72,38,124,36,
        88,139,215,125,16,165,82,250,251,170,117,127,13,159,133,111,42,211,19,51,249,43,107,163,62,144,89,58,120,151,153,
        101,22,249,57,254,130,247,42,99,232,201,181,48,223,79,173,241,162,244,102,106,69,90,125,203,201,43,202,167,63,142,
        90,22,14,149,68,45,52,65,135,94,199,235,173,148,112,71,249,241,169,101,62,168,54,22,175,46,92,77,132,202,70,254,
        1,239,223,206,211,129,160,95,185,99,165,77,231,157,187,22,110,125,239,36,150,253,200,61,75,219,105,211,210,116,
        193,114,202,196,79,162,31,137,90,203,120,44,46,247,119,87,167,63,253,15,116,134,87,191
    };
    // ../art_src/xrc_preview.svg
    const unsigned char xrc_preview_svg[689] {
        120,218,165,85,219,114,218,48,16,237,167,104,252,212,206,192,98,73,150,108,115,201,139,95,205,15,240,214,6,7,220,
        58,54,99,76,72,250,245,93,237,106,9,188,54,51,12,62,199,222,203,217,213,74,90,159,223,14,234,218,238,167,227,38,
        177,233,233,61,81,199,166,61,28,39,97,111,205,120,110,135,126,147,104,208,137,122,127,237,250,243,242,220,140,237,
        203,38,57,78,211,105,185,88,92,175,87,160,55,240,60,188,46,18,117,158,62,186,102,147,188,180,93,55,31,47,93,179,
        108,222,154,126,216,239,87,207,93,123,122,124,115,158,198,225,79,51,239,218,190,249,61,180,253,114,28,46,253,237,
        237,107,59,53,99,215,226,99,105,86,201,211,250,240,180,62,253,156,142,106,191,73,182,22,242,194,207,60,216,220,
        85,140,29,228,46,83,25,152,18,161,113,136,74,173,9,214,198,65,90,58,194,21,226,92,123,54,49,30,140,137,142,140,
        41,96,205,88,107,240,193,129,137,1,147,121,21,189,145,229,78,197,176,68,106,78,71,184,34,17,108,195,218,162,119,
        36,20,183,190,171,96,183,245,144,90,63,203,193,213,140,116,138,208,88,40,243,123,248,249,29,209,238,161,209,203,
        241,240,235,187,181,51,250,253,88,125,246,190,31,250,191,205,56,172,146,197,93,247,116,1,54,67,229,40,218,151,149,
        206,33,55,54,50,133,44,212,235,32,203,173,16,76,90,218,154,137,49,80,100,89,21,137,133,204,59,21,35,4,149,33,2,
        71,103,38,205,103,38,237,143,150,220,219,24,36,18,10,47,75,64,137,101,9,88,146,44,1,171,149,53,32,86,63,212,181,
        219,234,18,61,102,70,163,3,126,35,18,100,35,137,173,189,39,15,102,76,190,210,226,184,214,30,138,219,132,34,49,50,
        162,58,76,93,156,81,194,181,182,193,148,73,133,21,100,165,143,86,218,137,43,163,16,49,160,60,216,40,49,45,148,68,
        40,100,24,139,56,137,133,76,30,123,220,75,251,74,137,156,197,104,206,98,116,12,140,189,115,105,38,196,128,54,210,
        0,36,57,110,3,54,183,159,155,148,176,52,128,136,52,128,173,176,216,232,202,40,68,12,136,19,137,169,150,6,24,93,
        139,180,175,148,55,79,241,104,8,39,0,2,139,115,133,217,113,52,177,113,16,116,163,134,128,194,120,83,211,1,79,138,
        2,180,179,244,221,138,139,141,65,106,4,38,227,227,10,145,7,239,112,148,217,1,31,116,152,144,118,196,53,71,15,176,
        226,148,100,49,191,249,205,37,86,45,26,119,91,246,177,64,211,150,150,132,20,30,59,110,150,129,43,25,177,18,130,
        81,11,99,220,88,97,241,208,43,236,52,169,142,176,212,71,36,108,196,82,71,35,131,123,94,124,35,102,77,76,184,117,
        140,89,1,249,218,120,112,134,152,150,207,77,209,253,31,107,181,192,43,97,108,158,39,213,226,130,13,23,188,46,240,
        134,218,36,105,162,62,232,255,118,173,221,95,106,143,105,48,92,195,177,240,30,124,250,246,15,228,88,173,56
    };

}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
