///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/gdicmn.h>

#include <wx/bmpbndl.h>

namespace wxue_img
{
    wxImage get_image(const unsigned char* data, size_t size_data);

    wxBitmapBundle bundle_CustomControl_svg(int width, int height);
    wxBitmapBundle bundle_DialogBlocks_png();  // DialogBlocks.png
    wxBitmapBundle bundle_alignbottom_svg(int width, int height);
    wxBitmapBundle bundle_aligncenter_svg(int width, int height);
    wxBitmapBundle bundle_alignleft_svg(int width, int height);
    wxBitmapBundle bundle_alignright_svg(int width, int height);
    wxBitmapBundle bundle_aligntop_svg(int width, int height);
    wxBitmapBundle bundle_alignvertcenter_svg(int width, int height);
    wxBitmapBundle bundle_auitoolbar_svg(int width, int height);
    wxBitmapBundle bundle_bitmap_svg(int width, int height);
    wxBitmapBundle bundle_bitmap_toggle_button_svg(int width, int height);
    wxBitmapBundle bundle_bmp_combo_box_svg(int width, int height);
    wxBitmapBundle bundle_book_page_svg(int width, int height);
    wxBitmapBundle bundle_bottom_svg(int width, int height);
    wxBitmapBundle bundle_calendar_svg(int width, int height);
    wxBitmapBundle bundle_check3state_svg(int width, int height);
    wxBitmapBundle bundle_clear_svg(int width, int height);
    wxBitmapBundle bundle_close_btn_svg(int width, int height);
    wxBitmapBundle bundle_colourPickerIcon_svg(int width, int height);
    wxBitmapBundle bundle_cpp_logo_svg(int width, int height);
    wxBitmapBundle bundle_ctx_help_btn_svg(int width, int height);
    wxBitmapBundle bundle_data_list_svg(int width, int height);
    wxBitmapBundle bundle_dataview_ctrl_png();  // dataview_ctrl.png
    wxBitmapBundle bundle_dataviewlist_ctrl_png();  // dataviewlist_ctrl.png
    wxBitmapBundle bundle_dataviewtree_ctrl_png();  // dataviewtree_ctrl.png
    wxBitmapBundle bundle_datepicker_svg(int width, int height);
    wxBitmapBundle bundle_debug_logo_svg(int width, int height);
    wxBitmapBundle bundle_default_png();  // default.png
    wxBitmapBundle bundle_dirPicker_svg(int width, int height);
    wxBitmapBundle bundle_duplicate_svg(int width, int height);
    wxBitmapBundle bundle_empty_png();  // empty.png
    wxBitmapBundle bundle_filePicker_svg(int width, int height);
    wxBitmapBundle bundle_flex_grid_sizer_svg(int width, int height);
    wxBitmapBundle bundle_folder_svg(int width, int height);
    wxBitmapBundle bundle_fontPicker_svg(int width, int height);
    wxBitmapBundle bundle_gauge_svg(int width, int height);
    wxBitmapBundle bundle_generate_svg(int width, int height);
    wxBitmapBundle bundle_grid_svg(int width, int height);
    wxBitmapBundle bundle_grid_bag_sizer_svg(int width, int height);
    wxBitmapBundle bundle_grid_sizer_svg(int width, int height);
    wxBitmapBundle bundle_hide_svg(int width, int height);
    wxBitmapBundle bundle_images_svg(int width, int height);
    wxBitmapBundle bundle_import_svg(int width, int height);
    wxBitmapBundle bundle_left_svg(int width, int height);
    wxBitmapBundle bundle_new_project_svg(int width, int height);
    wxBitmapBundle bundle_notebook_svg(int width, int height);
    wxBitmapBundle bundle_notebook_aui_svg(int width, int height);
    wxBitmapBundle bundle_notebook_choice_svg(int width, int height);
    wxBitmapBundle bundle_notebook_list_svg(int width, int height);
    wxBitmapBundle bundle_pagectrl_svg(int width, int height);
    wxBitmapBundle bundle_popup_window_svg(int width, int height);
    wxBitmapBundle bundle_preferences_svg(int width, int height);
    wxBitmapBundle bundle_project_svg(int width, int height);
    wxBitmapBundle bundle_prop_sheet_dlg_svg(int width, int height);
    wxBitmapBundle bundle_propgrid_cat_svg(int width, int height);
    wxBitmapBundle bundle_propgriditem_svg(int width, int height);
    wxBitmapBundle bundle_propgridpage_svg(int width, int height);
    wxBitmapBundle bundle_python_logo_only_svg(int width, int height);
    wxBitmapBundle bundle_radio_box_svg(int width, int height);
    wxBitmapBundle bundle_redo_svg(int width, int height);
    wxBitmapBundle bundle_ribbon_bar_svg(int width, int height);
    wxBitmapBundle bundle_ribbon_buttonbar_png();  // ribbon_buttonbar.png
    wxBitmapBundle bundle_ribbon_gallery_png();  // ribbon_gallery.png
    wxBitmapBundle bundle_richtextctrl_svg(int width, int height);
    wxBitmapBundle bundle_right_svg(int width, int height);
    wxBitmapBundle bundle_ruby_logo_svg(int width, int height);
    wxBitmapBundle bundle_saveas_svg(int width, int height);
    wxBitmapBundle bundle_scintilla_svg(int width, int height);
    wxBitmapBundle bundle_scrollbar_png();  // scrollbar.png
    wxBitmapBundle bundle_search_svg(int width, int height);
    wxBitmapBundle bundle_sizer_svg(int width, int height);
    wxBitmapBundle bundle_sizer_horizontal_svg(int width, int height);
    wxBitmapBundle bundle_slider_svg(int width, int height);
    wxBitmapBundle bundle_spacer_svg(int width, int height);
    wxBitmapBundle bundle_spin_ctrl_svg(int width, int height);
    wxBitmapBundle bundle_spin_ctrl_double_svg(int width, int height);
    wxBitmapBundle bundle_spinbtn_svg(int width, int height);
    wxBitmapBundle bundle_static_line_svg(int width, int height);
    wxBitmapBundle bundle_stddialogbuttonsizer_svg(int width, int height);
    wxBitmapBundle bundle_svg_svg(int width, int height);
    wxBitmapBundle bundle_text_file_svg(int width, int height);
    wxBitmapBundle bundle_text_sizer_svg(int width, int height);
    wxBitmapBundle bundle_timepicker_svg(int width, int height);
    wxBitmapBundle bundle_title_close_png();  // title_close.png
    wxBitmapBundle bundle_toggle_button_svg(int width, int height);
    wxBitmapBundle bundle_tool_svg(int width, int height);
    wxBitmapBundle bundle_toolStretchable_svg(int width, int height);
    wxBitmapBundle bundle_tool_dropdown_svg(int width, int height);
    wxBitmapBundle bundle_toolseparator_svg(int width, int height);
    wxBitmapBundle bundle_toolspacer_svg(int width, int height);
    wxBitmapBundle bundle_top_svg(int width, int height);
    wxBitmapBundle bundle_undo_svg(int width, int height);
    wxBitmapBundle bundle_unknown_png();  // unknown.png
    wxBitmapBundle bundle_unknown_svg(int width, int height);
    wxBitmapBundle bundle_wrap_sizer_svg(int width, int height);
    wxBitmapBundle bundle_wxButton_svg(int width, int height);
    wxBitmapBundle bundle_wxCheckBox_svg(int width, int height);
    wxBitmapBundle bundle_wxCheckListBox_png();  // wxCheckListBox.png
    wxBitmapBundle bundle_wxChoice_svg(int width, int height);
    wxBitmapBundle bundle_wxCollapsiblePane_svg(int width, int height);
    wxBitmapBundle bundle_wxComboBox_svg(int width, int height);
    wxBitmapBundle bundle_wxCommandLinkButton_svg(int width, int height);
    wxBitmapBundle bundle_wxDialog_svg(int width, int height);
    wxBitmapBundle bundle_wxEditListBox_png();  // wxEditListBox.png
    wxBitmapBundle bundle_wxFB_png();  // wxFB.png
    wxBitmapBundle bundle_wxFrame_svg(int width, int height);
    wxBitmapBundle bundle_wxGlade_png();  // wxGlade.png
    wxBitmapBundle bundle_wxSmith_png();  // wxSmith.png
    wxBitmapBundle bundle_wxListBox_png();  // wxListBox.png
    wxBitmapBundle bundle_wxListView_png();  // wxListView.png
    wxBitmapBundle bundle_wxPanel_svg(int width, int height);
    wxBitmapBundle bundle_wxPropertyGrid_svg(int width, int height);
    wxBitmapBundle bundle_wxPropertyGridManager_svg(int width, int height);
    wxBitmapBundle bundle_wxPython_svg(int width, int height);
    wxBitmapBundle bundle_wxRadioButton_svg(int width, int height);
    wxBitmapBundle bundle_wxRearrangeCtrl_png();  // wxRearrangeCtrl.png
    wxBitmapBundle bundle_wxScrolledWindow_svg(int width, int height);
    wxBitmapBundle bundle_wxSimpleHtmlListBox_png();  // wxSimpleHtmlListBox.png
    wxBitmapBundle bundle_wxSimplebook_svg(int width, int height);
    wxBitmapBundle bundle_wxSplitterWindow_svg(int width, int height);
    wxBitmapBundle bundle_wxStaticBoxSizer_svg(int width, int height);
    wxBitmapBundle bundle_wxStaticCheckBoxSizer_svg(int width, int height);
    wxBitmapBundle bundle_wxStaticRadioBtnSizer_svg(int width, int height);
    wxBitmapBundle bundle_wxStaticText_svg(int width, int height);
    wxBitmapBundle bundle_wxTextCtrl_svg(int width, int height);
    wxBitmapBundle bundle_wxTimer_svg(int width, int height);
    wxBitmapBundle bundle_wxToolBar_svg(int width, int height);
    wxBitmapBundle bundle_wxToolbook_svg(int width, int height);
    wxBitmapBundle bundle_wxTreebook_svg(int width, int height);
    wxBitmapBundle bundle_wxUiEditor_svg(int width, int height);
    wxBitmapBundle bundle_wxWizard_svg(int width, int height);
    wxBitmapBundle bundle_wxWizardPageSimple_svg(int width, int height);
    wxBitmapBundle bundle_wxcrafter_png();  // wxcrafter.png
    wxBitmapBundle bundle_wxlogo_svg(int width, int height);
    wxBitmapBundle bundle_xml_file_svg(int width, int height);
    wxBitmapBundle bundle_xrc_compare_svg(int width, int height);
    wxBitmapBundle bundle_xrc_preview_svg(int width, int height);
    wxBitmapBundle bundle_xrc_tests_svg(int width, int height);

    wxImage image_DialogBlocks_1_5x_png();
    wxImage image_DialogBlocks_2x_png();
    wxImage image_DialogBlocks_png();
    wxImage image_dataview_ctrl_png();
    wxImage image_dataviewlist_ctrl_png();
    wxImage image_dataviewtree_ctrl_png();
    wxImage image_default_png();
    wxImage image_empty_png();
    wxImage image_ribbon_buttonbar_png();
    wxImage image_ribbon_gallery_png();
    wxImage image_scrollbar_png();
    wxImage image_title_close_png();
    wxImage image_unknown_png();
    wxImage image_wxCheckListBox_png();
    wxImage image_wxEditListBox_png();
    wxImage image_wxFB_1_5x_png();
    wxImage image_wxFB_2x_png();
    wxImage image_wxFB_png();
    wxImage image_wxGlade_png();
    wxImage image_wxListBox_png();
    wxImage image_wxListView_png();
    wxImage image_wxRearrangeCtrl_png();
    wxImage image_wxSimpleHtmlListBox_png();
    wxImage image_wxSmith_1_5x_png();
    wxImage image_wxSmith_2x_png();
    wxImage image_wxSmith_png();
    wxImage image_wxcrafter_png();

    extern const unsigned char CustomControl_svg[7855];  // ../art_src/CustomControl.svg
    extern const unsigned char DialogBlocks_1_5x_png[931];  // ../art_src/DialogBlocks_1_5x.png
    extern const unsigned char DialogBlocks_2x_png[796];  // ../art_src/DialogBlocks_2x.png
    extern const unsigned char DialogBlocks_png[547];  // ../art_src/DialogBlocks.png
    extern const unsigned char alignbottom_svg[506];  // ../art_src/alignbottom.svg
    extern const unsigned char aligncenter_svg[676];  // ../art_src/aligncenter.svg
    extern const unsigned char alignleft_svg[537];  // ../art_src/alignleft.svg
    extern const unsigned char alignright_svg[533];  // ../art_src/alignright.svg
    extern const unsigned char aligntop_svg[510];  // ../art_src/aligntop.svg
    extern const unsigned char alignvertcenter_svg[642];  // ../art_src/alignvertcenter.svg
    extern const unsigned char auitoolbar_svg[7811];  // ../art_src/auitoolbar.svg
    extern const unsigned char bitmap_svg[1564];  // ../art_src/bitmap.svg
    extern const unsigned char bitmap_toggle_button_svg[1688];  // ../art_src/bitmap_toggle_button.svg
    extern const unsigned char bmp_combo_box_svg[1762];  // ../art_src/bmp_combo_box.svg
    extern const unsigned char book_page_svg[1038];  // ../art_src/book_page.svg
    extern const unsigned char bottom_svg[484];  // ../art_src/bottom.svg
    extern const unsigned char calendar_svg[2751];  // ../art_src/calendar.svg
    extern const unsigned char check3state_svg[234];  // ../art_src/check3state.svg
    extern const unsigned char clear_svg[8338];  // ../art_src/clear.svg
    extern const unsigned char close_btn_svg[593];  // ../art_src/close_btn.svg
    extern const unsigned char colourPickerIcon_svg[4304];  // ../art_src/colourPickerIcon.svg
    extern const unsigned char cpp_logo_svg[664];  // ../art_src/cpp_logo.svg
    extern const unsigned char ctx_help_btn_svg[686];  // ../art_src/ctx_help_btn.svg
    extern const unsigned char data_list_svg[1088];  // ../art_src/data_list.svg
    extern const unsigned char dataview_ctrl_png[231];  // ../art_src/dataview_ctrl.png
    extern const unsigned char dataviewlist_ctrl_png[685];  // ../art_src/dataviewlist_ctrl.png
    extern const unsigned char dataviewtree_ctrl_png[238];  // ../art_src/dataviewtree_ctrl.png
    extern const unsigned char datepicker_svg[3836];  // ../art_src/datepicker.svg
    extern const unsigned char debug_logo_svg[11593];  // ../art_src/debug_logo.svg
    extern const unsigned char default_png[518];  // ../art_src/default.png
    extern const unsigned char dirPicker_svg[2772];  // ../art_src/dirPicker.svg
    extern const unsigned char duplicate_svg[2742];  // ../art_src/duplicate.svg
    extern const unsigned char empty_png[101];  // ../art_src/empty.png
    extern const unsigned char filePicker_svg[54464];  // ../art_src/filePicker.svg
    extern const unsigned char flex_grid_sizer_svg[330];  // ../art_src/flex_grid_sizer.svg
    extern const unsigned char folder_svg[661];  // ../art_src/folder.svg
    extern const unsigned char fontPicker_svg[4008];  // ../art_src/fontPicker.svg
    extern const unsigned char gauge_svg[285];  // ../art_src/gauge.svg
    extern const unsigned char generate_svg[2435];  // ../art_src/generate.svg
    extern const unsigned char grid_bag_sizer_svg[272];  // ../art_src/grid_bag_sizer.svg
    extern const unsigned char grid_sizer_svg[483];  // ../art_src/grid_sizer.svg
    extern const unsigned char grid_svg[1863];  // ../art_src/grid.svg
    extern const unsigned char hide_svg[994];  // ../art_src/hide.svg
    extern const unsigned char images_svg[2344];  // ../art_src/images.svg
    extern const unsigned char import_svg[2454];  // ../art_src/import.svg
    extern const unsigned char left_svg[437];  // ../art_src/left.svg
    extern const unsigned char new_project_svg[1062];  // ../art_src/new-project.svg
    extern const unsigned char notebook_aui_svg[1615];  // ../art_src/notebook_aui.svg
    extern const unsigned char notebook_choice_svg[2122];  // ../art_src/notebook_choice.svg
    extern const unsigned char notebook_list_svg[1313];  // ../art_src/notebook_list.svg
    extern const unsigned char notebook_svg[1232];  // ../art_src/notebook.svg
    extern const unsigned char pagectrl_svg[2307];  // ../art_src/pagectrl.svg
    extern const unsigned char popup_window_svg[1282];  // ../art_src/popup_window.svg
    extern const unsigned char preferences_svg[2113];  // ../art_src/preferences.svg
    extern const unsigned char project_svg[3759];  // ../art_src/project.svg
    extern const unsigned char prop_sheet_dlg_svg[12384];  // ../art_src/prop_sheet_dlg.svg
    extern const unsigned char propgrid_cat_svg[18583];  // ../art_src/propgrid_cat.svg
    extern const unsigned char propgriditem_svg[16566];  // ../art_src/propgriditem.svg
    extern const unsigned char propgridpage_svg[19172];  // ../art_src/propgridpage.svg
    extern const unsigned char python_logo_only_svg[985];  // ../art_src/python-logo-only.svg
    extern const unsigned char radio_box_svg[9527];  // ../art_src/radio_box.svg
    extern const unsigned char redo_svg[913];  // ../art_src/redo.svg
    extern const unsigned char ribbon_bar_svg[2353];  // ../art_src/ribbon_bar.svg
    extern const unsigned char ribbon_buttonbar_png[300];  // ../art_src/ribbon_buttonbar.png
    extern const unsigned char ribbon_gallery_png[215];  // ../art_src/ribbon_gallery.png
    extern const unsigned char richtextctrl_svg[2949];  // ../art_src/richtextctrl.svg
    extern const unsigned char right_svg[677];  // ../art_src/right.svg
    extern const unsigned char ruby_logo_svg[967];  // ../art_src/ruby_logo.svg
    extern const unsigned char saveas_svg[5968];  // ../art_src/saveas.svg
    extern const unsigned char scintilla_svg[53987];  // ../art_src/scintilla.svg
    extern const unsigned char scrollbar_png[214];  // ../art_src/scrollbar.png
    extern const unsigned char search_svg[1485];  // ../art_src/search.svg
    extern const unsigned char sizer_horizontal_svg[302];  // ../art_src/sizer_horizontal.svg
    extern const unsigned char sizer_svg[302];  // ../art_src/sizer.svg
    extern const unsigned char slider_svg[303];  // ../art_src/slider.svg
    extern const unsigned char spacer_svg[263];  // ../art_src/spacer.svg
    extern const unsigned char spin_ctrl_double_svg[1070];  // ../art_src/spin_ctrl_double.svg
    extern const unsigned char spin_ctrl_svg[827];  // ../art_src/spin_ctrl.svg
    extern const unsigned char spinbtn_svg[355];  // ../art_src/spinbtn.svg
    extern const unsigned char static_line_svg[208];  // ../art_src/static_line.svg
    extern const unsigned char stddialogbuttonsizer_svg[1676];  // ../art_src/stddialogbuttonsizer.svg
    extern const unsigned char svg_svg[1653];  // ../art_src/svg.svg
    extern const unsigned char text_file_svg[2720];  // ../art_src/text_file.svg
    extern const unsigned char text_sizer_svg[311];  // ../art_src/text_sizer.svg
    extern const unsigned char timepicker_svg[3366];  // ../art_src/timepicker.svg
    extern const unsigned char title_close_png[144];  // ../art_src/title_close.png
    extern const unsigned char toggle_button_svg[1505];  // ../art_src/toggle_button.svg
    extern const unsigned char toolStretchable_svg[1880];  // ../art_src/toolStretchable.svg
    extern const unsigned char tool_dropdown_svg[1267];  // ../art_src/tool_dropdown.svg
    extern const unsigned char tool_svg[6332];  // ../art_src/tool.svg
    extern const unsigned char toolseparator_svg[1732];  // ../art_src/toolseparator.svg
    extern const unsigned char toolspacer_svg[1671];  // ../art_src/toolspacer.svg
    extern const unsigned char top_svg[435];  // ../art_src/top.svg
    extern const unsigned char undo_svg[689];  // ../art_src/undo.svg
    extern const unsigned char unknown_png[1699];  // ../art_src/unknown.png
    extern const unsigned char unknown_svg[1426];  // ../art_src/unknown.svg
    extern const unsigned char wrap_sizer_svg[435];  // ../art_src/wrap_sizer.svg
    extern const unsigned char wxButton_svg[693];  // ../art_src/wxButton.svg
    extern const unsigned char wxCheckBox_svg[782];  // ../art_src/wxCheckBox.svg
    extern const unsigned char wxCheckListBox_png[498];  // ../art_src/wxCheckListBox.png
    extern const unsigned char wxChoice_svg[2432];  // ../art_src/wxChoice.svg
    extern const unsigned char wxCollapsiblePane_svg[3838];  // ../art_src/wxCollapsiblePane.svg
    extern const unsigned char wxComboBox_svg[304];  // ../art_src/wxComboBox.svg
    extern const unsigned char wxCommandLinkButton_svg[3399];  // ../art_src/wxCommandLinkButton.svg
    extern const unsigned char wxDialog_svg[4638];  // ../art_src/wxDialog.svg
    extern const unsigned char wxEditListBox_png[707];  // ../art_src/wxEditListBox.png
    extern const unsigned char wxFB_1_5x_png[2162];  // ../art_src/wxFB_1_5x.png
    extern const unsigned char wxFB_2x_png[5606];  // ../art_src/wxFB_2x.png
    extern const unsigned char wxFB_png[609];  // ../art_src/wxFB.png
    extern const unsigned char wxFrame_svg[2968];  // ../art_src/wxFrame.svg
    extern const unsigned char wxGlade_png[224];  // ../art_src/wxGlade.png
    extern const unsigned char wxListBox_png[310];  // ../art_src/wxListBox.png
    extern const unsigned char wxListView_png[356];  // ../art_src/wxListView.png
    extern const unsigned char wxPanel_svg[332];  // ../art_src/wxPanel.svg
    extern const unsigned char wxPropertyGridManager_svg[19542];  // ../art_src/wxPropertyGridManager.svg
    extern const unsigned char wxPropertyGrid_svg[18564];  // ../art_src/wxPropertyGrid.svg
    extern const unsigned char wxPython_svg[12402];  // ../art_src/wxPython.svg
    extern const unsigned char wxRadioButton_svg[594];  // ../art_src/wxRadioButton.svg
    extern const unsigned char wxRearrangeCtrl_png[332];  // ../art_src/wxRearrangeCtrl.png
    extern const unsigned char wxScrolledWindow_svg[535];  // ../art_src/wxScrolledWindow.svg
    extern const unsigned char wxSimpleHtmlListBox_png[676];  // ../art_src/wxSimpleHtmlListBox.png
    extern const unsigned char wxSimplebook_svg[3182];  // ../art_src/wxSimplebook.svg
    extern const unsigned char wxSmith_1_5x_png[1407];  // ../art_src/wxSmith_1_5x.png
    extern const unsigned char wxSmith_2x_png[2211];  // ../art_src/wxSmith_2x.png
    extern const unsigned char wxSmith_png[797];  // ../art_src/wxSmith.png
    extern const unsigned char wxSplitterWindow_svg[3078];  // ../art_src/wxSplitterWindow.svg
    extern const unsigned char wxStaticBoxSizer_svg[2367];  // ../art_src/wxStaticBoxSizer.svg
    extern const unsigned char wxStaticCheckBoxSizer_svg[2593];  // ../art_src/wxStaticCheckBoxSizer.svg
    extern const unsigned char wxStaticRadioBtnSizer_svg[2424];  // ../art_src/wxStaticRadioBtnSizer.svg
    extern const unsigned char wxStaticText_svg[1342];  // ../art_src/wxStaticText.svg
    extern const unsigned char wxTextCtrl_svg[1417];  // ../art_src/wxTextCtrl.svg
    extern const unsigned char wxTimer_svg[4440];  // ../art_src/wxTimer.svg
    extern const unsigned char wxToolBar_svg[1677];  // ../art_src/wxToolBar.svg
    extern const unsigned char wxToolbook_svg[7198];  // ../art_src/wxToolbook.svg
    extern const unsigned char wxTreebook_svg[2845];  // ../art_src/wxTreebook.svg
    extern const unsigned char wxUiEditor_svg[4381];  // ../art_src/wxUiEditor.svg
    extern const unsigned char wxWizardPageSimple_svg[1092];  // ../art_src/wxWizardPageSimple.svg
    extern const unsigned char wxWizard_svg[6433];  // ../art_src/wxWizard.svg
    extern const unsigned char wxcrafter_png[701];  // ../art_src/wxcrafter.png
    extern const unsigned char wxlogo_svg[1476];  // ../art_src/wxlogo.svg
    extern const unsigned char xml_file_svg[1176];  // ../art_src/xml_file.svg
    extern const unsigned char xrc_compare_svg[438];  // ../art_src/xrc_compare.svg
    extern const unsigned char xrc_preview_svg[2147];  // ../art_src/xrc_preview.svg
    extern const unsigned char xrc_tests_svg[1886];  // ../art_src/xrc_tests.svg
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
