///////////////////////////////////////////////////////////////////////////////
// <auto-generated>
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT ANYTHING IN THIS FILE UNTIL AFTER THE </auto-generated> MARKER
// All changes before that marker will be lost if the code is re-generated.
///////////////////////////////////////////////////////////////////////////////

// clang-format off
// NOLINTBEGIN
// cppcheck-suppress-begin *

#pragma once

#include <memory>  // for std::make_unique

namespace wxue_data
{
    std::unique_ptr<unsigned char[]> get_data(const unsigned char* data, size_t size_data, size_t size_data_uncompressed);

}

namespace wxue_data
{
    std::string get_bars();        // ../xml/bars.xml
    std::string get_boxes();       // ../xml/boxes.xml
    std::string get_buttons();     // ../xml/buttons.xml
    std::string get_containers();  // ../xml/containers.xml
    std::string get_data_ctrls();  // ../xml/data_ctrls.xml
    std::string get_forms();       // ../xml/forms.xml
    std::string get_interfaces();  // ../xml/interfaces.xml
    std::string get_mdi();         // ../xml/mdi.xml
    std::string get_pickers();     // ../xml/pickers.xml
    std::string get_project();     // ../xml/project.xml
    std::string get_sizers();      // ../xml/sizers.xml
    std::string get_text_ctrls();  // ../xml/text_ctrls.xml
    std::string get_widgets();     // ../xml/widgets.xml

    // ../xml/bars.xml
    extern const unsigned char bars[6256]; // Original size: 39,199 bytes
    // ../xml/boxes.xml
    extern const unsigned char boxes[2429]; // Original size: 14,336 bytes
    // ../xml/buttons.xml
    extern const unsigned char buttons[2721]; // Original size: 15,325 bytes
    // ../xml/containers.xml
    extern const unsigned char containers[5004]; // Original size: 27,443 bytes
    // ../xml/data_ctrls.xml
    extern const unsigned char data_ctrls[8341]; // Original size: 47,178 bytes
    // ../xml/forms.xml
    extern const unsigned char forms[6635]; // Original size: 55,979 bytes
    // ../xml/interfaces.xml
    extern const unsigned char interfaces[11351]; // Original size: 57,955 bytes
    // ../xml/mdi.xml
    extern const unsigned char mdi[1995]; // Original size: 17,170 bytes
    // ../xml/pickers.xml
    extern const unsigned char pickers[2480]; // Original size: 10,219 bytes
    // ../xml/project.xml
    extern const unsigned char project[1672]; // Original size: 6,203 bytes
    // ../xml/sizers.xml
    extern const unsigned char sizers[2268]; // Original size: 12,871 bytes
    // ../xml/text_ctrls.xml
    extern const unsigned char text_ctrls[7105]; // Original size: 30,396 bytes
    // ../xml/widgets.xml
    extern const unsigned char widgets[6714]; // Original size: 28,672 bytes
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// NOLINTEND
// cppcheck-suppress-end *
// ***********************************************
// </auto-generated>
