# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (sdi_generated_code

    # Non-base classes
    ${CMAKE_CURRENT_LIST_DIR}/cpp/booktest_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/commonctrls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/images.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/mainframe.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/popupwin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/python_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/testformpanel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/wizard.cpp

    # Base classes
    ${CMAKE_CURRENT_LIST_DIR}/cpp/dlgissue_956.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/dlgissue_960.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/form_toolbar_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/maintestdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/tools_dlg.cpp

)
