# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (wxui_internal

    ${CMAKE_CURRENT_LIST_DIR}/code_compare.cpp
    ${CMAKE_CURRENT_LIST_DIR}/convert_img_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/debugsettings_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msgframe_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/node_info.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrcpreview.cpp

)
