# Updated by ttBld.exe version 1.8.1 -- see https://github.com/KeyWorksRW/ttBld

Options:
    Project:          wxUiEditor # project name
    # Exe_type:         window   # [window | console | lib | dll]
    Exe_type:         lib   # This is just for clang-cl to verify compilation, so we don't need a full link
    Pch:              pch.h    # name of precompiled header file, or "none" if not using precompiled headers
    Ms_linker:        true     # true means use link.exe even when compiling with clang-cl

    Optimize:         space    # [space | speed] optimization to use in release builds
    Warn:             4        # [1-4] warning level
    Crt_rel:          dll      # [static | dll] type of CRT to link to in release builds
    Crt_dbg:          dll      # [static | dll] type of CRT to link to in debug builds

    CFlags_cmn:       /std:c++17 /Zc:__cplusplus /utf-8 /DUNICODE
    CFlags_rel:       /DNDEBUG # static wxWidgets libraries in release build

    # TargetDir:        ../bin   # target directory
    TargetDir:        ../build/CMakeFiles/CMakeTmp   # just a temporary location for the library
    Natvis:           wxui.natvis # MSVC Debug visualizer

    IncDirs:          ./;nodes;generate;utils;customprops;ui;../wxSnapshot/include;../wxSnapshot/win;../ttLib/include;../pugixml

    Libs_dbg:         ../build/wxSnapshot/Debug/wxCLib.lib;../build/wxSnapshot/Debug/wxWidgets.lib
    Libs_rel:         ../build/wxSnapshot/Release/wxCLib.lib;../build/wxSnapshot/Release/wxWidgets.lib

# file_list.cmake

Files:
    wxUiEditor.rc         # Only processed when compiling for Windows, ignored otherwise

    mainapp.cpp           # Main application class
    mainframe.cpp         # Main window frame

    appoptions.cpp        # Application-wide options
    bitmaps.cpp           # Map of bitmaps accessed by name
    clipboard.cpp         # Handles reading and writing OS clipboard data
    cstm_event.cpp        # Custom Event handling
    frame_status_bar.cpp  # MainFrame status bar functions
    gen_enums.cpp         # Enumerations for generators
    lambdas.cpp           # Functions for formatting and storage of lamda events
    pjtsettings.cpp       # Hold data for currently loaded project
    startup.cpp           # Dialog to display is wxUE is launched with no arguments
    undo_cmds.cpp         # Undoable command classes derived from UndoStackCmd
    undo_stack.cpp        # Maintain an undo and redo stack
    wakatime.cpp          # Updates WakaTime metrics
    xpm.cpp               # All xpm files

    customprops/code_string_prop.cpp    # Derived wxStringProperty class for code
    customprops/custom_param_prop.cpp   # Derived wxStringProperty class for custom control parameters
    customprops/evt_string_prop.cpp     # Derived wxStringProperty class for event function
    customprops/img_string_prop.cpp     # Derived wxStringProperty class for handling wxImage files or art
    customprops/txt_string_prop.cpp     # Derived wxStringProperty class for single-line text
    customprops/custom_colour_prop.cpp  # Property editor for colour

    customprops/art_prop_dlg.cpp   # Art Property Dialog for image property
    customprops/img_props.cpp      # Handles property grid image properties

    customprops/pg_image.cpp       # Custom property grid class for images
    customprops/pg_animation.cpp   # Custom property grid class for animations
    customprops/pg_point.cpp       # Custom wxPGProperty for wxPoint

    custom_ctrls/colour_rect_ctrl.cpp  # Control that displays a solid color

    generate/gen_base.cpp          # Generate Src and Hdr files for Base and Derived Class
    generate/gen_cmake.cpp         # Auto-generate a .cmake file
    generate/gen_codefiles.cpp     # Generate code files
    generate/gen_derived.cpp       # Generate Derived class code
    generate/gen_inherit.cpp       # Generate Inherited class code
    generate/write_code.cpp        # Write code to Scintilla or file

    generate/base_generator.cpp    # Base widget generator class
    generate/gen_initialize.cpp    # Initialize all widget generate classes
    generate/gen_common.cpp        # Common widget generation functions

    # The following files in generate/ are used to display the widget in the Mockup panel and to generate
    # the code to insert into the source and header files.

    generate/book_widgets.cpp      # Book generation classes
    generate/btn_widgets.cpp       # Button generation class
    generate/checkbox_widgets.cpp  # wxCheckBox generation class
    generate/combo_widgets.cpp     # Combo and choice generation classes
    generate/ctrl_widgets.cpp      # Calendar, GenericDir, Search Ctrl generation classes
    generate/dataview_widgets.cpp  # wxDataView generation classes
    generate/form_widgets.cpp      # Form generation classes
    generate/grid_widgets.cpp      # Grid generation classes
    generate/images_form.cpp       # Embedded images generator
    generate/listbox_widgets.cpp   # ListBox generation classes
    generate/listctrl_widgets.cpp  # ListCtrl generation class
    generate/menu_widgets.cpp      # Menu generation classes
    generate/misc_widgets.cpp      # Miscellaneous generation classes
    generate/panel_widgets.cpp     # Panel generation classes
    generate/picker_widgets.cpp    # Picker generation classes
    generate/radio_widgets.cpp     # Radio button and Radio box generation classes
    generate/ribbon_widgets.cpp    # Ribbon generation classes
    generate/sizer_widgets.cpp     # Sizer generation classes
    generate/spin_widgets.cpp      # Spin and ScrollBar generation classes
    generate/text_widgets.cpp      # Text generation classes
    generate/toolbar_widgets.cpp   # Toolbar generation classes
    generate/tree_widgets.cpp      # wxTreeCtrl generation classes
    generate/window_widgets.cpp    # Splitter and Scroll generation classes
    generate/wizard_form.cpp       # Wizard form class

    import/import_crafter_maps.cpp # wxCrafter mappings
    import/import_formblder.cpp    # Import a wxFormBuider project
    import/import_wxcrafter.cpp    # Import a wxCrafter project
    import/import_wxglade.cpp      # Import a Import a wxGlade file
    import/import_wxsmith.cpp      # Process XRC files
    import/import_xml.cpp          # Base class for XML importing

    mockup/mockup_parent.cpp    # Top-level MockUp Parent window
    mockup/mockup_content.cpp   # Mockup of a form's contents
    mockup/mockup_wizard.cpp    # Emulate a wxWizard

    nodes/node.cpp              # Contains user-modifiable node
    nodes/node_constants.cpp    # Maps wxWidgets constants to their numerical value
    nodes/node_creator.cpp      # Class used to create nodes
    nodes/node_decl.cpp         # Contains the declarations for a node (properties, events, etc.)
    nodes/node_gridbag.cpp      # Create and modify a node containing a wxGridBagSizer
    nodes/node_init.cpp         # Initialize NodeCreator class
    nodes/node_prop.cpp         # NodeProperty class
    nodes/tool_creator.cpp      # Functions for creating new nodes from Ribbon Panel

    panels/cstm_propgrid.cpp    # Derived wxPropertyGrid class
    panels/code_display.cpp     # Display code in scintilla control
    panels/base_panel.cpp       # Code generation panel
    panels/nav_panel.cpp        # Navigation panel
    panels/navpopupmenu.cpp     # Context-menu for Navigation panel
    panels/propgrid_panel.cpp   # Property panel
    panels/ribbon_tools.cpp     # Displays node creation tools in a wxRibbonBar

    project/loadproject.cpp     # Load wxUiEditor project
    project/saveproject.cpp     # Save a wxUiEditor project file

    utils/font_prop.cpp         # FontProperty class
    utils/utils.cpp             # Utility functions that work with properties

    winres/ctrl_utils.cpp       # resCtrl class utility functions
    winres/form_utils.cpp       # resForm class utility functions
    winres/import_winres.cpp    # Import a Windows resource file
    winres/winres_ctrl.cpp      # Process Windows Resource control data
    winres/winres_dlg.cpp       # Process a Windows Resource DIALOG or DIALOGEX
    winres/winres_menu.cpp      # Process a Windows Resource MENU
    winres/winres_images.cpp    # resCtrl class image/icon functions
    winres/winres_layout.cpp    # resForm layout code
    winres/winres_styles.cpp    # resCtrl style processing functions

    ../pugixml/pugixml.cpp      # XML parser

    ui/embedimg.cpp             # Convert image to Header (.h) or XPM (.xpm) file
    ui/eventhandlerdlg.cpp      # Dialog for editing event handlers
    ui/gridbag_item.cpp         # Dialog for inserting an item into a wxGridBagSizer node
    ui/import_dlg.cpp           # Dialog to import one or more projects
    ui/importwinresdlg.cpp      # Dialog for Importing a Windows resource file
    ui/insertwidget.cpp         # Dialog to lookup and insert a widget
    ui/newdialog.cpp            # Dialog for creating a new project dialog
    ui/newframe.cpp             # Dialog for creating a new project wxFrame
    ui/newribbon.cpp            # Dialog for creating a new wxRibbonBar
    ui/optionsdlg.cpp           # Dialog containing special Debugging commands

    # wxUiEditor generated files
    ui/wxui_code.cmake

    # ttLib submodule files (see https://github.com/KeyWorksRW/ttLib repository)

    ../ttLib/src/ttcstr.cpp             # Class for handling zero-terminated char strings.
    ../ttLib/src/ttcview.cpp            # string_view functionality on a zero-terminated char string.
    ../ttLib/src/ttsview.cpp            # std::string_view with additional methods
    ../ttLib/src/ttmultistr.cpp         # Breaks a single string into multiple strings
    ../ttLib/src/ttparser.cpp           # Command line parser
    ../ttLib/src/ttstr.cpp              # Enhanced version of wxString
    ../ttLib/src/ttlibspace.cpp         # ttlib namespace functions
    ../ttLib/src/tttextfile.cpp         # Classes for reading and writing text files.

DebugFiles:
    # Debug-only files

    debugging/msg_logging.cpp    # Message logging class
    debugging/msgframe.cpp       # Stores messages
    debugging/nodeinfo.cpp       # Node memory usage dialog
    debugging/nodeinfo_base.cpp  # wxUiEditor generated file

    debugging/dbg_code_diff.cpp       # Compare code generationg
    debugging/dbg_code_diff_base.cpp

    debugging/debugsettings.cpp         # Settings while running the Debug version of wxUiEditor
    debugging/debugsettingsBase.cpp     # wxUiEditor generated file
    debugging/msgframe_base.cpp         # wxUiEditor generated file

    ../ttLib/src/winsrc/ttdebug_min.cpp  # ttAssertionMsg

Docs:
    # ttBld will ignore this section -- it's here just for convenience as a shortcut to open some of the documentation
    # files.

    ../README.md
    ../docs/DEV_NOTES.md
    ../docs/import_crafter.md
    ../docs/import_formbuilder.md
    ../docs/import_winres.md
    nodes/README.md

    # The following are the XML files we use for interfaces and generators

    xml/README.md

    xml/interface_xml.xml
    xml/sizer_child_xml.xml
    xml/validators_xml.xml
    xml/window_interfaces_xml.xml

    xml/aui_xml.xml
    xml/bars_xml.xml
    xml/books_xml.xml
    xml/boxes_xml.xml
    xml/buttons_xml.xml
    xml/containers_xml.xml
    xml/dataview_xml.xml
    xml/dialogs_xml.xml
    xml/forms_xml.xml
    xml/grid_xml.xml
    xml/listview_xml.xml
    xml/menus_xml.xml
    xml/pickers_xml.xml
    xml/project_xml.xml
    xml/propgrid_xml.xml
    xml/ribbon_xml.xml
    xml/scintilla_xml.xml
    xml/sizers_xml.xml
    xml/std_dlg_btns_xml.xml
    xml/textctrls_xml.xml
    xml/toolbars_xml.xml
    xml/trees_xml.xml
    xml/widgets_xml.xml
    xml/wizard_xml.xml
