# Requires ttBld.exe version 1.7.2 or higher to process -- see https://github.com/KeyWorksRW/ttBld

# This version will automatically be used if ttBld is run on a Windows OS

Options:
    Project:     wxUiEditor   # project name
    Exe_type:    window       # [window | console | lib | dll]
    Pch:         pch.h        # name of precompiled header file, or "none" if not using precompiled headers
    Ms_linker:   true         # true means use link.exe even when compiling with clang-cl

    Optimize:    space        # [space | speed] optimization to use in release builds
    Warn:        4            # [1-4] warning level
    Crt_rel:     dll          # [static | dll] type of CRT to link to in release builds
    Crt_dbg:     dll          # [static | dll] type of CRT to link to in debug builds

    CFlags_cmn:  /std:c++17 /Zc:__cplusplus /utf-8
    CFlags_rel:  /DNDEBUG     # static wxWidgets libraries in release build
    CFlags_dbg:  -DWXUSINGDLL # dll wxWidgets libraries in debug build

    TargetDir:   ../bin       # target directory
    Natvis:      wxui.natvis  # MSVC Debug visualizer

    IncDirs:     ./;nodes;generate;utils;customprops;../ttLib

Files:
    wxUiEditor.rc         # Windows resources

    mainapp.cpp           # Main application class
    mainframe.cpp         # Main window frame

    appoptions.cpp        # Application-wide options
    bitmaps.cpp           # Map of bitmaps accessed by name
    clipboard.cpp
    cstm_event.cpp        # Custom Event handling
    gen_enums.cpp         # Enumerations for generators
    frame_status_bar.cpp  # MainFrame status bar functions
    gzip.cpp              # Convert compiled GZIP arrays into original strings/images
    pjtsettings.cpp       # Hold data for currently loaded project
    startup.cpp           # Dialog to display is wxUE is launched with no arguments
    strings.cpp           # Contains translatable strings
    undo_cmds.cpp         # Undoable command classes derived from UndoStackCmd
    undo_stack.cpp        # Maintain an undo and redo stack
    xpm.cpp               # All xpm files

    customprops/anim_string_prop.cpp  # Derived wxStringProperty class for handling animation files
    customprops/evt_string_prop.cpp   # Derived wxStringProperty class for event function
    customprops/img_string_prop.cpp   # Derived wxStringProperty class for handling wxImage files or art
    customprops/txt_string_prop.cpp   # Derived wxStringProperty class for single-line text

    customprops/art_prop_dlg.cpp      # Art Property Dialog for image property
    customprops/anim_props.cpp         # Handles property grid image properties
    customprops/img_props.cpp         # Handles property grid image properties

    customprops/pg_image.cpp          # Custom property grid class for images
    customprops/pg_animation.cpp      # Custom property grid class for animations
    customprops/pg_point.cpp          # Custom wxPGProperty for wxPoint
    customprops/pg_size.cpp           # Custom wxPGProperty for wxSize

    generate/gen_base.cpp          # Generate Src and Hdr files for Base and Derived Class
    generate/gen_codefiles.cpp     # Generate code files
    generate/gen_derived.cpp       # Generate Derived class code
    generate/gen_inherit.cpp       # Generate Inherited class code
    generate/write_code.cpp        # Write code to Scintilla or file

    generate/base_generator.cpp    # Base widget generator class
    generate/gen_initialize.cpp    # Initialize all widget generate classes
    generate/gen_common.cpp        # Common widget generation functions

    generate/book_widgets.cpp      # Book generation classes
    generate/btn_widgets.cpp       # Button generation class
    generate/checkbox_widgets.cpp  # wxCheckBox generation class
    generate/combo_widgets.cpp     # Combo and choice generation classes
    generate/ctrl_widgets.cpp      # Calendar, GenericDir, Search Ctrl generation classes
    generate/dataview_widgets.cpp  # wxDataView generation classes
    generate/form_widgets.cpp      # Form generation classes
    generate/grid_widgets.cpp      # Grid generation classes
    generate/listbox_widgets.cpp   # ListBox generation classes
    generate/listctrl_widgets.cpp  # ListCtrl generation class
    generate/menu_widgets.cpp      # Menu generation classes
    generate/misc_widgets.cpp      # Miscellaneous generation classes
    generate/panel_widgets.cpp     # Panel generation classes
    generate/picker_widgets.cpp    # Picker generation classes
    generate/radio_widgets.cpp     # Radio button and Radio box generation classes
    generate/ribbon_widgets.cpp    # Ribbon generation classes
    generate/sizer_widgets.cpp     # Sizer generation classes
    generate/spin_widgets.cpp      # Spin and ScrollBar generation classes
    generate/text_widgets.cpp      # Text generation classes
    generate/toolbar_widgets.cpp   # Toolbar generation classes
    generate/tree_widgets.cpp      # wxTreeCtrl generation classes
    generate/window_widgets.cpp    # Splitter and Scroll generation classes
    generate/wizard_form.cpp       # Wizard form class

    import/import_formblder.cpp    # Import a wxFormBuider project
    import/import_winres.cpp       # Import a Windows resource file
    import/import_wxglade.cpp      # Import a Import a wxGlade file
    import/import_wxsmith.cpp      # Process XRC files
    import/import_xml.cpp          # Base class for XML importing
    import/winres/winres_ctrl.cpp  # Process Windows Resource control data
    import/winres/winres_form.cpp  # Process a Windows Resource form (usually a dialog)

    mockup/mockup_parent.cpp    # Top-level MockUp Parent window
    mockup/mockup_content.cpp   # Mockup of a form's contents
    mockup/mockup_wizard.cpp    # Emulate a wxWizard

    nodes/node.cpp              # Contains user-modifiable node
    nodes/node_creator.cpp      # Class used to create nodes
    nodes/node_decl.cpp         # Contains the declarations for a node (properties, events, etc.)
    nodes/node_init.cpp         # Initialize NodeCreator class
    nodes/node_prop.cpp         # NodeProperty class
    nodes/node_types.cpp        # Stores node types and allowable child count

    panels/cstm_propgrid.cpp    # Derived wxPropertyGrid class
    panels/code_display.cpp     # Display code in scintilla control
    panels/base_panel.cpp       # Code generation panel
    panels/nav_panel.cpp        # Navigation panel
    panels/navpopupmenu.cpp     # Context-menu for Navigation panel
    panels/propgrid_panel.cpp   # Property panel
    panels/ribbon_tools.cpp     # Displays node creation tools in a wxRibbonBar

    project/loadproject.cpp       # Load wxUiEditor project
    project/oldproject.cpp        # Load older version of wxUiEditor project
    project/saveproject.cpp       # Save a wxUiEditor project file

    utils/font_prop.cpp         # FontProperty class
    utils/loadxml.cpp           # Load internal xml files
    utils/utils.cpp             # Utility functions that work with properties

    ../pugixml/pugixml.cpp      # XML parser

    ui/embedimg.cpp             # Convert image to Header (.h) or XPM (.xpm) file
    ui/eventhandlerdlg.cpp      # Dialog for editing event handlers
    ui/importwinresdlg.cpp      # Dialog for Importing a Windows resource file
    ui/insertdialog.cpp
    ui/newproject.cpp           # Dialog to create a new project
    ui/optionsdlg.cpp           # Dialog containing special Debugging commands

# wxUiEditor generated files

    ui/artpropdlg_base.cpp
    ui/editstringdialog_base.cpp
    ui/embedimg_base.cpp
    ui/eventhandlerdlg_base.cpp
    ui/importwinres_base.cpp
    ui/insertdialog_base.cpp
    ui/mainframe_base.cpp
    ui/newproject_base.cpp
    ui/optionsdlg_base.cpp
    ui/ribbonpanel_base.cpp

    ../ttLib/ttcstr.cpp
    ../ttLib/ttcview.cpp
    ../ttLib/ttmultistr.cpp
    ../ttLib/ttparser.cpp
    ../ttLib/ttstr.cpp
    ../ttLib/ttlibspace.cpp
    ../ttLib/ttstrings.cpp
    ../ttLib/tttextfile.cpp

DebugFiles:
    debugging/msg_logging.cpp    # Message logging class
    debugging/msgframe.cpp       # Stores messages
    debugging/nodeinfo.cpp       # Node memory usage dialog
    debugging/nodeinfo_base.cpp

    ui/debugsettings.cpp        # Settings while running the Debug version of wxUiEditor
    ui/debugsettingsBase.cpp
    ui/msgframe_base.cpp

    ../ttLib/ttdebug.cpp

GZIP:
    xml/aui.xml: xml/aui.hgz
    xml/bars.xml: xml/bars.hgz
    xml/containers.xml: xml/containers.hgz
    xml/forms.xml: xml/forms.hgz
    xml/interface.xml: xml/interface.hgz
    xml/sizers.xml: xml/sizers.hgz
    xml/widgets.xml: xml/widgets.hgz

PNG:
    art_src/alignbottom.png: art_headers/alignbottom_png.hxx
    art_src/aligncenter.png: art_headers/aligncenter_png.hxx
    art_src/alignleft.png: art_headers/alignleft_png.hxx
    art_src/alignright.png: art_headers/alignright_png.hxx
    art_src/aligntop.png: art_headers/aligntop_png.hxx
    art_src/alignvertcenter.png: art_headers/alignvertcenter_png.hxx
    art_src/bottom.png: art_headers/bottom_png.hxx
    art_src/expand.png: art_headers/expand_png.hxx
    art_src/generate.png: art_headers/generate_png.hxx
    art_src/hidden.png: art_headers/hidden_png.hxx
    art_src/left.png: art_headers/left_png.hxx
    art_src/magnify.png: art_headers/magnify_png.hxx
    art_src/nav_coll_expand.png: art_headers/nav_coll_expand_png.hxx
    art_src/nav_collapse.png: art_headers/nav_collapse_png.hxx
    art_src/nav_expand.png: art_headers/nav_expand_png.hxx
    art_src/nav_movedown.png: art_headers/nav_movedown_png.hxx
    art_src/nav_moveleft.png: art_headers/nav_moveleft_png.hxx
    art_src/nav_moveright.png: art_headers/nav_moveright_png.hxx
    art_src/nav_moveup.png: art_headers/nav_moveup_png.hxx
    art_src/new.png: art_headers/new_png.hxx
    art_src/right.png: art_headers/right_png.hxx
    art_src/save.png: art_headers/save_png.hxx
    art_src/top.png: art_headers/top_png.hxx

    art_src/default.png: art_headers/default_png.hxx
    art_src/empty.png: art_headers/empty_png.hxx
    art_src/title_close.png: art_headers/title_close_png.hxx
    art_src/unknown.png: art_headers/unknown_png.hxx

    art_src/debug_16.png: art_headers/debug_16_png.hxx
    art_src/debug_32.png: art_headers/debug_32_png.hxx
    art_src/logo16.png: art_headers/logo16_png.hxx
    art_src/logo32.png: art_headers/logo32_png.hxx
    art_src/logo64.png: art_headers/logo64_png.hxx

    art_src/flex_grid_sizer.png: art_headers/flex_grid_sizer_png.hxx
    art_src/grid_bag_sizer.png: art_headers/grid_bag_sizer_png.hxx
    art_src/grid_sizer.png: art_headers/grid_sizer_png.hxx
    art_src/sizer.png: art_headers/sizer_png.hxx
    art_src/sizer_horizontal.png: art_headers/sizer_horizontal_png.hxx
    art_src/spacer.png: art_headers/spacer_png.hxx
    art_src/stddialogbuttonsizer.png: art_headers/stddialogbuttonsizer_png.hxx
    art_src/text_sizer.png: art_headers/text_sizer_png.hxx
    art_src/wrap_sizer.png: art_headers/wrap_sizer_png.hxx
    art_src/wxStaticBoxSizer.png: art_headers/wxStaticBoxSizer_png.hxx
    art_src/wxStaticCheckBoxSizer.png: art_headers/wxStaticCheckBoxSizer_png.hxx
    art_src/wxStaticRadioBtnSizer.png: art_headers/wxStaticRadioBtnSizer_png.hxx

    art_src/auinotebook.png: art_headers/auinotebook_png.hxx
    art_src/auitoolbar.png: art_headers/auitoolbar_png.hxx
    art_src/bitmap_button.png: art_headers/bitmap_button_png.hxx
    art_src/bitmap_toggle_button.png: art_headers/bitmap_toggle_button_png.hxx
    art_src/bmp_combo_box.png: art_headers/bmp_combo_box_png.hxx
    art_src/book_page.png: art_headers/book_page_png.hxx
    art_src/calendar.png: art_headers/calendar_png.hxx
    art_src/check3state.png: art_headers/check3state_png.hxx
    art_src/colourPickerIcon.png: art_headers/colourPickerIcon_png.hxx
    art_src/dataview_ctrl.png: art_headers/dataview_ctrl_png.hxx
    art_src/dataviewlist_column.png: art_headers/dataviewlist_column_png.hxx
    art_src/dataviewlist_ctrl.png: art_headers/dataviewlist_ctrl_png.hxx
    art_src/dataviewtree_ctrl.png: art_headers/dataviewtree_ctrl_png.hxx
    art_src/datepicker.png: art_headers/datepicker_png.hxx
    art_src/dirPicker.png: art_headers/dirPicker_png.hxx
    art_src/doc_mdi_parent_frame.png: art_headers/doc_mdi_parent_frame_png.hxx
    art_src/doc_parent_frame.png: art_headers/doc_parent_frame_png.hxx
    art_src/document.png: art_headers/document_png.hxx
    art_src/empty.png: art_headers/empty_png.hxx
    art_src/filePicker.png: art_headers/filePicker_png.hxx
    art_src/fontPicker.png: art_headers/fontPicker_png.hxx
    art_src/gauge.png: art_headers/gauge_png.hxx
    art_src/genericdir_ctrl.png: art_headers/genericdir_ctrl_png.hxx
    art_src/grid.png: art_headers/grid_png.hxx
    art_src/htmlwin.png: art_headers/htmlwin_png.hxx
    art_src/hyperlink_ctrl.png: art_headers/hyperlink_ctrl_png.hxx
    art_src/infobar.png: art_headers/infobar_png.hxx
    art_src/menu.png: art_headers/menu_png.hxx
    art_src/menuitem.png: art_headers/menuitem_png.hxx
    art_src/moveColLeft.png: art_headers/moveColLeft_png.hxx
    art_src/moveColRight.png: art_headers/moveColRight_png.hxx
    art_src/moveRowDown.png: art_headers/moveRowDown_png.hxx
    art_src/moveRowUp.png: art_headers/moveRowUp_png.hxx
    art_src/project.png: art_headers/project_png.hxx
    art_src/propgriditem.png: art_headers/propgriditem_png.hxx
    art_src/propgridpage.png: art_headers/propgridpage_png.hxx
    art_src/radio_box.png: art_headers/radio_box_png.hxx
    art_src/ribbon_bar.png: art_headers/ribbon_bar_png.hxx
    art_src/ribbon_button.png: art_headers/ribbon_button_png.hxx
    art_src/ribbon_button_dropdown.png: art_headers/ribbon_button_dropdown_png.hxx
    art_src/ribbon_button_hybrid.png: art_headers/ribbon_button_hybrid_png.hxx
    art_src/ribbon_button_toggle.png: art_headers/ribbon_button_toggle_png.hxx
    art_src/ribbon_buttonbar.png: art_headers/ribbon_buttonbar_png.hxx
    art_src/ribbon_gallery.png: art_headers/ribbon_gallery_png.hxx
    art_src/ribbon_gallery_item.png: art_headers/ribbon_gallery_item_png.hxx
    art_src/ribbon_page.png: art_headers/ribbon_page_png.hxx
    art_src/ribbon_panel.png: art_headers/ribbon_panel_png.hxx
    art_src/richtextctrl.png: art_headers/richtextctrl_png.hxx
    art_src/scintilla.png: art_headers/scintilla_png.hxx
    art_src/scrollbar.png: art_headers/scrollbar_png.hxx
    art_src/search.png: art_headers/search_png.hxx
    art_src/separator.png: art_headers/separator_png.hxx
    art_src/slider.png: art_headers/slider_png.hxx
    art_src/spin_ctrl.png: art_headers/spin_ctrl_png.hxx
    art_src/spin_ctrl_double.png: art_headers/spin_ctrl_double_png.hxx
    art_src/spinbtn.png: art_headers/spinbtn_png.hxx
    art_src/static_bitmap.png: art_headers/static_bitmap_png.hxx
    art_src/static_line.png: art_headers/static_line_png.hxx
    art_src/statusbar.png: art_headers/statusbar_png.hxx
    art_src/submenu.png: art_headers/submenu_png.hxx
    art_src/timepicker.png: art_headers/timepicker_png.hxx
    art_src/timer.png: art_headers/timer_png.hxx
    art_src/title_close.png: art_headers/title_close_png.hxx
    art_src/toggle_button.png: art_headers/toggle_button_png.hxx
    art_src/tool.png: art_headers/tool_png.hxx
    art_src/toolseparator.png: art_headers/toolseparator_png.hxx
    art_src/tree_ctrl.png: art_headers/tree_ctrl_png.hxx
    art_src/treelistctrl.png: art_headers/treelistctrl_png.hxx
    art_src/treelistctrlcolumn.png: art_headers/treelistctrlcolumn_png.hxx
    art_src/wxActivityIndicator.png: art_headers/wxActivityIndicator_png.hxx
    art_src/wxBannerWindow.png: art_headers/wxBannerWindow_png.hxx
    art_src/wxButton.png: art_headers/wxButton_png.hxx
    art_src/wxCheckBox.png: art_headers/wxCheckBox_png.hxx
    art_src/wxCheckListBox.png: art_headers/wxCheckListBox_png.hxx
    art_src/wxChoice.png: art_headers/wxChoice_png.hxx
    art_src/wxChoicebook.png: art_headers/wxChoicebook_png.hxx
    art_src/wxCollapsiblePane.png: art_headers/wxCollapsiblePane_png.hxx
    art_src/wxComboBox.png: art_headers/wxComboBox_png.hxx
    art_src/wxCommandLinkButton.png: art_headers/wxCommandLinkButton_png.hxx
    art_src/wxDialog.png: art_headers/wxDialog_png.hxx
    art_src/wxFileCtrl.png: art_headers/wxFileCtrl_png.hxx
    art_src/wxFrame.png: art_headers/wxFrame_png.hxx
    art_src/wxListBox.png: art_headers/wxListBox_png.hxx
    art_src/wxListView.png: art_headers/wxListView_png.hxx
    art_src/wxListbook.png: art_headers/wxListbook_png.hxx
    art_src/wxMenuBar.png: art_headers/wxMenuBar_png.hxx
    art_src/wxNotebook.png: art_headers/wxNotebook_png.hxx
    art_src/wxPanel.png: art_headers/wxPanel_png.hxx
    art_src/wxPopupTransientWindow.png: art_headers/wxPopupTransientWindow_png.hxx
    art_src/wxPropertyGrid.png: art_headers/wxPropertyGrid_png.hxx
    art_src/wxPropertyGridManager.png: art_headers/wxPropertyGridManager_png.hxx
    art_src/wxRadioButton.png: art_headers/wxRadioButton_png.hxx
    art_src/wxRearrangeCtrl.png: art_headers/wxRearrangeCtrl_png.hxx
    art_src/wxScrolledWindow.png: art_headers/wxScrolledWindow_png.hxx
    art_src/wxSimpleHtmlListBox.png: art_headers/wxSimpleHtmlListBox_png.hxx
    art_src/wxSimplebook.png: art_headers/wxSimplebook_png.hxx
    art_src/wxSplitterWindow.png: art_headers/wxSplitterWindow_png.hxx
    art_src/wxStaticText.png: art_headers/wxStaticText_png.hxx
    art_src/wxTextCtrl.png: art_headers/wxTextCtrl_png.hxx
    art_src/wxToolBar.png: art_headers/wxToolBar_png.hxx
    art_src/wxToolbook.png: art_headers/wxToolbook_png.hxx
    art_src/wxTreebook.png: art_headers/wxTreebook_png.hxx
    art_src/wxWizard.png: art_headers/wxWizard_png.hxx
    art_src/wxWizardPageSimple.png: art_headers/wxWizardPageSimple_png.hxx

Docs:
    ../README.md
    ../docs/DEV_NOTES.md
    ../docs/import_formbuilder.md
    nodes/README.md
    xml/README.md
