////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor ( https://github.com/KeyWorksRW/wxUiEditor/ )
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////

#pragma once

#include <wx/string.h>
#include <wx/frame.h>
#include <wx/gdicmn.h>

class MainFrameBase : public wxFrame
{
public:
	MainFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = "wxUiTesting",
		const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300),
		long style = wxDEFAULT_FRAME_STYLE| wxTAB_TRAVERSAL);

protected:
private:
};
