///////////////////////////////////////////////////////////////////////////
// Original code generated by wxUiEditor
//
// The code is generated only once. You can now modify the code as needed.
///////////////////////////////////////////////////////////////////////////

#include "pch.h"


#include "other_ctrls.h"  // auto-generated: other_ctrls_base.h and other_ctrls_base.cpp

OtherCtrlsDlg::OtherCtrlsDlg(wxWindow* parent) : OtherCtrlsBase(parent)
{

}
