////////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////////

#include "pch.h"

#include <wx/sizer.h>

#include "popupwin_base.h"

PopupWinBase::PopupWinBase(wxWindow* parent, int border) : wxPopupTransientWindow(parent, border)
{
    auto parent_sizer = new wxBoxSizer(wxVERTICAL);

    m_staticText = new wxStaticText(this, wxID_ANY, wxString::FromUTF8("This is a wxPopupTransientWindow set to use a raised border around it. Note that the default is to not have a border at all.\n\nClick outside this window to dismiss it."));
    m_staticText->Wrap(250);
    parent_sizer->Add(m_staticText, wxSizerFlags().Border(wxALL));

    SetSizerAndFit(parent_sizer);
}
