////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////

#pragma once

#include <wx/dialog.h>
#include <wx/gdicmn.h>
#include <wx/ribbon/art.h>
#include <wx/ribbon/bar.h>
#include <wx/ribbon/control.h>

class RibbonDlgBase : public wxDialog
{
public:
    RibbonDlgBase(wxWindow* parent, wxWindowID id = wxID_ANY,
        const wxString& title = wxString::FromUTF8("Ribbon Dialog"),
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500, 300),
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);

protected:

    // Class member variables

    wxRibbonBar* m_rbnBar;
};
