name: "Build Unix Executable"

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  buildUnix:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: mkdir ${{github.workspace}}/build

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++-11.4 ninja-build libgtk-3-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build wxUiEditor
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target wxUiEditor

    - name: Build Setup
      run: |
        cd build
        cpack -G DEB -C Release

    - name: Create wxUiEditor Artifact
      uses: actions/upload-artifact@v3
      with:
        name: UnixExecutable
        path: |
          build/wxUiEditor-1.1.3-Linux.deb
