name: "Windows Debug Build"

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  buildWindows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - run: mkdir ${{github.workspace}}/build

    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build wxUiEditor
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target wxUiEditor

    - name: Create Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WindowsExecutable
        path: |
          build/bin/Debug/wxUiEditor.exe
